ServerEvents.recipes(event => {
//Solids
    event.recipes.gtceu.large_boiler('coal')
        .itemInputs('minecraft:coal')
        .duration(220)
    event.recipes.gtceu.large_boiler('charcoal')
        .itemInputs('minecraft:charcoal')
        .duration(220)
    event.recipes.gtceu.large_boiler('blaze_rod')
        .itemInputs('minecraft:blaze_rod')
        .duration(330)
    event.recipes.gtceu.large_boiler('coke_gem')
        .itemInputs('gtceu:coke_gem')
        .duration(440)
    event.recipes.gtceu.large_boiler('dried_kelp_block')
        .itemInputs('minecraft:dried_kelp_block')
        .duration(550)
    event.recipes.gtceu.large_boiler('blaze_cake')
        .itemInputs('create:blaze_cake')
        .duration(880)
    event.recipes.gtceu.large_boiler('charcoal_block')
        .itemInputs('gtceu:charcoal_block')
        .duration(1980)
    event.recipes.gtceu.large_boiler('coal_block')
        .itemInputs('minecraft:coal_block')
        .duration(2200)
    event.recipes.gtceu.large_boiler('coke_block')
        .itemInputs('gtceu:coke_block')
        .duration(3960)
//Liquids
    event.recipes.gtceu.large_boiler('lava')
        .inputFluids('minecraft:lava 100')
        .duration(77)
    event.recipes.gtceu.large_boiler('oil')
        .inputFluids('gtceu:oil 200')
        .duration(110)
    event.recipes.gtceu.large_boiler('sulfuric_heavy_fuel')
        .inputFluids('gtceu:sulfuric_heavy_fuel 32')
        .duration(110)
    event.recipes.gtceu.large_boiler('oil_heavy')
        .inputFluids('gtceu:oil_heavy 32')
        .duration(110)
    event.recipes.gtceu.large_boiler('biomass')
        .inputFluids('gtceu:biomass 40')
        .duration(110)
    event.recipes.gtceu.large_boiler('creosote')
        .inputFluids('gtceu:creosote 160')
        .duration(110)
    event.recipes.gtceu.large_boiler('fish_oil')
        .inputFluids('gtceu:fish_oil 160')
        .duration(110)
    event.recipes.gtceu.large_boiler('heavy_fuel')
        .inputFluids('gtceu:heavy_fuel 16')
        .duration(330)
    event.recipes.gtceu.large_boiler('blaze')
        .inputFluids('gtceu:blaze 576')
        .duration(330)
//Other removals
    event.remove({ type: 'gtceu:large_boiler' })
})