StartupEvents.registry('block', event => {
    event.create('mithril_coil_block', 'gtceu:coil')
        .temperature(12600)
        .level(16)
        .energyDiscount(16) // 
        .tier(8)
        .coilMaterial(() => GTMaterials.get('mithril'))
        .texture('gtceu:block/coils/machine_coil_mithril')
        .hardness(5)
        .requiresTool(true)
        .material('metal')
        .soundType(SoundType.NETHERITE_BLOCK)
        .tagBlock('forge:mineable/wrench')

    event.create('chadium_coil_block', 'gtceu:coil')
        .temperature(14400)
        .level(32)
        .energyDiscount(32) // 
        .tier(9)
        .coilMaterial(() => GTMaterials.get('chadium'))
        .texture('gtceu:block/coils/machine_coil_chadium')
        .hardness(5)
        .requiresTool(true)
        .material('metal')
        .soundType(SoundType.NETHERITE_BLOCK)
        .tagBlock('forge:mineable/wrench')

    event.create('awakened_draconium_coil_block', 'gtceu:coil')
        .temperature(16200)
        .level(32)
        .energyDiscount(32) // 
        .tier(9)
        .coilMaterial(() => GTMaterials.get('awakened_draconium'))
        .texture('gtceu:block/coils/machine_coil_awakened_draconium')
        .hardness(5)
        .requiresTool(true)
        .material('metal')
        .soundType(SoundType.NETHERITE_BLOCK)
        .tagBlock('forge:mineable/wrench')
})