ServerEvents.recipes(event => {
    event.recipes.gtceu.builders_press('agon')
        .circuit(0)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:agon_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('azur')
        .circuit(1)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:azur_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('bitt')
        .circuit(2)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:bitt_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('cray')
        .circuit(3)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:cray_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('fort')
        .circuit(4)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:fort_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('glaxx')
        .circuit(5)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:glaxx_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('iszm')
        .circuit(6)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:iszm_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('jelt')
        .circuit(7)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:jelt_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('korp')
        .circuit(8)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:korp_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('kryp')
        .circuit(9)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:kryp_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('lair')
        .circuit(10)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:lair_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('lave')
        .circuit(11)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:lave_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('mint')
        .circuit(12)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:mint_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('myst')
        .circuit(13)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:myst_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('reds')
        .circuit(14)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:reds_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('reed')
        .circuit(15)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:reed_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('roen')
        .circuit(16)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:roen_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('sols')
        .circuit(17)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:sols_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('sync')
        .circuit(18)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:sync_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('tank')
        .circuit(19)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:tank_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('vect')
        .circuit(20)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:vect_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('vena')
        .circuit(21)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:vena_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('zane')
        .circuit(22)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:zane_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('zech')
        .circuit(23)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:zech_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('zest')
        .circuit(24)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:zest_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('zeta')
        .circuit(25)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:zeta_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('zion')
        .circuit(26)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:zion_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('zkul')
        .notConsumable('minecraft:skeleton_skull')
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:zkul_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('zoea')
        .circuit(27)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:zoea_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('zome')
        .circuit(28)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:zome_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('zone')
        .circuit(29)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:zone_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('zorg')
        .circuit(30)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:zorg_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('ztyl')
        .circuit(31)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:ztyl_block_0')
        .EUt(60)
        .duration(400)
    event.recipes.gtceu.builders_press('zyth')
        .circuit(32)
        .inputFluids('gtceu:construction_foam 4000')
        .itemOutputs('64x xtonesreworked:zyth_block_0')
        .EUt(60)
        .duration(400)
})