ServerEvents.recipes(event => {
    //event.remove({mod: 'productivebees'})
//Centrifuge
    function honeycomb(id, input, output, base, tier, time, eu){
        event.recipes.gtceu.centrifuge(id)
            .itemInputs(input)
            .chancedOutput(output, base, tier)
            .itemOutputs('productivebees:wax')
            .outputFluids('productivebees:honey 50')
            .duration(time)
            .EUt(eu)
    }
//Centrifuge multi
    /*function honeycomb(id, input, output, base, tier, time, eu){
        event.recipes.gtceu.centrifuge(id)
            .itemInputs(input)
            .chancedOutput(output, base, tier)
            .itemOutputs('productivebees:wax')
            .outputFluids('productivebees:honey 50')
            .duration(time)
            .EUt(eu)
    }*/
//Centrifuge fluids
    function honeycombfluid(id, input, output, time, eu){
        event.recipes.gtceu.centrifuge(id)
            .itemInputs(input)
            .itemOutputs('productivebees:wax')
            .outputFluids(output)
            .duration(time)
            .EUt(eu)
    }
//honeycomb('*', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:*"}').weakNBT(), 'gtceu:raw_*', 9000, 50, 1200, 30)
//GTCEU Raw Materials
    honeycomb('aluminum', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:aluminum"}').weakNBT(), 'gtceu:raw_aluminium', 8000, 50, 1200, 30)
    honeycomb('amethyst', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:amethyst"}').weakNBT(), 'gtceu:raw_amethyst', 3000, 50, 1200, 30)
    honeycomb('apatite', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:apatite"}').weakNBT(), 'gtceu:raw_apatite', 5000, 50, 1200, 30)
    honeycomb('barite', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:barite"}').weakNBT(), 'gtceu:raw_barite', 8000, 50, 1200, 30)
    honeycomb('bastnasite', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:bastnasite"}').weakNBT(), 'gtceu:raw_bastnasite', 8000, 50, 1200, 30)
    honeycomb('bauxite', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:bauxite"}').weakNBT(), 'gtceu:raw_bauxite', 8000, 50, 1200, 30)
    honeycomb('calorite', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:calorite"}').weakNBT(), 'gtceu:raw_calorite', 3000, 50, 1200, 30)
    honeycomb('certus', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:spatial"}').weakNBT(), 'gtceu:raw_certus_quartz', 9000, 50, 1200, 30)
    honeycomb('chromite', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:chromite"}').weakNBT(), 'gtceu:raw_chromite', 8000, 50, 1200, 30)
    honeycomb('cinnabar', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:cinnabar"}').weakNBT(), 'gtceu:raw_cinnabar', 5000, 50, 1200, 30)
    honeycomb('coal', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:coal"}').weakNBT(), 'gtceu:raw_coal', 6000, 50, 1200, 30)
    honeycomb('cobalt', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:cobalt"}').weakNBT(), 'gtceu:raw_cobalt', 2000, 50, 1200, 30)
    honeycomb('cobaltite', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:cobaltite"}').weakNBT(), 'gtceu:raw_cobaltite', 8000, 50, 1200, 30)
    honeycomb('copper', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:copper"}').weakNBT(), 'minecraft:raw_copper', 4000, 50, 1200, 30)
    honeycomb('desh', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:desh"}').weakNBT(), 'gtceu:raw_desh', 3000, 50, 1200, 30)
    honeycomb('diamond', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:diamond"}').weakNBT(), 'gtceu:raw_diamond', 2000, 50, 1200, 30)
    honeycomb('emerald', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:emerald"}').weakNBT(), 'gtceu:raw_emerald', 2000, 50, 1200, 30)
    honeycomb('electrotine', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:electrotine"}').weakNBT(), 'gtceu:raw_electrotine', 8000, 50, 1200, 30)
    honeycomb('galena', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:galena"}').weakNBT(), 'gtceu:raw_galena', 8000, 50, 1200, 30)
    honeycomb('gold', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:gold"}').weakNBT(), 'minecraft:raw_gold', 4000, 50, 1200, 30)
    honeycomb('graphite', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:graphite"}').weakNBT(), 'gtceu:raw_graphite', 8000, 50, 1200, 30)
    honeycomb('green_sapphire', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:green_sapphire"}').weakNBT(), 'gtceu:raw_green_sapphire', 5000, 50, 1200, 30)
    honeycomb('ilmenite', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:ilmenite"}').weakNBT(), 'gtceu:raw_ilmenite', 8000, 50, 1200, 30)
    honeycomb('iridium', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:iridium"}').weakNBT(), 'gtceu:raw_iridium', 2000, 50, 1200, 30)
    honeycomb('iron', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:iron"}').weakNBT(), 'minecraft:raw_iron', 4000, 50, 1200, 30)
    honeycomb('lapis', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:lapis"}').weakNBT(), 'gtceu:raw_lapis', 5000, 50, 1200, 30)
    honeycomb('lead', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:lead"}').weakNBT(), 'gtceu:raw_lead', 4000, 50, 1200, 30)
    honeycomb('lepidolite', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:lepidolite"}').weakNBT(), 'gtceu:raw_lepidolite', 8000, 50, 1200, 30)
    honeycomb('malachite', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:malachite"}').weakNBT(), 'gtceu:raw_malachite', 5000, 50, 1200, 30)
    honeycomb('molybdenum', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:molybdenum"}').weakNBT(), 'gtceu:raw_molybdenum', 8000, 50, 1200, 30)
    honeycomb('naquadah', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:naquadah"}').weakNBT(), 'gtceu:raw_naquadah', 8000, 50, 1200, 30)
    honeycomb('neodymium', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:neodymium"}').weakNBT(), 'gtceu:raw_neodymium', 8000, 50, 1200, 30)
    honeycomb('nickel', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:nickel"}').weakNBT(), 'gtceu:raw_nickel', 4000, 50, 1200, 30)
    honeycomb('oilsands', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:oilsands"}').weakNBT(), 'gtceu:raw_oilsands', 8000, 50, 1200, 30)
    honeycomb('opal', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:opal"}').weakNBT(), 'gtceu:raw_opal', 5000, 50, 1200, 30)
    honeycomb('osmium', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:osmium"}').weakNBT(), 'gtceu:raw_osmium', 4000, 50, 1200, 30)
    honeycomb('ostrum', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:ostrum"}').weakNBT(), 'gtceu:raw_ostrum', 3000, 50, 1200, 30)
    honeycomb('palladium', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:palladium"}').weakNBT(), 'gtceu:raw_palladium', 8000, 50, 1200, 30)
    honeycomb('platinum', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:platinum"}').weakNBT(), 'gtceu:raw_platinum', 4000, 50, 1200, 30)
    honeycomb('pyrochlore', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:pyrochlore"}').weakNBT(), 'gtceu:raw_pyrochlore', 8000, 50, 1200, 30)
    honeycomb('pyrolusite', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:pyrolusite"}').weakNBT(), 'gtceu:raw_pyrolusite', 8000, 50, 1200, 30)
    honeycomb('pyrope', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:pyrope"}').weakNBT(), 'gtceu:raw_pyrope', 5000, 50, 1200, 30)
    honeycomb('quartz', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:crystalline"}').weakNBT(), 'minecraft:quartz', 5000, 50, 1200, 30)
    honeycomb('realgar', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:realgar"}').weakNBT(), 'gtceu:raw_realgar', 8000, 50, 1200, 30)
    honeycomb('redstone', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:redstone"}').weakNBT(), 'gtceu:raw_redstone', 5000, 50, 1200, 30)
    honeycomb('ruby', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:ruby"}').weakNBT(), 'gtceu:raw_ruby', 5000, 50, 1200, 30)
    honeycomb('sapphire', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:sapphire"}').weakNBT(), 'gtceu:raw_sapphire', 5000, 50, 1200, 30)
    honeycomb('scheelite', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:scheelite"}').weakNBT(), 'gtceu:raw_scheelite', 8000, 50, 1200, 30)
    honeycomb('sheldonite', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:sheldonite"}').weakNBT(), 'gtceu:raw_cooperite', 8000, 50, 1200, 30)
    honeycomb('silver', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:silver"}').weakNBT(), 'gtceu:raw_silver', 4000, 50, 1200, 30)
    honeycomb('stibnite', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:stibnite"}').weakNBT(), 'gtceu:raw_stibnite', 8000, 50, 1200, 30)
    honeycomb('sphalerite', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:sphalerite"}').weakNBT(), 'gtceu:raw_sphalerite', 8000, 50, 1200, 30)
    honeycomb('sodalite', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:sodalite"}').weakNBT(), 'gtceu:raw_sodalite', 5000, 50, 1200, 30)
    honeycomb('sulfur', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:sulfur"}').weakNBT(), 'gtceu:raw_sulfur', 9000, 50, 1200, 30)
    honeycomb('tantalite', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:tantalite"}').weakNBT(), 'gtceu:raw_tantalite', 8000, 50, 1200, 30)
    honeycomb('tetrahedrite', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:tetrahedrite"}').weakNBT(), 'gtceu:raw_tetrahedrite', 8000, 50, 1200, 30)
    honeycomb('tin', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:tin"}').weakNBT(), 'gtceu:raw_tin', 4000, 50, 1200, 30)
    honeycomb('titanium', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:titanium"}').weakNBT(), 'gtceu:raw_titanium', 4000, 50, 1200, 30)
    honeycomb('tricalcium_phosphate', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:tricalcium_phosphate"}').weakNBT(), 'gtceu:raw_tricalcium_phosphate', 8000, 50, 1200, 30)
    honeycomb('topaz', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:topaz"}').weakNBT(), 'gtceu:raw_topaz', 8000, 50, 1200, 30)
    honeycomb('tungstate', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:tungstate"}').weakNBT(), 'gtceu:raw_tungstate', 8000, 50, 1200, 30)
    honeycomb('tungsten', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:tungsten"}').weakNBT(), 'gtceu:raw_tungsten', 4000, 50, 1200, 30)
    honeycomb('uranium', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:radioactive"}').weakNBT(), 'gtceu:raw_uranium', 2000, 50, 1200, 30)
    honeycomb('vanadium_magnetite', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:vanadium_magnetite"}').weakNBT(), 'gtceu:raw_vanadium_magnetite', 8000, 50, 1200, 30)
    honeycomb('zinc', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:zinc"}').weakNBT(), 'create:raw_zinc', 4000, 50, 1200, 30)
//Mob drops
    honeycomb('blazing', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:blazing"}').weakNBT(), 'minecraft:blaze_powder', 3000, 50, 1200, 30)
    honeycomb('draconic', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:draconic"}').weakNBT(), 'productivebees:draconic_dust', 3000, 50, 1200, 30)
    honeycomb('ender', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:ender"}').weakNBT(), 'minecraft:ender_pearl', 2000, 50, 1200, 30)
    honeycomb('magmatic', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:magmatic"}').weakNBT(), 'minecraft:magma_cream', 2000, 50, 1200, 30)
    honeycomb('powdery', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:powdery"}').weakNBT(), 'minecraft:gunpowder', 5000, 50, 1200, 30)
    honeycomb('sculk', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:sculk"}').weakNBT(), 'minecraft:echo_shard', 3000, 50, 1200, 30)
    honeycomb('silky', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:silky"}').weakNBT(), 'minecraft:string', 5000, 50, 1200, 30)
    honeycomb('skeletal', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:skeletal"}').weakNBT(), 'minecraft:bone_meal', 7000, 50, 1200, 30)
    honeycomb('slimy', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:slimy"}').weakNBT(), 'minecraft:slime_ball', 2000, 50, 1200, 30)
    honeycomb('withered', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:withered"}').weakNBT(), 'productivebees:wither_skull_chip', 3000, 50, 1200, 30)
    honeycomb('zombie', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:zombie"}').weakNBT(), 'minecraft:rotten_flesh', 6000, 50, 1200, 30)
//Other Mats
    honeycomb('netherite', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:netherite"}').weakNBT(), 'minecraft:netherite_scrap', 1000, 50, 1200, 30)
    honeycomb('brown_shroom', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:brown_shroom"}').weakNBT(), 'minecraft:brown_mushroom', 7000, 50, 1200, 30)
    honeycomb('cheese', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:cheese"}').weakNBT(), 'ad_astra:cheese', 9000, 50, 1200, 30)
    honeycomb('crimson', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:crimson"}').weakNBT(), 'minecraft:crimson_fungus', 7000, 50, 1200, 30)
    honeycomb('glowing', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:glowing"}').weakNBT(), 'minecraft:glowstone_dust', 9000, 50, 1200, 30)
    honeycomb('obsidian', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:obsidian"}').weakNBT(), '2x gtceu:obsidian_dust', 5000, 50, 1200, 30)
    honeycomb('red_shroom', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:red_shroom"}').weakNBT(), 'minecraft:red_mushroom', 7000, 50, 1200, 30)
    honeycomb('scrapped', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:scrapped"}').weakNBT(), 'tetra:metal_scrap', 1000, 50, 1200, 30)
    honeycomb('silicon', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:silicon"}').weakNBT(), 'gtceu:silicon_dust', 5000, 50, 1200, 30)
    honeycomb('steel', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:steel"}').weakNBT(), 'gtceu:steel_dust', 8000, 50, 1200, 30)
    honeycomb('sticky_resin', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:sticky_resin"}').weakNBT(), 'gtceu:sticky_resin', 9000, 50, 1200, 30)
    honeycomb('warped', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:warped"}').weakNBT(), 'minecraft:warped_fungus', 7000, 50, 1200, 30)
//Alloys
    honeycomb('bismuth', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:bismuth"}').weakNBT(), 'gtceu:bismuth_dust', 9000, 50, 1200, 30)
    honeycomb('brass', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:brass"}').weakNBT(), 'gtceu:brass_dust', 8000, 50, 1200, 30)
    honeycomb('bronze', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:bronze"}').weakNBT(), 'gtceu:bronze_dust', 8000, 50, 1200, 30)
    honeycomb('electrum', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:electrum"}').weakNBT(), 'gtceu:electrum_dust', 8000, 50, 1200, 30)
    honeycomb('fluix', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:fluix"}').weakNBT(), 'ae2:fluix_crystal', 2000, 50, 1200, 30)
    honeycomb('invar', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:invar"}').weakNBT(), 'gtceu:invar_dust', 8000, 50, 1200, 30)
    honeycomb('rose_gold', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:rose_gold"}').weakNBT(), 'gtceu:rose_gold_dust', 8000, 50, 1200, 30)
    honeycomb('rose_quartz', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:rose_quartz"}').weakNBT(), 'gtceu:rose_quartz_gem', 5000, 50, 1200, 30)
//Multi Item Output
    //honeycomb('prismarine', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:prismarine"}').weakNBT(), 'minecraft:prismarine_shard', 9000, 50, 1200, 30)
    //honeycomb('frosty', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:frosty"}').weakNBT(), 'minecraft:ice', 9000, 50, 1200, 30)
//Fluids
    honeycombfluid('chocolate', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:chocolate"}').weakNBT(), 'create:chocolate 100', 1200, 30)
    honeycombfluid('experience', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:experience"}').weakNBT(), 'experienceobelisk:cognitium 100', 1200, 30)
    honeycombfluid('hyper_experience', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:hyper_experience"}').weakNBT(), 'create_enchantment_industry:hyper_experience 10', 1200, 30)
    honeycombfluid('tea', Item.of('productivebees:configurable_honeycomb','{type: "productivebees:tea"}').weakNBT(), 'create:tea 100', 1200, 30)
//GTCEU Raw Materials Blocks
    honeycomb('aluminum_block', Item.of('productivebees:configurable_comb','{type: "productivebees:aluminum"}').weakNBT(), '4x gtceu:raw_aluminium', 8000, 50, 1200, 30)
    honeycomb('amethyst_block', Item.of('productivebees:configurable_comb','{type: "productivebees:amethyst"}').weakNBT(), '4x gtceu:raw_amethyst', 3000, 50, 1200, 30)
    honeycomb('apatite_block', Item.of('productivebees:configurable_comb','{type: "productivebees:apatite"}').weakNBT(), '4x gtceu:raw_apatite', 5000, 50, 1200, 30)
    honeycomb('barite_block', Item.of('productivebees:configurable_comb','{type: "productivebees:barite"}').weakNBT(), '4x gtceu:raw_barite', 8000, 50, 1200, 30)
    honeycomb('bastnasite_block', Item.of('productivebees:configurable_comb','{type: "productivebees:bastnasite"}').weakNBT(), '4x gtceu:raw_bastnasite', 8000, 50, 1200, 30)
    honeycomb('bauxite_block', Item.of('productivebees:configurable_comb','{type: "productivebees:bauxite"}').weakNBT(), '4x gtceu:raw_bauxite', 8000, 50, 1200, 30)
    honeycomb('calorite_block', Item.of('productivebees:configurable_comb','{type: "productivebees:calorite"}').weakNBT(), '4x gtceu:raw_calorite', 3000, 50, 1200, 30)
    honeycomb('certus_block', Item.of('productivebees:configurable_comb','{type: "productivebees:spatial"}').weakNBT(), '4x gtceu:raw_certus_quartz', 9000, 50, 1200, 30)
    honeycomb('chromite_block', Item.of('productivebees:configurable_comb','{type: "productivebees:chromite"}').weakNBT(), '4x gtceu:raw_chromite', 8000, 50, 1200, 30)
    honeycomb('cinnabar_block', Item.of('productivebees:configurable_comb','{type: "productivebees:cinnabar"}').weakNBT(), '4x gtceu:raw_cinnabar', 5000, 50, 1200, 30)
    honeycomb('coal_block', Item.of('productivebees:configurable_comb','{type: "productivebees:coal"}').weakNBT(), '4x gtceu:raw_coal', 6000, 50, 1200, 30)
    honeycomb('cobalt_block', Item.of('productivebees:configurable_comb','{type: "productivebees:cobalt"}').weakNBT(), '4x gtceu:raw_cobalt', 2000, 50, 1200, 30)
    honeycomb('cobaltite_block', Item.of('productivebees:configurable_comb','{type: "productivebees:cobaltite"}').weakNBT(), '4x gtceu:raw_cobaltite', 8000, 50, 1200, 30)
    honeycomb('copper_block', Item.of('productivebees:configurable_comb','{type: "productivebees:copper"}').weakNBT(), '4x minecraft:raw_copper', 4000, 50, 1200, 30)
    honeycomb('desh_block', Item.of('productivebees:configurable_comb','{type: "productivebees:desh"}').weakNBT(), '4x gtceu:raw_desh', 3000, 50, 1200, 30)
    honeycomb('diamond_block', Item.of('productivebees:configurable_comb','{type: "productivebees:diamond"}').weakNBT(), '4x gtceu:raw_diamond', 2000, 50, 1200, 30)
    honeycomb('emerald_block', Item.of('productivebees:configurable_comb','{type: "productivebees:emerald"}').weakNBT(), '4x gtceu:raw_emerald', 2000, 50, 1200, 30)
    honeycomb('electrotine_block', Item.of('productivebees:configurable_comb','{type: "productivebees:electrotine"}').weakNBT(), '4x gtceu:raw_electrotine', 8000, 50, 1200, 30)
    honeycomb('galena_block', Item.of('productivebees:configurable_comb','{type: "productivebees:galena"}').weakNBT(), '4x gtceu:raw_galena', 8000, 50, 1200, 30)
    honeycomb('gold_block', Item.of('productivebees:configurable_comb','{type: "productivebees:gold"}').weakNBT(), '4x minecraft:raw_gold', 4000, 50, 1200, 30)
    honeycomb('graphite_block', Item.of('productivebees:configurable_comb','{type: "productivebees:graphite"}').weakNBT(), '4x gtceu:raw_graphite', 8000, 50, 1200, 30)
    honeycomb('green_sapphire_block', Item.of('productivebees:configurable_comb','{type: "productivebees:green_sapphire"}').weakNBT(), '4x gtceu:raw_green_sapphire', 5000, 50, 1200, 30)
    honeycomb('ilmenite_block', Item.of('productivebees:configurable_comb','{type: "productivebees:ilmenite"}').weakNBT(), '4x gtceu:raw_ilmenite', 8000, 50, 1200, 30)
    honeycomb('iridium_block', Item.of('productivebees:configurable_comb','{type: "productivebees:iridium"}').weakNBT(), '4x gtceu:raw_iridium', 2000, 50, 1200, 30)
    honeycomb('iron_block', Item.of('productivebees:configurable_comb','{type: "productivebees:iron"}').weakNBT(), '4x minecraft:raw_iron', 4000, 50, 1200, 30)
    honeycomb('lapis_block', Item.of('productivebees:configurable_comb','{type: "productivebees:lapis"}').weakNBT(), '4x gtceu:raw_lapis', 5000, 50, 1200, 30)
    honeycomb('lead_block', Item.of('productivebees:configurable_comb','{type: "productivebees:lead"}').weakNBT(), '4x gtceu:raw_lead', 4000, 50, 1200, 30)
    honeycomb('lepidolite_block', Item.of('productivebees:configurable_comb','{type: "productivebees:lepidolite"}').weakNBT(), '4x gtceu:raw_lepidolite', 8000, 50, 1200, 30)
    honeycomb('malachite_block', Item.of('productivebees:configurable_comb','{type: "productivebees:malachite"}').weakNBT(), '4x gtceu:raw_malachite', 5000, 50, 1200, 30)
    honeycomb('molybdenum_block', Item.of('productivebees:configurable_comb','{type: "productivebees:molybdenum"}').weakNBT(), '4x gtceu:raw_molybdenum', 8000, 50, 1200, 30)
    honeycomb('naquadah_block', Item.of('productivebees:configurable_comb','{type: "productivebees:naquadah"}').weakNBT(), '4x gtceu:raw_naquadah', 8000, 50, 1200, 30)
    honeycomb('neodymium_block', Item.of('productivebees:configurable_comb','{type: "productivebees:neodymium"}').weakNBT(), '4x gtceu:raw_neodymium', 8000, 50, 1200, 30)
    honeycomb('nickel_block', Item.of('productivebees:configurable_comb','{type: "productivebees:nickel"}').weakNBT(), '4x gtceu:raw_nickel', 4000, 50, 1200, 30)
    honeycomb('oilsands_block', Item.of('productivebees:configurable_comb','{type: "productivebees:oilsands"}').weakNBT(), '4x gtceu:raw_oilsands', 8000, 50, 1200, 30)
    honeycomb('opal_block', Item.of('productivebees:configurable_comb','{type: "productivebees:opal"}').weakNBT(), '4x gtceu:raw_opal', 5000, 50, 1200, 30)
    honeycomb('osmium_block', Item.of('productivebees:configurable_comb','{type: "productivebees:osmium"}').weakNBT(), '4x gtceu:raw_osmium', 4000, 50, 1200, 30)
    honeycomb('ostrum_block', Item.of('productivebees:configurable_comb','{type: "productivebees:ostrum"}').weakNBT(), '4x gtceu:raw_ostrum', 3000, 50, 1200, 30)
    honeycomb('palladium_block', Item.of('productivebees:configurable_comb','{type: "productivebees:palladium"}').weakNBT(), '4x gtceu:raw_palladium', 8000, 50, 1200, 30)
    honeycomb('platinum_block', Item.of('productivebees:configurable_comb','{type: "productivebees:platinum"}').weakNBT(), '4x gtceu:raw_platinum', 4000, 50, 1200, 30)
    honeycomb('pyrochlore_block', Item.of('productivebees:configurable_comb','{type: "productivebees:pyrochlore"}').weakNBT(), '4x gtceu:raw_pyrochlore', 8000, 50, 1200, 30)
    honeycomb('pyrolusite_block', Item.of('productivebees:configurable_comb','{type: "productivebees:pyrolusite"}').weakNBT(), '4x gtceu:raw_pyrolusite', 8000, 50, 1200, 30)
    honeycomb('pyrope_block', Item.of('productivebees:configurable_comb','{type: "productivebees:pyrope"}').weakNBT(), '4x gtceu:raw_pyrope', 5000, 50, 1200, 30)
    honeycomb('quartz_block', Item.of('productivebees:configurable_comb','{type: "productivebees:crystalline"}').weakNBT(), '4x minecraft:quartz', 5000, 50, 1200, 30)
    honeycomb('realgar_block', Item.of('productivebees:configurable_comb','{type: "productivebees:realgar"}').weakNBT(), '4x gtceu:raw_realgar', 8000, 50, 1200, 30)
    honeycomb('redstone_block', Item.of('productivebees:configurable_comb','{type: "productivebees:redstone"}').weakNBT(), '4x gtceu:raw_redstone', 5000, 50, 1200, 30)
    honeycomb('ruby_block', Item.of('productivebees:configurable_comb','{type: "productivebees:ruby"}').weakNBT(), '4x gtceu:raw_ruby', 5000, 50, 1200, 30)
    honeycomb('sapphire_block', Item.of('productivebees:configurable_comb','{type: "productivebees:sapphire"}').weakNBT(), '4x gtceu:raw_sapphire', 5000, 50, 1200, 30)
    honeycomb('scheelite_block', Item.of('productivebees:configurable_comb','{type: "productivebees:scheelite"}').weakNBT(), '4x gtceu:raw_scheelite', 8000, 50, 1200, 30)
    honeycomb('sheldonite_block', Item.of('productivebees:configurable_comb','{type: "productivebees:sheldonite"}').weakNBT(), '4x gtceu:raw_cooperite', 8000, 50, 1200, 30)
    honeycomb('silver_block', Item.of('productivebees:configurable_comb','{type: "productivebees:silver"}').weakNBT(), '4x gtceu:raw_silver', 4000, 50, 1200, 30)
    honeycomb('stibnite_block', Item.of('productivebees:configurable_comb','{type: "productivebees:stibnite"}').weakNBT(), '4x gtceu:raw_stibnite', 8000, 50, 1200, 30)
    honeycomb('sphalerite_block', Item.of('productivebees:configurable_comb','{type: "productivebees:sphalerite"}').weakNBT(), '4x gtceu:raw_sphalerite', 8000, 50, 1200, 30)
    honeycomb('sodalite_block', Item.of('productivebees:configurable_comb','{type: "productivebees:sodalite"}').weakNBT(), '4x gtceu:raw_sodalite', 5000, 50, 1200, 30)
    honeycomb('sulfur_block', Item.of('productivebees:configurable_comb','{type: "productivebees:sulfur"}').weakNBT(), '4x gtceu:raw_sulfur', 9000, 50, 1200, 30)
    honeycomb('tantalite_block', Item.of('productivebees:configurable_comb','{type: "productivebees:tantalite"}').weakNBT(), '4x gtceu:raw_tantalite', 8000, 50, 1200, 30)
    honeycomb('tetrahedrite_block', Item.of('productivebees:configurable_comb','{type: "productivebees:tetrahedrite"}').weakNBT(), '4x gtceu:raw_tetrahedrite', 8000, 50, 1200, 30)
    honeycomb('tin_block', Item.of('productivebees:configurable_comb','{type: "productivebees:tin"}').weakNBT(), '4x gtceu:raw_tin', 4000, 50, 1200, 30)
    honeycomb('titanium_block', Item.of('productivebees:configurable_comb','{type: "productivebees:titanium"}').weakNBT(), '4x gtceu:raw_titanium', 4000, 50, 1200, 30)
    honeycomb('tricalcium_phosphate_block', Item.of('productivebees:configurable_comb','{type: "productivebees:tricalcium_phosphate"}').weakNBT(), '4x gtceu:raw_tricalcium_phosphate', 8000, 50, 1200, 30)
    honeycomb('topaz_block', Item.of('productivebees:configurable_comb','{type: "productivebees:topaz"}').weakNBT(), '4x gtceu:raw_topaz', 8000, 50, 1200, 30)
    honeycomb('tungstate_block', Item.of('productivebees:configurable_comb','{type: "productivebees:tungstate"}').weakNBT(), '4x gtceu:raw_tungstate', 8000, 50, 1200, 30)
    honeycomb('tungsten_block', Item.of('productivebees:configurable_comb','{type: "productivebees:tungsten"}').weakNBT(), '4x gtceu:raw_tungsten', 4000, 50, 1200, 30)
    honeycomb('uranium_block', Item.of('productivebees:configurable_comb','{type: "productivebees:radioactive"}').weakNBT(), '4x gtceu:raw_uranium', 2000, 50, 1200, 30)
    honeycomb('vanadium_magnetite_block', Item.of('productivebees:configurable_comb','{type: "productivebees:vanadium_magnetite"}').weakNBT(), '4x gtceu:raw_vanadium_magnetite', 8000, 50, 1200, 30)
    honeycomb('zinc_block', Item.of('productivebees:configurable_comb','{type: "productivebees:zinc"}').weakNBT(), '4x create:raw_zinc', 4000, 50, 1200, 30)
//Mob drops Blocks
    honeycomb('blazing_block', Item.of('productivebees:configurable_comb','{type: "productivebees:blazing"}').weakNBT(), '4x minecraft:blaze_powder', 3000, 50, 1200, 30)
    honeycomb('draconic_block', Item.of('productivebees:configurable_comb','{type: "productivebees:draconic"}').weakNBT(), '4x productivebees:draconic_dust', 3000, 50, 1200, 30)
    honeycomb('ender_block', Item.of('productivebees:configurable_comb','{type: "productivebees:ender"}').weakNBT(), '4x minecraft:ender_pearl', 2000, 50, 1200, 30)
    honeycomb('magmatic_block', Item.of('productivebees:configurable_comb','{type: "productivebees:magmatic"}').weakNBT(), '4x minecraft:magma_cream', 2000, 50, 1200, 30)
    honeycomb('powdery_block', Item.of('productivebees:configurable_comb','{type: "productivebees:powdery"}').weakNBT(), '4x minecraft:gunpowder', 5000, 50, 1200, 30)
    honeycomb('sculk_block', Item.of('productivebees:configurable_comb','{type: "productivebees:sculk"}').weakNBT(), '4x minecraft:echo_shard', 3000, 50, 1200, 30)
    honeycomb('silky_block', Item.of('productivebees:configurable_comb','{type: "productivebees:silky"}').weakNBT(), '4x minecraft:string', 5000, 50, 1200, 30)
    honeycomb('skeletal_block', Item.of('productivebees:configurable_comb','{type: "productivebees:skeletal"}').weakNBT(), '4x minecraft:bone_meal', 7000, 50, 1200, 30)
    honeycomb('slimy_block', Item.of('productivebees:configurable_comb','{type: "productivebees:slimy"}').weakNBT(), '4x minecraft:slime_ball', 2000, 50, 1200, 30)
    honeycomb('withered_block', Item.of('productivebees:configurable_comb','{type: "productivebees:withered"}').weakNBT(), '4x productivebees:wither_skull_chip', 3000, 50, 1200, 30)
    honeycomb('zombie_block', Item.of('productivebees:configurable_comb','{type: "productivebees:zombie"}').weakNBT(), '4x minecraft:rotten_flesh', 6000, 50, 1200, 30)
//Other Mats Blocks
    honeycomb('netherite_block', Item.of('productivebees:configurable_comb','{type: "productivebees:netherite"}').weakNBT(), '4x minecraft:netherite_scrap', 1000, 50, 1200, 30)
    honeycomb('brown_shroom_block', Item.of('productivebees:configurable_comb','{type: "productivebees:brown_shroom"}').weakNBT(), '4x minecraft:brown_mushroom', 7000, 50, 1200, 30)
    honeycomb('cheese_block', Item.of('productivebees:configurable_comb','{type: "productivebees:cheese"}').weakNBT(), '4x ad_astra:cheese', 9000, 50, 1200, 30)
    honeycomb('crimson_block', Item.of('productivebees:configurable_comb','{type: "productivebees:crimson"}').weakNBT(), '4x minecraft:crimson_fungus', 7000, 50, 1200, 30)
    honeycomb('glowing_block', Item.of('productivebees:configurable_comb','{type: "productivebees:glowing"}').weakNBT(), '4x minecraft:glowstone_dust', 9000, 50, 1200, 30)
    honeycomb('obsidian_block', Item.of('productivebees:configurable_comb','{type: "productivebees:obsidian"}').weakNBT(), '8x gtceu:obsidian_dust', 5000, 50, 1200, 30)
    honeycomb('red_shroom_block', Item.of('productivebees:configurable_comb','{type: "productivebees:red_shroom"}').weakNBT(), '4x minecraft:red_mushroom', 7000, 50, 1200, 30)
    honeycomb('scrapped_block', Item.of('productivebees:configurable_comb','{type: "productivebees:scrapped"}').weakNBT(), '4x tetra:metal_scrap', 1000, 50, 1200, 30)
    honeycomb('silicon_block', Item.of('productivebees:configurable_comb','{type: "productivebees:silicon"}').weakNBT(), '4x gtceu:silicon_dust', 5000, 50, 1200, 30)
    honeycomb('steel_block', Item.of('productivebees:configurable_comb','{type: "productivebees:steel"}').weakNBT(), '4x gtceu:steel_dust', 8000, 50, 1200, 30)
    honeycomb('sticky_resin_block', Item.of('productivebees:configurable_comb','{type: "productivebees:sticky_resin"}').weakNBT(), '4x gtceu:sticky_resin', 9000, 50, 1200, 30)
    honeycomb('warped_block', Item.of('productivebees:configurable_comb','{type: "productivebees:warped"}').weakNBT(), '4x minecraft:warped_fungus', 7000, 50, 1200, 30)
//Alloys Blocks
    honeycomb('bismuth_block', Item.of('productivebees:configurable_comb','{type: "productivebees:bismuth"}').weakNBT(), '4x gtceu:bismuth_dust', 9000, 50, 1200, 30)
    honeycomb('brass_block', Item.of('productivebees:configurable_comb','{type: "productivebees:brass"}').weakNBT(), '4x gtceu:brass_dust', 8000, 50, 1200, 30)
    honeycomb('bronze_block', Item.of('productivebees:configurable_comb','{type: "productivebees:bronze"}').weakNBT(), '4x gtceu:bronze_dust', 8000, 50, 1200, 30)
    honeycomb('electrum_block', Item.of('productivebees:configurable_comb','{type: "productivebees:electrum"}').weakNBT(), '4x gtceu:electrum_dust', 8000, 50, 1200, 30)
    honeycomb('fluix_block', Item.of('productivebees:configurable_comb','{type: "productivebees:fluix"}').weakNBT(), '4x ae2:fluix_crystal', 2000, 50, 1200, 30)
    honeycomb('invar_block', Item.of('productivebees:configurable_comb','{type: "productivebees:invar"}').weakNBT(), '4x gtceu:invar_dust', 8000, 50, 1200, 30)
    honeycomb('rose_gold_block', Item.of('productivebees:configurable_comb','{type: "productivebees:rose_gold"}').weakNBT(), '4x gtceu:rose_gold_dust', 8000, 50, 1200, 30)
    honeycomb('rose_quartz_block', Item.of('productivebees:configurable_comb','{type: "productivebees:rose_quartz"}').weakNBT(), '4x gtceu:rose_quartz_gem', 5000, 50, 1200, 30)
//Multi Item Output Blocks
    //honeycomb('prismarine_block', Item.of('productivebees:configurable_comb','{type: "productivebees:prismarine"}').weakNBT(), '4x minecraft:prismarine_shard', 9000, 50, 1200, 30)
    //honeycomb('frosty_block', Item.of('productivebees:configurable_comb','{type: "productivebees:frosty"}').weakNBT(), '4x minecraft:ice', 9000, 50, 1200, 30)
//Fluids Blocks
    honeycombfluid('chocolate_block', Item.of('productivebees:configurable_comb','{type: "productivebees:chocolate"}').weakNBT(), 'create:chocolate 400', 1200, 30)
    honeycombfluid('experience_block', Item.of('productivebees:configurable_comb','{type: "productivebees:experience"}').weakNBT(), 'experienceobelisk:cognitium 400', 1200, 30)
    honeycombfluid('hyper_experience_block', Item.of('productivebees:configurable_comb','{type: "productivebees:hyper_experience"}').weakNBT(), 'create_enchantment_industry:hyper_experience 40', 1200, 30)
    honeycombfluid('tea_block', Item.of('productivebees:configurable_comb','{type: "productivebees:tea"}').weakNBT(), 'create:tea 400', 1200, 30)
})