ServerEvents.recipes(event => {
//Certus Wafers
    event.recipes.gtceu.cutter('water_certus_wafer')
        .itemInputs('kubejs:certus_quartz_boule')
        .inputFluids('minecraft:water 1000')
        .itemOutputs('32x kubejs:certus_wafer')
        .duration(1480)
        .EUt(480)
    event.recipes.gtceu.cutter('dist_water_certus_wafer')
        .itemInputs('kubejs:certus_quartz_boule')
        .inputFluids('gtceu:distilled_water 750')
        .itemOutputs('32x kubejs:certus_wafer')
        .duration(1200)
        .EUt(480)
    event.recipes.gtceu.cutter('lube_certus_wafer')
        .itemInputs('kubejs:certus_quartz_boule')
        .inputFluids('gtceu:lubricant 250')
        .itemOutputs('32x kubejs:certus_wafer')
        .duration(800)
        .EUt(480)
    
    event.recipes.gtceu.electric_blast_furnace('certus_quartz_boule')
        .itemInputs('64x gtceu:silicon_dust', '8x gtceu:certus_quartz_dust', '4x gtceu:gallium_arsenide_dust')
        .inputFluids('gtceu:nitrogen 8000')
        .itemOutputs('kubejs:certus_quartz_boule')
        .blastFurnaceTemp(2484)
        .duration(12000)
        .EUt(480)

    event.recipes.gtceu.chemical_reactor('ae2_silicon')
        .itemInputs('6x gtceu:electrum_foil', 'gtceu:silicon_plate')
        .inputFluids('gtceu:iron_iii_chloride 500')
        .itemOutputs('ae2:printed_silicon')
        .cleanroom(CleanroomType.CLEANROOM)
        .duration(900)
        .EUt(120)

//Calculation
    event.recipes.gtceu.laser_engraver('ae2_calculation')
        .itemInputs('kubejs:certus_wafer')
        .notConsumable('#forge:lenses/light_blue')
        .itemOutputs('kubejs:calculation_wafer')
        .cleanroom(CleanroomType.CLEANROOM)
        .duration(900)
        .EUt(480)

    event.recipes.gtceu.cutter('water_calculation')
        .itemInputs('kubejs:calculation_wafer')
        .inputFluids('minecraft:water 1000')
        .itemOutputs('4x ae2:printed_calculation_processor')
        .duration(1800)
        .EUt(480)

    event.recipes.gtceu.cutter('dist_water_calculation')
        .itemInputs('kubejs:calculation_wafer')
        .inputFluids('gtceu:distilled_water 750')
        .itemOutputs('4x ae2:printed_calculation_processor')
        .duration(1350)
        .EUt(480)

    event.recipes.gtceu.cutter('lube_calculation')
        .itemInputs('kubejs:calculation_wafer')
        .inputFluids('gtceu:lubricant 250')
        .itemOutputs('4x ae2:printed_calculation_processor')
        .duration(900)
        .EUt(480)

//Engineering
    event.recipes.gtceu.laser_engraver('ae2_engineering')
        .itemInputs('kubejs:certus_wafer')
        .notConsumable('#forge:lenses/blue')
        .itemOutputs('kubejs:engineering_wafer')
        .cleanroom(CleanroomType.CLEANROOM)
        .duration(900)
        .EUt(480)

    event.recipes.gtceu.cutter('water_engineering')
        .itemInputs('kubejs:engineering_wafer')
        .inputFluids('minecraft:water 1000')
        .itemOutputs('4x ae2:printed_engineering_processor')
        .duration(1800)
        .EUt(480)

    event.recipes.gtceu.cutter('dist_water_engineering')
        .itemInputs('kubejs:engineering_wafer')
        .inputFluids('gtceu:distilled_water 750')
        .itemOutputs('4x ae2:printed_engineering_processor')
        .duration(1350)
        .EUt(480)

    event.recipes.gtceu.cutter('lube_engineering')
        .itemInputs('kubejs:engineering_wafer')
        .inputFluids('gtceu:lubricant 250')
        .itemOutputs('4x ae2:printed_engineering_processor')
        .duration(900)
        .EUt(480)

//Logic
    event.recipes.gtceu.laser_engraver('ae2_logic')
        .itemInputs('kubejs:certus_wafer')
        .notConsumable('#forge:lenses/yellow')
        .itemOutputs('kubejs:logic_wafer')
        .cleanroom(CleanroomType.CLEANROOM)
        .duration(900)
        .EUt(480)

    event.recipes.gtceu.cutter('water_logic')
        .itemInputs('kubejs:logic_wafer')
        .inputFluids('minecraft:water 1000')
        .itemOutputs('4x ae2:printed_logic_processor')
        .duration(1800)
        .EUt(480)

    event.recipes.gtceu.cutter('dist_water_logic')
        .itemInputs('kubejs:logic_wafer')
        .inputFluids('gtceu:distilled_water 750')
        .itemOutputs('4x ae2:printed_logic_processor')
        .duration(1350)
        .EUt(480)

    event.recipes.gtceu.cutter('lube_logic')
        .itemInputs('kubejs:logic_wafer')
        .inputFluids('gtceu:lubricant 250')
        .itemOutputs('4x ae2:printed_logic_processor')
        .duration(900)
        .EUt(480)

//Processors
    event.recipes.gtceu.circuit_assembler('ae2_cal_solder')
        .itemInputs('ae2:printed_silicon', '#gtceu:circuits/hv', '4x ae2:printed_calculation_processor', '8x gtceu:fine_electrum_wire')
        .inputFluids('gtceu:soldering_alloy 144')
        .itemOutputs('ae2:calculation_processor')
        .cleanroom(CleanroomType.CLEANROOM)
        .duration(400)
        .EUt(480)

    event.recipes.gtceu.circuit_assembler('ae2_cal_tin')
        .itemInputs('ae2:printed_silicon', '#gtceu:circuits/hv', '4x ae2:printed_calculation_processor', '8x gtceu:fine_electrum_wire')
        .inputFluids('gtceu:tin 288')
        .itemOutputs('ae2:calculation_processor')
        .cleanroom(CleanroomType.CLEANROOM)
        .duration(400)
        .EUt(480)

    event.recipes.gtceu.circuit_assembler('ae2_eng_solder')
        .itemInputs('ae2:printed_silicon', '#gtceu:circuits/hv', '4x ae2:printed_engineering_processor', '8x gtceu:fine_electrum_wire')
        .inputFluids('gtceu:soldering_alloy 144')
        .itemOutputs('ae2:engineering_processor')
        .cleanroom(CleanroomType.CLEANROOM)
        .duration(400)
        .EUt(480)

    event.recipes.gtceu.circuit_assembler('ae2_eng_tin')
        .itemInputs('ae2:printed_silicon', '#gtceu:circuits/hv', '4x ae2:printed_engineering_processor', '8x gtceu:fine_electrum_wire')
        .inputFluids('gtceu:tin 288')
        .itemOutputs('ae2:engineering_processor')
        .cleanroom(CleanroomType.CLEANROOM)
        .duration(400)
        .EUt(480)

    event.recipes.gtceu.circuit_assembler('ae2_log_solder')
        .itemInputs('ae2:printed_silicon', '#gtceu:circuits/hv', '4x ae2:printed_logic_processor', '8x gtceu:fine_electrum_wire')
        .inputFluids('gtceu:soldering_alloy 144')
        .itemOutputs('ae2:logic_processor')
        .cleanroom(CleanroomType.CLEANROOM)
        .duration(400)
        .EUt(480)

    event.recipes.gtceu.circuit_assembler('ae2_log_tin')
        .itemInputs('ae2:printed_silicon', '#gtceu:circuits/hv', '4x ae2:printed_logic_processor', '8x gtceu:fine_electrum_wire')
        .inputFluids('gtceu:tin 288')
        .itemOutputs('ae2:logic_processor')
        .cleanroom(CleanroomType.CLEANROOM)
        .duration(400)
        .EUt(480)

//Certus Enrichment
    event.recipes.gtceu.chemical_reactor('certus_enrich')
        .itemInputs('4x gtceu:certus_quartz_gem', 'gtceu:carbon_dust')
        .inputFluids('gtceu:redstone 576')
        .itemOutputs('gtceu:enriched_certus_dust')
        .chancedOutput('gtceu:enriched_certus_dust', 5000, 500)
        .chancedOutput('gtceu:enriched_certus_dust', 500, 50)
        .duration(400)
        .EUt(120)

    event.recipes.gtceu.autoclave('certus_enrich_2')
        .itemInputs('gtceu:enriched_certus_dust')
        .inputFluids('gtceu:polyethylene 36')
        .chancedOutput('gtceu:enriched_certus_gem', 8000, 50)
        .duration(400)
        .EUt(120)

//Fluix
    event.recipes.gtceu.chemical_reactor('fluix_gem')
        .itemInputs('gtceu:enriched_certus_gem', 'minecraft:quartz')
        .inputFluids('gtceu:redstone 144')
        .itemOutputs('2x ae2:fluix_crystal')
        .duration(400)
        .EUt(120)
})