ServerEvents.recipes(event => {
    event.remove({mod: 'create', output: 'create:propeller'})
    event.remove({mod: 'create', output: 'create:whisk'})
    event.remove({mod: 'create', output: 'create:copper_casing'})
    event.remove({mod: 'create', output: 'create:brass_casing'})
    event.remove({mod: 'create', output: 'create:andesite_casing'})
    event.remove({mod: 'create', output: 'create:shaft'})
    event.remove({mod: 'create', output: 'create:belt_connector'})
    event.remove({mod: 'create', output: 'create:large_cogwheel'})
    event.remove({mod: 'create', output: 'create:cogwheel'})
    event.remove({mod: 'create', output: 'create:windmill_bearing'})
    event.remove({mod: 'create', output: 'create:basin'})
    event.remove({mod: 'create', output: 'create:encased_fan'})
    event.remove({mod: 'create', output: 'create:water_wheel'})
    event.remove({mod: 'create', output: 'create:large_water_wheel'})
    event.remove({mod: 'create', output: 'create:mechanical_press'})
    event.remove({mod: 'create', output: 'create:fluid_tank'})
    event.remove({mod: 'create', output: 'create:rose_quartz'})
    event.remove({mod: 'create', output: 'precision_mechanism'})
    event.remove({mod: 'create', output: 'brass_ingot'})
    event.remove({mod: 'create', output: 'obsidian_plate'})
    event.remove({mod: 'create', output: 'mechanical_crafter'})
    event.remove({mod: 'create', output:'#minecraft:planks'})
    event.remove({mod: 'createcasing', output: 'createcasing:industrial_press'})
    event.remove({mod: 'createcasing', output: 'createcasing:brass_press'})
    event.remove({mod: 'createcasing', output: 'createcasing:copper_press'})
    event.remove({mod: 'createcasing', output: 'createcasing:railway_press'})
    event.remove({mod: 'createcasing', output: 'createcasing:creative_press'})
    event.remove({mod: 'create', output: 'create:mechanical_mixer'})
    event.remove({mod: 'createcasing', output: 'createcasing:industrial_iron_mixer'})
    event.remove({mod: 'createcasing', output: 'createcasing:brass_mixer'})
    event.remove({mod: 'createcasing', output: 'createcasing:copper_mixer'})
    event.remove({mod: 'createcasing', output: 'createcasing:railway_mixer'})
    event.remove({mod: 'createcasing', output: 'createcasing:creative_mixer'})
    event.remove({mod: 'create_new_age', output: 'create_new_age:generator_coil'})
    event.remove({mod: 'tfmg', output: 'tfmg:cast_iron_ingot'})
    event.remove({mod: 'createdeco', output: 'createdeco:industrial_iron_ingot'})
    event.remove({mod: 'create', output: 'create:andesite_alloy'})
    event.remove({mod: 'tfmg', output: 'tfmg:screw'})
    event.remove({mod: 'tfmg', output: 'tfmg:screwdriver'})
    event.remove({mod: 'tfmg', output: 'tfmg:coke_oven'})
    event.remove({mod: 'tfmg', output: 'tfmg:molten_steel'})
    event.remove({mod: 'tfmg', output: 'tfmg:slag'})
    event.remove({mod: 'tfmg', output: 'tfmg:industrial_pipe'})
    event.remove({mod: 'tfmg', output: 'tfmg:steel_frame'})
    event.remove({mod: 'tfmg', output: 'tfmg:steel_truss'})
    event.remove({mod: 'tfmg', output: 'tfmg:heavy_machine_casing'})
    event.remove({mod: 'tfmg', output: 'tfmg:pumpjack_hammer_head'})
    event.remove({mod: 'tfmg', output: 'tfmg:pumpjack_hammer_part'})
    event.remove({mod: 'tfmg', output: 'tfmg:pumpjack_hammer_connector'})
    event.remove({mod: 'tfmg', output: 'tfmg:pumpjack_crank'})
    event.remove({mod: 'tfmg', output: 'tfmg:pumpjack_base'})
    event.remove({mod: 'tfmg', output: 'tfmg:pumpjack_hammer'})
    event.remove({mod: 'tfmg', output: 'tfmg:machine_input'})
    event.remove({mod: 'ironchests', output:'ironchests:iron_chest'})
    event.remove({mod: 'gtceu', output:'gtceu:iv_processing_array'})
    event.remove({mod: 'gtceu', output:'gtceu:luv_processing_array'})
    event.remove({output: 'gtceu:wrought_iron_nugget', type: 'minecraft:smelting'})
    event.remove({output: 'gtceu:steel_ingot', type: 'minecraft:blasting'})
    event.remove({output: 'gtceu:steel_ingot', type: 'minecraft:shaped'})
    event.remove({output: 'gtceu:steel_ingot', type: 'minecraft:shapless'})
    event.remove({output: 'ad_astra:steel_ingot' })
    event.remove({id: 'gtceu:shaped/compressed_coke_clay'})
    event.remove({id: 'gtceu:shapeless/compressed_clay'})
    event.remove({id: 'gtceu:shapeless/dust_bronze'})
    event.remove({id: 'gtceu:shapeless/dust_brass'})
    event.remove({id: 'tfmg:casting_steel'})
    event.remove({id:'ironchests:blank_chest_upgrade'})
    event.remove({id:'ironchests:copper_chest_upgrade'})
    event.remove({id:'ironchests:iron_chest_upgrade'})
    event.remove({id:'ironchests:gold_chest_upgrade'})
    event.remove({id:'ironchests:diamond_chest_upgrade'})
    event.remove({id:'ironchests:crystal_chest_upgrade'})
    event.remove({id:'ironchests:obsidian_chest_upgrade'})
    event.remove({id:'ironchests:copper_barrel'})
    event.remove({id:'ironchests:iron_barrel'})
    event.remove({id:'ironchests:gold_barrel'})
    event.remove({id:'ironchests:diamond_barrel'})
    event.remove({id:'ironchests:crystal_barrel'})
    event.remove({id:'ironchests:obsidian_barrel'})
    event.remove({id:'ironchests:copper_chest'})
    event.remove({id:'ironchests:iron_chest'})
    event.remove({id:'ironchests:gold_chest'})
    event.remove({id:'ironchests:diamond_chest'})
    event.remove({id:'ironchests:crystal_chest'})
    event.remove({id:'ironchests:obsidian_chest'})
    event.remove({id:'ironchests:iron_dolly'})
    event.remove({id:'ironchests:diamond_dolly'})
    event.remove({type: 'create:pressing'})
})