ServerEvents.recipes(event => {
    event.remove({mod: 'ae2', output: 'ae2:inscriber'})
    event.remove({mod: 'expatternprovider', output: 'expatternprovider:ex_inscriber'})
    event.remove({mod: 'create', output: 'create:propeller'})
    event.remove({mod: 'create', output: 'create:whisk'})
    event.remove({mod: 'create', output: 'create:copper_casing'})
    event.remove({mod: 'create', output: 'create:brass_casing'})
    event.remove({mod: 'create', output: 'create:andesite_casing'})
    event.remove({mod: 'create', output: 'create:shaft'})
    event.remove({mod: 'create', output: 'create:belt_connector'})
    event.remove({mod: 'create', output: 'create:large_cogwheel'})
    event.remove({mod: 'create', output: 'create:cogwheel'})
    event.remove({mod: 'create', output: 'create:windmill_bearing'})
    event.remove({mod: 'create', output: 'create:basin'})
    event.remove({mod: 'create', output: 'create:encased_fan'})
    event.remove({mod: 'create', output: 'create:water_wheel'})
    event.remove({mod: 'create', output: 'create:large_water_wheel'})
    event.remove({mod: 'create', output: 'create:mechanical_press'})
    event.remove({mod: 'create', output: 'create:fluid_tank'})
    event.remove({mod: 'create', output: 'create:rose_quartz'})
    event.remove({mod: 'create', output: 'precision_mechanism'})
    event.remove({mod: 'create', output: 'brass_ingot'})
    event.remove({mod: 'create', output: 'obsidian_plate'})
    event.remove({mod: 'create', output: 'mechanical_crafter'})
    event.remove({mod: 'create', output:'#minecraft:planks'})
    event.remove({mod: 'create', output:'create:goggles'})
    event.remove({mod: 'create', output: 'create:mechanical_pump'})
    event.remove({mod: 'create', output: 'create:mechanical_saw'})
    event.remove({mod: 'create', output: 'create:deployer'})
    event.remove({mod: 'createcasing', output: 'createcasing:industrial_press'})
    event.remove({mod: 'createcasing', output: 'createcasing:brass_press'})
    event.remove({mod: 'createcasing', output: 'createcasing:copper_press'})
    event.remove({mod: 'createcasing', output: 'createcasing:railway_press'})
    event.remove({mod: 'createcasing', output: 'createcasing:creative_press'})
    event.remove({mod: 'create', output: 'create:mechanical_mixer'})
    event.remove({mod: 'createcasing', output: 'createcasing:industrial_iron_mixer'})
    event.remove({mod: 'createcasing', output: 'createcasing:brass_mixer'})
    event.remove({mod: 'createcasing', output: 'createcasing:copper_mixer'})
    event.remove({mod: 'createcasing', output: 'createcasing:railway_mixer'})
    event.remove({mod: 'createcasing', output: 'createcasing:creative_mixer'})
    event.remove({mod: 'create_new_age', output: 'create_new_age:generator_coil'})
    event.remove({mod: 'tfmg', output: 'tfmg:cast_iron_ingot'})
    event.remove({mod: 'createdeco', output: 'createdeco:industrial_iron_ingot'})
    event.remove({mod: 'create', output: 'create:andesite_alloy'})
    event.remove({mod: 'tfmg', output: 'tfmg:screw'})
    event.remove({mod: 'tfmg', output: 'tfmg:screwdriver'})
    event.remove({mod: 'tfmg', output: 'tfmg:coke_oven'})
    event.remove({mod: 'tfmg', output: 'tfmg:molten_steel'})
    event.remove({mod: 'tfmg', output: 'tfmg:slag'})
    event.remove({mod: 'tfmg', output: 'tfmg:industrial_pipe'})
    event.remove({mod: 'tfmg', output: 'tfmg:steel_frame'})
    event.remove({mod: 'tfmg', output: 'tfmg:steel_truss'})
    event.remove({mod: 'tfmg', output: 'tfmg:heavy_machine_casing'})
    event.remove({mod: 'tfmg', output: 'tfmg:pumpjack_hammer_head'})
    event.remove({mod: 'tfmg', output: 'tfmg:pumpjack_hammer_part'})
    event.remove({mod: 'tfmg', output: 'tfmg:pumpjack_hammer_connector'})
    event.remove({mod: 'tfmg', output: 'tfmg:pumpjack_crank'})
    event.remove({mod: 'tfmg', output: 'tfmg:pumpjack_base'})
    event.remove({mod: 'tfmg', output: 'tfmg:pumpjack_hammer'})
    event.remove({mod: 'tfmg', output: 'tfmg:machine_input'})
    event.remove({mod: 'ironchests', output:'ironchests:iron_chest'})
    event.remove({mod: 'gtceu', output:'gtceu:iv_processing_array'})
    event.remove({mod: 'gtceu', output:'gtceu:luv_processing_array'})
    event.remove({mod: 'gtceu', output:'ae2:printed_silicon'})
    event.remove({mod: 'gtceu', output:'ae2:printed_calculation_processor'})
    event.remove({mod: 'gtceu', output:'ae2:printed_engineering_processor'})
    event.remove({mod: 'gtceu', output:'ae2:printed_logic_processor'})
    event.remove({mod: 'gtceu', output:'ae2:calculation_processor'})//
    event.remove({mod: 'gtceu', output:'ae2:engineering_processor'})//
    event.remove({mod: 'gtceu', output:'ae2:logic_processor'})//
    event.remove({output: 'gtceu:wrought_iron_nugget', type: 'minecraft:smelting'})
    event.remove({output: 'minecraft:iron_nugget', type: 'minecraft:smelting'})
    event.remove({output: 'minecraft:iron_nugget', type: 'minecraft:blasting'})
    event.remove({output: 'minecraft:gold_nugget', type: 'minecraft:smelting'})
    event.remove({output: 'minecraft:gold_nugget', type: 'minecraft:blasting'})
    event.remove({output: 'minecraft:charcoal', type: 'minecraft:smelting'})
    event.remove({output: 'gtceu:steel_ingot', type: 'minecraft:blasting'})
    event.remove({output: 'gtceu:steel_ingot', type: 'minecraft:shaped'})
    event.remove({output: 'gtceu:steel_ingot', type: 'minecraft:shapless'})
    event.remove({output: 'ad_astra:steel_ingot' })
    event.remove({id:'gtceu:shaped/compressed_coke_clay'})
    event.remove({id:'gtceu:shapeless/compressed_clay'})
    event.remove({id:'gtceu:shapeless/dust_bronze'})
    event.remove({id:'gtceu:shapeless/dust_brass'})
    event.remove({id:'gtceu:mixer/mixer/ae2/transform/fluix_crystal'})
    event.remove({id:'gtceu:create_mixer/mixer/ae2/transform/fluix_crystal'})
    event.remove({id:'gtceu:fluid_solidifier/fluid_solidfication/ae2/charged_certus_quartz_crystal'})
    event.remove({id:'gtceu:forming_press/forming_press/ae2/calculation_processor_press'})
    event.remove({id:'gtceu:forming_press/forming_press/ae2/engineering_processor_press'})
    event.remove({id:'gtceu:forming_press/forming_press/ae2/logic_processor_press'})
    event.remove({id:'tfmg:casting_steel'})
    event.remove({id:'ironchests:blank_chest_upgrade'})
    event.remove({id:'ironchests:copper_chest_upgrade'})
    event.remove({id:'ironchests:iron_chest_upgrade'})
    event.remove({id:'ironchests:gold_chest_upgrade'})
    event.remove({id:'ironchests:diamond_chest_upgrade'})
    event.remove({id:'ironchests:crystal_chest_upgrade'})
    event.remove({id:'ironchests:obsidian_chest_upgrade'})
    event.remove({id:'ironchests:copper_barrel'})
    event.remove({id:'ironchests:iron_barrel'})
    event.remove({id:'ironchests:gold_barrel'})
    event.remove({id:'ironchests:diamond_barrel'})
    event.remove({id:'ironchests:crystal_barrel'})
    event.remove({id:'ironchests:obsidian_barrel'})
    event.remove({id:'ironchests:copper_chest'})
    event.remove({id:'ironchests:iron_chest'})
    event.remove({id:'ironchests:gold_chest'})
    event.remove({id:'ironchests:diamond_chest'})
    event.remove({id:'ironchests:crystal_chest'})
    event.remove({id:'ironchests:obsidian_chest'})
    event.remove({id:'ironchests:iron_dolly'})
    event.remove({id:'ironchests:diamond_dolly'})
    event.remove({id:'create:compat/ae2/mixing/fluix_crystal'})
    event.remove({id:'dawnoftimebuilder:mulberry_paper'})
    event.remove({id:'farmersdelight:paper_from_tree_bark'})
    event.remove({id:'pamhc2crops:paper_x2_paper_plants'})
    event.remove({id:'create:crafting/kinetics/fluid_pipe_vertical'})
    event.remove({id:'create:crafting/kinetics/mechanical_crafter'})
    event.remove({id:'create:crafting/kinetics/item_drain'})
    event.remove({id:'create:crafting/kinetics/spout'})
    event.remove({id:'create:crafting/logistics/andesite_funnel'})
    event.remove({id:'create:crafting/logistics/andesite_tunnel'})
    event.remove({id:'create:crafting/logistics/brass_funnel'})
    event.remove({id:'create:crafting/logistics/brass_tunnel'})
    event.remove({id:'create:crafting/kinetics/chute'})
    event.remove({id:'create:crafting/kinetics/smart_chute'})
    event.remove({id:'createlowheated:charcoal_burner'})
    event.remove({id:'create:crafting/kinetics/steam_engine'})
    event.remove({id:'pamhc2foodextended:charcoal_coconut_x1'})
    event.remove({type: 'create:pressing'})
})