ServerEvents.recipes(event => {
//Wood planks
    event.recipes.gtceu.cutter('water_oak')
        .itemInputs('#minecraft:oak_logs')
        .inputFluids('minecraft:water 5')
        .itemOutputs('4x minecraft:oak_planks', '2x gtceu:wood_dust')
        .duration(400)
        .EUt(7)
    event.recipes.gtceu.cutter('dist_water_oak')
        .itemInputs('#minecraft:oak_logs')
        .inputFluids('gtceu:distilled_water 3')
        .itemOutputs('4x minecraft:oak_planks', '2x gtceu:wood_dust')
        .duration(300)
        .EUt(7)
    event.recipes.gtceu.cutter('lube_oak')
        .itemInputs('#minecraft:oak_logs')
        .inputFluids('gtceu:lubricant 1')
        .itemOutputs('6x minecraft:oak_planks', 'gtceu:wood_dust')
        .duration(200)
        .EUt(7)
    event.recipes.gtceu.cutter('water_spruce')
        .itemInputs('#minecraft:spruce_logs')
        .inputFluids('minecraft:water 5')
        .itemOutputs('4x minecraft:spruce_planks', '2x gtceu:wood_dust')
        .duration(400)
        .EUt(7)
    event.recipes.gtceu.cutter('dist_water_spruce')
        .itemInputs('#minecraft:spruce_logs')
        .inputFluids('gtceu:distilled_water 3')
        .itemOutputs('4x minecraft:spruce_planks', '2x gtceu:wood_dust')
        .duration(300)
        .EUt(7)
    event.recipes.gtceu.cutter('lube_spruce')
        .itemInputs('#minecraft:spruce_logs')
        .inputFluids('gtceu:lubricant 1')
        .itemOutputs('6x minecraft:spruce_planks', 'gtceu:wood_dust')
        .duration(200)
        .EUt(7)
    event.recipes.gtceu.cutter('water_birch')
        .itemInputs('#minecraft:birch_logs')
        .inputFluids('minecraft:water 5')
        .itemOutputs('4x minecraft:birch_planks', '2x gtceu:wood_dust')
        .duration(400)
        .EUt(7)
    event.recipes.gtceu.cutter('dist_water_birch')
        .itemInputs('#minecraft:birch_logs')
        .inputFluids('gtceu:distilled_water 3')
        .itemOutputs('4x minecraft:birch_planks', '2x gtceu:wood_dust')
        .duration(300)
        .EUt(7)
    event.recipes.gtceu.cutter('lube_birch')
        .itemInputs('#minecraft:birch_logs')
        .inputFluids('gtceu:lubricant 1')
        .itemOutputs('6x minecraft:birch_planks', 'gtceu:wood_dust')
        .duration(200)
        .EUt(7)
    event.recipes.gtceu.cutter('water_jungle')
        .itemInputs('#minecraft:jungle_logs')
        .inputFluids('minecraft:water 5')
        .itemOutputs('4x minecraft:jungle_planks', '2x gtceu:wood_dust')
        .duration(400)
        .EUt(7)
    event.recipes.gtceu.cutter('dist_water_jungle')
        .itemInputs('#minecraft:jungle_logs')
        .inputFluids('gtceu:distilled_water 3')
        .itemOutputs('4x minecraft:jungle_planks', '2x gtceu:wood_dust')
        .duration(300)
        .EUt(7)
    event.recipes.gtceu.cutter('lube_jungle')
        .itemInputs('#minecraft:jungle_logs')
        .inputFluids('gtceu:lubricant 1')
        .itemOutputs('6x minecraft:jungle_planks', 'gtceu:wood_dust')
        .duration(200)
        .EUt(7)
    event.recipes.gtceu.cutter('water_acacia')
        .itemInputs('#minecraft:acacia_logs')
        .inputFluids('minecraft:water 5')
        .itemOutputs('4x minecraft:acacia_planks', '2x gtceu:wood_dust')
        .duration(400)
        .EUt(7)
    event.recipes.gtceu.cutter('dist_water_acacia')
        .itemInputs('#minecraft:acacia_logs')
        .inputFluids('gtceu:distilled_water 3')
        .itemOutputs('4x minecraft:acacia_planks', '2x gtceu:wood_dust')
        .duration(300)
        .EUt(7)
    event.recipes.gtceu.cutter('lube_acacia')
        .itemInputs('#minecraft:acacia_logs')
        .inputFluids('gtceu:lubricant 1')
        .itemOutputs('6x minecraft:acacia_planks', 'gtceu:wood_dust')
        .duration(200)
        .EUt(7)
    event.recipes.gtceu.cutter('water_dark_oak')
        .itemInputs('#minecraft:dark_oak_logs')
        .inputFluids('minecraft:water 5')
        .itemOutputs('4x minecraft:dark_oak_planks', '2x gtceu:wood_dust')
        .duration(400)
        .EUt(7)
    event.recipes.gtceu.cutter('dist_water_dark_oak')
        .itemInputs('#minecraft:dark_oak_logs')
        .inputFluids('gtceu:distilled_water 3')
        .itemOutputs('4x minecraft:dark_oak_planks', '2x gtceu:wood_dust')
        .duration(300)
        .EUt(7)
    event.recipes.gtceu.cutter('lube_dark_oak')
        .itemInputs('#minecraft:dark_oak_logs')
        .inputFluids('gtceu:lubricant 1')
        .itemOutputs('6x minecraft:dark_oak_planks', 'gtceu:wood_dust')
        .duration(200)
        .EUt(7)
    event.recipes.gtceu.cutter('water_mangrove')
        .itemInputs('#minecraft:mangrove_logs')
        .inputFluids('minecraft:water 5')
        .itemOutputs('4x minecraft:mangrove_planks', '2x gtceu:wood_dust')
        .duration(400)
        .EUt(7)
    event.recipes.gtceu.cutter('dist_water_mangrove')
        .itemInputs('#minecraft:mangrove_logs')
        .inputFluids('gtceu:distilled_water 3')
        .itemOutputs('4x minecraft:mangrove_planks', '2x gtceu:wood_dust')
        .duration(300)
        .EUt(7)
    event.recipes.gtceu.cutter('lube_mangrove')
        .itemInputs('#minecraft:mangrove_logs')
        .inputFluids('gtceu:lubricant 1')
        .itemOutputs('6x minecraft:mangrove_planks', 'gtceu:wood_dust')
        .duration(200)
        .EUt(7)
    event.recipes.gtceu.cutter('water_cherry')
        .itemInputs('#minecraft:cherry_logs')
        .inputFluids('minecraft:water 5')
        .itemOutputs('4x minecraft:cherry_planks', '2x gtceu:wood_dust')
        .duration(400)
        .EUt(7)
    event.recipes.gtceu.cutter('dist_water_cherry')
        .itemInputs('#minecraft:cherry_logs')
        .inputFluids('gtceu:distilled_water 3')
        .itemOutputs('4x minecraft:cherry_planks', '2x gtceu:wood_dust')
        .duration(300)
        .EUt(7)
    event.recipes.gtceu.cutter('lube_cherry')
        .itemInputs('#minecraft:cherry_logs')
        .inputFluids('gtceu:lubricant 1')
        .itemOutputs('6x minecraft:cherry_planks', 'gtceu:wood_dust')
        .duration(200)
        .EUt(7)
    event.recipes.gtceu.cutter('water_crimson')
        .itemInputs('#minecraft:crimson_stems')
        .inputFluids('minecraft:water 5')
        .itemOutputs('4x minecraft:crimson_planks', '2x gtceu:wood_dust')
        .duration(400)
        .EUt(7)
    event.recipes.gtceu.cutter('dist_water_crimson')
        .itemInputs('#minecraft:crimson_stems')
        .inputFluids('gtceu:distilled_water 3')
        .itemOutputs('4x minecraft:crimson_planks', '2x gtceu:wood_dust')
        .duration(300)
        .EUt(7)
    event.recipes.gtceu.cutter('lube_crimson')
        .itemInputs('#minecraft:crimson_stems')
        .inputFluids('gtceu:lubricant 1')
        .itemOutputs('6x minecraft:crimson_planks', 'gtceu:wood_dust')
        .duration(200)
        .EUt(7)
    event.recipes.gtceu.cutter('water_warped')
        .itemInputs('#minecraft:warped_stems')
        .inputFluids('minecraft:water 5')
        .itemOutputs('4x minecraft:warped_planks', '2x gtceu:wood_dust')
        .duration(400)
        .EUt(7)
    event.recipes.gtceu.cutter('dist_water_warped')
        .itemInputs('#minecraft:warped_stems')
        .inputFluids('gtceu:distilled_water 3')
        .itemOutputs('4x minecraft:warped_planks', '2x gtceu:wood_dust')
        .duration(300)
        .EUt(7)
    event.recipes.gtceu.cutter('lube_warped')
        .itemInputs('#minecraft:warped_stems')
        .inputFluids('gtceu:lubricant 1')
        .itemOutputs('6x minecraft:warped_planks', 'gtceu:wood_dust')
        .duration(200)
        .EUt(7)
    event.recipes.gtceu.cutter('water_fir')
        .itemInputs('#biomesoplenty:fir_logs')
        .inputFluids('minecraft:water 5')
        .itemOutputs('4x biomesoplenty:fir_planks', '2x gtceu:wood_dust')
        .duration(400)
        .EUt(7)
    event.recipes.gtceu.cutter('dist_water_fir')
        .itemInputs('#biomesoplenty:fir_logs')
        .inputFluids('gtceu:distilled_water 3')
        .itemOutputs('4x biomesoplenty:fir_planks', '2x gtceu:wood_dust')
        .duration(300)
        .EUt(7)
    event.recipes.gtceu.cutter('lube_fir')
        .itemInputs('#biomesoplenty:fir_logs')
        .inputFluids('gtceu:lubricant 1')
        .itemOutputs('6x biomesoplenty:fir_planks', 'gtceu:wood_dust')
        .duration(200)
        .EUt(7)
    event.recipes.gtceu.cutter('water_redwood')
        .itemInputs('#biomesoplenty:redwood_logs')
        .inputFluids('minecraft:water 5')
        .itemOutputs('4x biomesoplenty:redwood_planks', '2x gtceu:wood_dust')
        .duration(400)
        .EUt(7)
    event.recipes.gtceu.cutter('dist_water_redwood')
        .itemInputs('#biomesoplenty:redwood_logs')
        .inputFluids('gtceu:distilled_water 3')
        .itemOutputs('4x biomesoplenty:redwood_planks', '2x gtceu:wood_dust')
        .duration(300)
        .EUt(7)
    event.recipes.gtceu.cutter('lube_redwood')
        .itemInputs('#biomesoplenty:redwood_logs')
        .inputFluids('gtceu:lubricant 1')
        .itemOutputs('6x biomesoplenty:redwood_planks', 'gtceu:wood_dust')
        .duration(200)
        .EUt(7)
    event.recipes.gtceu.cutter('water_mahogany')
        .itemInputs('#biomesoplenty:mahogany_logs')
        .inputFluids('minecraft:water 5')
        .itemOutputs('4x biomesoplenty:mahogany_planks', '2x gtceu:wood_dust')
        .duration(400)
        .EUt(7)
    event.recipes.gtceu.cutter('dist_water_mahogany')
        .itemInputs('#biomesoplenty:mahogany_logs')
        .inputFluids('gtceu:distilled_water 3')
        .itemOutputs('4x biomesoplenty:mahogany_planks', '2x gtceu:wood_dust')
        .duration(300)
        .EUt(7)
    event.recipes.gtceu.cutter('lube_mahogany')
        .itemInputs('#biomesoplenty:mahogany_logs')
        .inputFluids('gtceu:lubricant 1')
        .itemOutputs('6x biomesoplenty:mahogany_planks', 'gtceu:wood_dust')
        .duration(200)
        .EUt(7)
    event.recipes.gtceu.cutter('water_jacaranda')
        .itemInputs('#biomesoplenty:jacaranda_logs')
        .inputFluids('minecraft:water 5')
        .itemOutputs('4x biomesoplenty:jacaranda_planks', '2x gtceu:wood_dust')
        .duration(400)
        .EUt(7)
    event.recipes.gtceu.cutter('dist_water_jacaranda')
        .itemInputs('#biomesoplenty:jacaranda_logs')
        .inputFluids('gtceu:distilled_water 3')
        .itemOutputs('4x biomesoplenty:jacaranda_planks', '2x gtceu:wood_dust')
        .duration(300)
        .EUt(7)
    event.recipes.gtceu.cutter('lube_jacaranda')
        .itemInputs('#biomesoplenty:jacaranda_logs')
        .inputFluids('gtceu:lubricant 1')
        .itemOutputs('6x biomesoplenty:jacaranda_planks', 'gtceu:wood_dust')
        .duration(200)
        .EUt(7)
    event.recipes.gtceu.cutter('water_palm')
        .itemInputs('#biomesoplenty:palm_logs')
        .inputFluids('minecraft:water 5')
        .itemOutputs('4x biomesoplenty:palm_planks', '2x gtceu:wood_dust')
        .duration(400)
        .EUt(7)
    event.recipes.gtceu.cutter('dist_water_palm')
        .itemInputs('#biomesoplenty:palm_logs')
        .inputFluids('gtceu:distilled_water 3')
        .itemOutputs('4x biomesoplenty:palm_planks', '2x gtceu:wood_dust')
        .duration(300)
        .EUt(7)
    event.recipes.gtceu.cutter('lube_palm')
        .itemInputs('#biomesoplenty:palm_logs')
        .inputFluids('gtceu:lubricant 1')
        .itemOutputs('6x biomesoplenty:palm_planks', 'gtceu:wood_dust')
        .duration(200)
        .EUt(7)
    event.recipes.gtceu.cutter('water_willow')
        .itemInputs('#biomesoplenty:willow_logs')
        .inputFluids('minecraft:water 5')
        .itemOutputs('4x biomesoplenty:willow_planks', '2x gtceu:wood_dust')
        .duration(400)
        .EUt(7)
    event.recipes.gtceu.cutter('dist_water_willow')
        .itemInputs('#biomesoplenty:willow_logs')
        .inputFluids('gtceu:distilled_water 3')
        .itemOutputs('4x biomesoplenty:willow_planks', '2x gtceu:wood_dust')
        .duration(300)
        .EUt(7)
    event.recipes.gtceu.cutter('lube_willow')
        .itemInputs('#biomesoplenty:willow_logs')
        .inputFluids('gtceu:lubricant 1')
        .itemOutputs('6x biomesoplenty:willow_planks', 'gtceu:wood_dust')
        .duration(200)
        .EUt(7)
    event.recipes.gtceu.cutter('water_dead')
        .itemInputs('#biomesoplenty:dead_logs')
        .inputFluids('minecraft:water 5')
        .itemOutputs('4x biomesoplenty:dead_planks', '2x gtceu:wood_dust')
        .duration(400)
        .EUt(7)
    event.recipes.gtceu.cutter('dist_water_dead')
        .itemInputs('#biomesoplenty:dead_logs')
        .inputFluids('gtceu:distilled_water 3')
        .itemOutputs('4x biomesoplenty:dead_planks', '2x gtceu:wood_dust')
        .duration(300)
        .EUt(7)
    event.recipes.gtceu.cutter('lube_dead')
        .itemInputs('#biomesoplenty:dead_logs')
        .inputFluids('gtceu:lubricant 1')
        .itemOutputs('6x biomesoplenty:dead_planks', 'gtceu:wood_dust')
        .duration(200)
        .EUt(7)
    event.recipes.gtceu.cutter('water_magic')
        .itemInputs('#biomesoplenty:magic_logs')
        .inputFluids('minecraft:water 5')
        .itemOutputs('4x biomesoplenty:magic_planks', '2x gtceu:wood_dust')
        .duration(400)
        .EUt(7)
    event.recipes.gtceu.cutter('dist_water_magic')
        .itemInputs('#biomesoplenty:magic_logs')
        .inputFluids('gtceu:distilled_water 3')
        .itemOutputs('4x biomesoplenty:magic_planks', '2x gtceu:wood_dust')
        .duration(300)
        .EUt(7)
    event.recipes.gtceu.cutter('lube_magic')
        .itemInputs('#biomesoplenty:magic_logs')
        .inputFluids('gtceu:lubricant 1')
        .itemOutputs('6x biomesoplenty:magic_planks', 'gtceu:wood_dust')
        .duration(200)
        .EUt(7)
    event.recipes.gtceu.cutter('water_umbran')
        .itemInputs('#biomesoplenty:umbran_logs')
        .inputFluids('minecraft:water 5')
        .itemOutputs('4x biomesoplenty:umbran_planks', '2x gtceu:wood_dust')
        .duration(400)
        .EUt(7)
    event.recipes.gtceu.cutter('dist_water_umbran')
        .itemInputs('#biomesoplenty:umbran_logs')
        .inputFluids('gtceu:distilled_water 3')
        .itemOutputs('4x biomesoplenty:umbran_planks', '2x gtceu:wood_dust')
        .duration(300)
        .EUt(7)
    event.recipes.gtceu.cutter('lube_umbran')
        .itemInputs('#biomesoplenty:umbran_logs')
        .inputFluids('gtceu:lubricant 1')
        .itemOutputs('6x biomesoplenty:umbran_planks', 'gtceu:wood_dust')
        .duration(200)
        .EUt(7)
    event.recipes.gtceu.cutter('water_hellbark')
        .itemInputs('#biomesoplenty:hellbark_logs')
        .inputFluids('minecraft:water 5')
        .itemOutputs('4x biomesoplenty:hellbark_planks', '2x gtceu:wood_dust')
        .duration(400)
        .EUt(7)
    event.recipes.gtceu.cutter('dist_water_hellbark')
        .itemInputs('#biomesoplenty:hellbark_logs')
        .inputFluids('gtceu:distilled_water 3')
        .itemOutputs('4x biomesoplenty:hellbark_planks', '2x gtceu:wood_dust')
        .duration(300)
        .EUt(7)
    event.recipes.gtceu.cutter('lube_hellbark')
        .itemInputs('#biomesoplenty:hellbark_logs')
        .inputFluids('gtceu:lubricant 1')
        .itemOutputs('6x biomesoplenty:hellbark_planks', 'gtceu:wood_dust')
        .duration(200)
        .EUt(7)
})