ServerEvents.recipes(event => {
    event.remove({mod: 'ae2', output: 'ae2:inscriber'})
    event.remove({mod: 'expatternprovider', output: 'expatternprovider:ex_inscriber'})
    event.remove({mod: 'create', output: 'create:propeller'})
    event.remove({mod: 'create', output: 'create:whisk'})
    event.remove({mod: 'create', output: 'create:copper_casing'})
    event.remove({mod: 'create', output: 'create:brass_casing'})
    event.remove({mod: 'create', output: 'create:andesite_casing'})
    event.remove({mod: 'create', output: 'create:shaft'})
    event.remove({mod: 'create', output: 'create:belt_connector'})
    event.remove({mod: 'create', output: 'create:large_cogwheel'})
    event.remove({mod: 'create', output: 'create:cogwheel'})
    event.remove({mod: 'create', output: 'create:windmill_bearing'})
    event.remove({mod: 'create', output: 'create:basin'})
    event.remove({mod: 'create', output: 'create:encased_fan'})
    event.remove({mod: 'create', output: 'create:water_wheel'})
    event.remove({mod: 'create', output: 'create:large_water_wheel'})
    event.remove({mod: 'create', output: 'create:mechanical_press'})
    event.remove({mod: 'create', output: 'create:fluid_tank'})
    event.remove({mod: 'create', output: 'create:rose_quartz'})
    event.remove({mod: 'create', output: 'precision_mechanism'})
    event.remove({mod: 'create', output: 'brass_ingot'})
    event.remove({mod: 'create', output: 'obsidian_plate'})
    event.remove({mod: 'create', output: 'mechanical_crafter'})
    event.remove({mod: 'create', output:'#minecraft:planks'})
    event.remove({mod: 'create', output:'create:goggles'})
    event.remove({mod: 'create', output: 'create:mechanical_pump'})
    event.remove({mod: 'create', output: 'create:mechanical_saw'})
    event.remove({mod: 'create', output: 'create:deployer'})
    event.remove({mod: 'createcasing', output: 'createcasing:industrial_press'})
    event.remove({mod: 'createcasing', output: 'createcasing:brass_press'})
    event.remove({mod: 'createcasing', output: 'createcasing:copper_press'})
    event.remove({mod: 'createcasing', output: 'createcasing:railway_press'})
    event.remove({mod: 'createcasing', output: 'createcasing:creative_press'})
    event.remove({mod: 'create', output: 'create:mechanical_mixer'})
    event.remove({mod: 'createcasing', output: 'createcasing:industrial_iron_mixer'})
    event.remove({mod: 'createcasing', output: 'createcasing:brass_mixer'})
    event.remove({mod: 'createcasing', output: 'createcasing:copper_mixer'})
    event.remove({mod: 'createcasing', output: 'createcasing:railway_mixer'})
    event.remove({mod: 'createcasing', output: 'createcasing:creative_mixer'})
    event.remove({mod: 'tfmg', output: 'tfmg:cast_iron_ingot'})
    event.remove({mod: 'createdeco', output: 'createdeco:industrial_iron_ingot'})
    event.remove({mod: 'create', output: 'create:andesite_alloy'})
    event.remove({mod: 'tfmg', output: 'tfmg:screw'})
    event.remove({mod: 'tfmg', output: 'tfmg:screwdriver'})
    event.remove({mod: 'tfmg', output: 'tfmg:coke_oven'})
    event.remove({mod: 'tfmg', output: 'tfmg:molten_steel'})
    event.remove({mod: 'tfmg', output: 'tfmg:industrial_pipe'})
    event.remove({mod: 'tfmg', output: 'tfmg:steel_frame'})
    event.remove({mod: 'tfmg', output: 'tfmg:heavy_machine_casing'})
    event.remove({mod: 'tfmg', output: 'tfmg:pumpjack_hammer_head'})
    event.remove({mod: 'tfmg', output: 'tfmg:pumpjack_hammer_part'})
    event.remove({mod: 'tfmg', output: 'tfmg:pumpjack_hammer_connector'})
    event.remove({mod: 'tfmg', output: 'tfmg:pumpjack_crank'})
    event.remove({mod: 'tfmg', output: 'tfmg:pumpjack_base'})
    event.remove({mod: 'tfmg', output: 'tfmg:pumpjack_hammer'})
    event.remove({mod: 'tfmg', output: 'tfmg:machine_input'})
    event.remove({mod: 'ironchests', output:'ironchests:iron_chest'})
    event.remove({mod: 'gtceu', output:'gtceu:iv_processing_array'})
    event.remove({mod: 'gtceu', output:'gtceu:luv_processing_array'})
    event.remove({mod: 'create', output: 'ad_astra:cheese'})
    event.remove({mod: 'create', output: 'ad_astra:ice_shard'})
    event.remove({mod: 'create', output: 'ad_astra:raw_calorite'})
    event.remove({mod: 'create', output: 'ad_astra:raw_ostrum'})
    event.remove({mod: 'create', output: 'ad_astra:raw_desh'})
    event.remove({mod: 'create', output: 'create:crushed_raw_iron'})
    event.remove({mod: 'create', output: 'create:crushed_raw_tin'})
    event.remove({mod: 'create', output: 'create:crushed_raw_gold'})
    event.remove({mod: 'create', output: 'create:crushed_raw_silver'})
    event.remove({mod: 'create', output: 'create:crushed_raw_copper'})
    event.remove({mod: 'create', output: 'create:crushed_raw_uranium'})
    event.remove({mod: 'create', output: 'create:crushed_raw_lead'})
    event.remove({mod: 'create', output: 'create:crushed_raw_platinum'})
    event.remove({mod: 'create', output: 'create:crushed_raw_nickel'})
    event.remove({mod: 'create', output: 'create:crushed_raw_aluminum'})
    event.remove({mod: 'create', output: 'create:crushed_raw_osmium'})
    event.remove({mod: 'create', output: 'create:crushed_raw_zinc'})
    event.remove({output: 'gtceu:wrought_iron_nugget', type: 'minecraft:smelting'})
    event.remove({output: 'minecraft:iron_nugget', type: 'minecraft:smelting'})
    event.remove({output: 'minecraft:iron_nugget', type: 'minecraft:blasting'})
    event.remove({output: 'minecraft:gold_nugget', type: 'minecraft:smelting'})
    event.remove({output: 'minecraft:gold_nugget', type: 'minecraft:blasting'})
    event.remove({output: 'gtceu:zircon_dust', type: 'minecraft:smelting'})
    event.remove({output: 'gtceu:zircon_dust', type: 'minecraft:blasting'})
    event.remove({output: 'minecraft:charcoal', type: 'minecraft:smelting'})
    event.remove({output: 'gtceu:steel_ingot', type: 'minecraft:blasting'})
    event.remove({output: 'gtceu:steel_ingot', type: 'minecraft:shaped'})
    event.remove({output: 'gtceu:steel_ingot', type: 'minecraft:shapless'})
    event.remove({output: 'ad_astra:steel_ingot' })
    event.remove({id:'gtceu:shaped/compressed_coke_clay'})
    event.remove({id:'gtceu:shapeless/compressed_clay'})
    event.remove({id:'gtceu:shapeless/dust_bronze'})
    event.remove({id:'gtceu:shapeless/dust_brass'})
    event.remove({mod: 'gtceu', output:'ae2:printed_silicon'})
    event.remove({mod: 'gtceu', output:'ae2:printed_calculation_processor'})
    event.remove({mod: 'gtceu', output:'ae2:printed_engineering_processor'})
    event.remove({mod: 'gtceu', output:'ae2:printed_logic_processor'})
    event.remove({mod: 'gtceu', output:'ae2:calculation_processor'})//
    event.remove({mod: 'gtceu', output:'ae2:engineering_processor'})//
    event.remove({mod: 'gtceu', output:'ae2:logic_processor'})//
    //event.remove({id:'gtceu:mixer/mixer/ae2/transform/fluix_crystal'})
    //event.remove({id:'gtceu:create_mixer/mixer/ae2/transform/fluix_crystal'})
    event.remove({id:'create:compat/ae2/mixing/fluix_crystal'})
    event.remove({id:'gtceu:fluid_solidifier/fluid_solidfication/ae2/charged_certus_quartz_crystal'})
    event.remove({id:'gtceu:forming_press/forming_press/ae2/calculation_processor_press'})
    event.remove({id:'gtceu:forming_press/forming_press/ae2/engineering_processor_press'})
    event.remove({id:'gtceu:forming_press/forming_press/ae2/logic_processor_press'})
    event.remove({id:'tfmg:casting_steel'})
    event.remove({id:'ironchests:blank_chest_upgrade'})
    event.remove({id:'ironchests:copper_chest_upgrade'})
    event.remove({id:'ironchests:iron_chest_upgrade'})
    event.remove({id:'ironchests:gold_chest_upgrade'})
    event.remove({id:'ironchests:diamond_chest_upgrade'})
    event.remove({id:'ironchests:crystal_chest_upgrade'})
    event.remove({id:'ironchests:obsidian_chest_upgrade'})
    event.remove({id:'ironchests:copper_barrel'})
    event.remove({id:'ironchests:iron_barrel'})
    event.remove({id:'ironchests:gold_barrel'})
    event.remove({id:'ironchests:diamond_barrel'})
    event.remove({id:'ironchests:crystal_barrel'})
    event.remove({id:'ironchests:obsidian_barrel'})
    event.remove({id:'ironchests:copper_chest'})
    event.remove({id:'ironchests:iron_chest'})
    event.remove({id:'ironchests:gold_chest'})
    event.remove({id:'ironchests:diamond_chest'})
    event.remove({id:'ironchests:crystal_chest'})
    event.remove({id:'ironchests:obsidian_chest'})
    event.remove({id:'ironchests:iron_dolly'})
    event.remove({id:'ironchests:diamond_dolly'})
    event.remove({id:'dawnoftimebuilder:mulberry_paper'})
    event.remove({id:'farmersdelight:paper_from_tree_bark'})
    event.remove({id:'pamhc2crops:paper_x2_paper_plants'})
    event.remove({id:'create:crafting/kinetics/fluid_pipe_vertical'})
    event.remove({id:'create:crafting/kinetics/mechanical_crafter'})
    event.remove({id:'create:crafting/kinetics/item_drain'})
    event.remove({id:'create:crafting/kinetics/spout'})
    event.remove({id:'create:crafting/logistics/andesite_funnel'})
    event.remove({id:'create:crafting/logistics/andesite_tunnel'})
    event.remove({id:'create:crafting/logistics/brass_funnel'})
    event.remove({id:'create:crafting/logistics/brass_tunnel'})
    event.remove({id:'create:crafting/kinetics/chute'})
    event.remove({id:'create:crafting/kinetics/smart_chute'})
    event.remove({id:'createlowheated:charcoal_burner'})
    event.remove({id:'create:crafting/kinetics/steam_engine'})
    event.remove({id:'create:crafting/kinetics/empty_blaze_burner'})
    event.remove({id:'pamhc2foodextended:charcoal_coconut_x1'})
    event.remove({id:'vintageimprovements:craft/belt_grinder'})
    event.remove({id:'vintageimprovements:craft/spring_coiling_machine'})
    event.remove({id:'vintageimprovements:coiling/brass_ingot'})
    event.remove({id:'vintageimprovements:coiling/calorite_wire'})
    event.remove({id:'vintageimprovements:coiling/calorite_rod'})
    event.remove({id:'vintageimprovements:coiling/copper_plate'})
    event.remove({id:'vintageimprovements:coiling/steel_wire'})
    event.remove({id:'vintageimprovements:coiling/desh_rod'})
    event.remove({id:'vintageimprovements:coiling/iron_plate'})
    event.remove({id:'vintageimprovements:coiling/golden_plate'})
    event.remove({id:'vintageimprovements:coiling/desh_wire'})
    event.remove({id:'vintageimprovements:coiling/ostrum_wire'})
    event.remove({id:'vintageimprovements:coiling/brass_wire'})
    event.remove({id:'vintageimprovements:coiling/ostrum_rod'})
    event.remove({id:'vintageimprovements:coiling/copper_ingot'})
    event.remove({id:'vintageimprovements:coiling/iron_ingot'})
    event.remove({id:'vintageimprovements:coiling/steel_rod'})
    event.remove({id:'vintageimprovements:coiling/golden_ingot'})
    event.remove({id:'vintageimprovements:craft/vanadium_nuggets_to_ingot'})
    event.remove({id:'vintageimprovements:craft/vanadium_block_to_ingots'})
    event.remove({id:'vintageimprovements:craft/vanadium_ingots_to_block'})
    event.remove({id:'vintageimprovements:craft/sulfur_items_to_block'})
    event.remove({id:'vintageimprovements:craft/sulfur_nuggets_to_item'})
    event.remove({id:'vintageimprovements:craft/sulfur_block_to_items'})
    event.remove({id:'vintageimprovements:craft/sulfur_item_to_nuggets'})
    event.remove({id:'vintageimprovements:crushing/scoria_recycling'})
    event.remove({id:'vintageimprovements:crushing/scoria'})
    event.remove({id:'gtceu:shaped/rechiseledcreate/mechanical_chisel'})
    event.remove({id:'gtceu:shaped/steam_boiler_solar_bronze'})
    event.remove({id:'gtceu:shaped/steam_boiler_solar_steel'})
    event.remove({id:'create:mixing/brass_ingot'})
    event.remove({id:'create:crafting/kinetics/rope_pulley'})
    event.remove({id:'create:crafting/kinetics/mechanical_drill'})
    event.remove({id:'sliceanddice:slicer'})
    event.remove({id:'create:crafting/kinetics/mechanical_roller'})
    event.remove({id:'create:crafting/kinetics/mechanical_piston'})
    event.remove({id:'create:crafting/kinetics/millstone'})
    event.remove({id:'create:crafting/kinetics/cuckoo_clock'})
    event.remove({id:'create:crafting/kinetics/mechanical_bearing'})
    event.remove({id:'create:crafting/kinetics/speedometer'})
    event.remove({id:'create:crafting/kinetics/gantry_carriage'})
    event.remove({id:'vintageimprovements:mechanical_crafting/helve_hammer'})
    event.remove({id:'gtceu:shapeless/rubber_wood_planks'})
    event.remove({id:'tfmg:sequenced_assembly/heavy_plate'})
    event.remove({id:'createqol:item_application/botanist_saw_using_deployer'})
    event.remove({id:'createqol:item_application/glassblower_saw_using_deployer'})
    event.remove({id:'createqol:item_application/loom_saw_using_deployer'})
    event.remove({id:'createqol:item_application/loom_saw_using_deployer'})
    event.remove({id:'createqol:item_application/tinkering_saw_using_deployer'})
    event.remove({id:'createdeco:industrial_iron_nugget_from_industrial_iron_ingot'})
    event.remove({id:'createdeco:netherite_nugget_from_netherite_ingot'})
    event.remove({id:'gtceu:assembly_line/wetware_mainframe_uhv'})
    event.remove({id:'gtceu:assembly_line/wetware_super_computer_uv'})
    event.remove({id:'gtceu:assembly_line/crystal_mainframe_uv'})
    event.remove({id:'gtceu:implosion_compressor/implode_dust_magneto_resonatic__tnt'})
    event.remove({id:'tfmg:crushing/lignite'})
    event.remove({id:'etched:blank_music_disc'})
    event.remove({id:'create:milling/charcoal'})
    event.remove({id:'create:milling/coal'})
    event.remove({id:'create:milling/andesite'})
    event.remove({id:'create:milling/clay'})
    event.remove({id:'minecraft:bread'})
    event.remove({id:'pamhc2crops:bread_grain'})
    event.remove({id:'vintagedelight:oat_bread'})
    event.remove({id:'vintagedelight:oat_dough_from_eggs'})
    event.remove({id:'vintagedelight:oat_dough_from_water'})
    event.remove({id:'create:crafting/appliances/dough'})
    event.remove({id:'create_central_kitchen:crafting/dough_4'})
    event.remove({id:'create_central_kitchen:crafting/dough_3'})
    event.remove({id:'create_central_kitchen:crafting/dough_2'})
    event.remove({id:'create_central_kitchen:crafting/dough_1'})
    event.remove({id:'farmersdelight:wheat_dough_from_water'})
    event.remove({id:'farmersdelight:wheat_dough_from_eggs'})
    event.remove({id:'create:mixing/dough_by_mixing'})
    event.remove({id:'pamhc2foodcore:bread_dough'})
    event.remove({id:'vintagedelight:cutting/oat_cutting'})
    event.remove({id:'vintagedelight:cutting/oat_cutting_using_deployer'})
    event.remove({id:'create:crafting/kinetics/fluid_pipe'})
    event.remove({id:'createlowheated:basic_burner'})
    event.remove({id:'ad_astra:iron_rod'})
    event.remove({id:'ad_astra:steel_rod'})
    event.remove({id:'ad_astra:photovoltaic_etrium_cell'})
    event.remove({id:'gtceu:extruder/extrude_wood_ingot_to_small_gear'})
    event.remove({id:'gtceu:alloy_smelter/alloy_smelt_wood_ingot_to_small_gear'})
    event.remove({id:'gtceu:shaped/treated_wood_planks'})
    event.remove({id:'gtceu:shaped/good_circuit_board'})
    event.remove({id:'gtceu:shaped/electronic_circuit_mv'})
    event.remove({id:'gtceu:shaped/electronic_circuit_lv'})
    event.remove({id:'gtceu:shaped/resistor_wire'})
    event.remove({id:'gtceu:shaped/resistor_wire_fine_charcoal'})
    event.remove({id:'gtceu:shaped/resistor_wire_carbon'})
    event.remove({id:'gtceu:shaped/resistor_wire_fine_carbon'})
    event.remove({id:'gtceu:shaped/resistor_wire_fine'})
    event.remove({id:'gtceu:shaped/resistor_wire_charcoal'})
    event.remove({id:'gtceu:shaped/vacuum_tube'})
    event.remove({id:'gtceu:shaped/basic_circuit_board'})
    event.remove({id:'tfmg:crafting/casting_spout'})
    event.remove({id:'tfmg:crafting/pipes/cast_iron_pipe_vertical'})
    event.remove({id:'tfmg:crafting/pipes/cast_iron_pipe_horizontal'})
    event.remove({id:'tfmg:crafting/casting_basin'})
    event.remove({id:'tfmg:crafting/pipes/cast_iron_fluid_pump'})
    event.remove({id:'tfmg:casting/steel'})
    event.remove({id:'framedblocks:framed_lever'})
    event.remove({id:'supplementaries:sconce_lever'})
    event.remove({id:'ad_astra:alloying/steel_ingot_from_alloying_iron_ingot_and_coals'})
    event.remove({id:'caupona:crafting/walnut_planks'})
    event.remove({id:'dawnoftimebuilder:charred_spruce_planks'})
    event.remove({id:'dawnoftimebuilder:waxed_oak_planks'})
    event.remove({id:'ad_astra:aeronos_planks'})
    event.remove({id:'ad_astra:strophar_planks'})
    event.remove({id:'ad_astra:glacian_planks'})
    event.remove({id:'ad_astra:compressor'})
    event.remove({id:'ad_astra:compressing/iron_plate_from_compressing_iron_ingot'})
    event.remove({id:'ad_astra:compressing/calorite_plate_from_compressing_calorite_blocks'})
    event.remove({id:'ad_astra:compressing/ostrum_plate_from_compressing_ostrum_blocks'})
    event.remove({id:'ad_astra:compressing/steel_plate_from_compressing_steel_blocks'})
    event.remove({id:'ad_astra:compressing/desh_plate_from_compressing_desh_blocks'})
    event.remove({id:'ad_astra:compressing/desh_plate_from_compressing_desh_ingots'})
    event.remove({id:'ad_astra:compressing/calorite_plate_from_compressing_calorite_ingots'})
    event.remove({id:'ad_astra:compressing/steel_plate_from_compressing_steel_ingots'})
    event.remove({id:'ad_astra:compressing/ostrum_plate_from_compressing_ostrum_ingots'})
    event.remove({id:'ad_astra:compressing/iron_plate_from_compressing_iron_block'})
    event.remove({id:'framedblocks:powered_framing_saw'})
    event.remove({id:'framedblocks:framing_saw'})
    event.remove({id:'minecraft:polished_blackstone_pressure_plate'})
    event.remove({id:'minecraft:polished_blackstone_button'})
    event.remove({id:'gtceu:shaped/biomesoplenty/fir_button'})
    event.remove({id:'gtceu:shaped/biomesoplenty/redwood_button'})
    event.remove({id:'gtceu:shaped/biomesoplenty/mahogany_button'})
    event.remove({id:'gtceu:shaped/biomesoplenty/jacaranda_button'})
    event.remove({id:'gtceu:shaped/biomesoplenty/palm_button'})
    event.remove({id:'gtceu:shaped/biomesoplenty/willow_button'})
    event.remove({id:'gtceu:shaped/biomesoplenty/dead_button'})
    event.remove({id:'gtceu:shaped/biomesoplenty/magic_button'})
    event.remove({id:'gtceu:shaped/biomesoplenty/umbran_button'})
    event.remove({id:'gtceu:shaped/biomesoplenty/hellbark_button'})
    event.remove({id:'framedblocks:framed_button'})
    event.remove({id:'framedblocks:framed_stone_button'})
    event.remove({id:'framedblocks:framed_obsidian_pressure_plate'})
    event.remove({id:'framedblocks:framed_gold_pressure_plate'})
    event.remove({id:'framedblocks:framed_iron_pressure_plate'})
    event.remove({id:'ad_astra:iron_plating_button'})
    event.remove({id:'ad_astra:steel_plating_button'})
    event.remove({id:'ad_astra:desh_plating_button'})
    event.remove({id:'ad_astra:ostrum_plating_button'})
    event.remove({id:'ad_astra:calorite_plating_button'})
    event.remove({id:'ad_astra:glacian_button'})
    event.remove({id:'caupona:crafting/walnut_button'})
    event.remove({id:'caupona:crafting/walnut_pressure_plate'})
    event.remove({id:'minecraft:cherry_pressure_plate'})
    event.remove({id:'minecraft:bamboo_pressure_plate'})
    event.remove({id:'framedblocks:framed_pressure_plate'})
    event.remove({id:'ad_astra:iron_plating_pressure_plate'})
    event.remove({id:'ad_astra:steel_plating_pressure_plate'})
    event.remove({id:'ad_astra:desh_plating_pressure_plate'})
    event.remove({id:'ad_astra:ostrum_plating_pressure_plate'})
    event.remove({id:'ad_astra:calorite_plating_pressure_plate'})
    event.remove({id:'ad_astra:glacian_pressure_plate'})
    event.remove({id:'framedblocks:framed_stone_pressure_plate'})
    event.remove({id:'minecraft:polished_blackstone_pressure_plate'})
    event.remove({id:'apotheosis:torch'})
    event.remove({id:'create:crafting/materials/copper_nugget'})
    event.remove({id:'caupona:crafting/lead_nugget_from_ingot'})
    event.remove({id:'create:crafting/materials/zinc_nugget_from_decompacting'})
    event.remove({id:'create:crafting/materials/brass_nugget_from_decompacting'})
    event.remove({id:'ad_astra:steel_nugget'})
    event.remove({id:'framedblocks:framed_bookshelf'})
    event.remove({id:'productivetrees:sawmill/dark_oak_planks_from_log'})
    event.remove({id:'productivetrees:sawmill/oak_planks_from_log'})
    event.remove({id:'productivetrees:sawmill/crimson_planks_from_log'})
    event.remove({id:'productivetrees:sawmill/cherry_planks_from_log'})
    event.remove({id:'productivetrees:sawmill/acacia_planks_from_log'})
    event.remove({id:'productivetrees:sawmill/spruce_planks_from_log'})
    event.remove({id:'productivetrees:sawmill/jungle_planks_from_log'})
    event.remove({id:'productivetrees:sawmill/mangrove_planks_from_log'})
    event.remove({id:'productivetrees:sawmill/birch_planks_from_log'})
    event.remove({id:'productivetrees:sawmill/warped_planks_from_log'})
    event.remove({id:'productivebees:centrifuge_cauldron'})
    event.remove({id:'productivebees:centrifuge'})
    event.remove({id:'productivebees:powered_centrifuge/vanilla'})
    event.remove({id:'productivebees:heated_centrifuge'})
    event.remove({id:'tfmg:crafting/pipes/brass_pipe_horizontal'})
    event.remove({id:'tfmg:crafting/pipes/brass_pipe_vertical'})
    event.remove({id:'tfmg:crafting/pipes/aluminum_pipe_vertical'})
    event.remove({id:'tfmg:crafting/pipes/aluminum_pipe_horizontal'})
    event.remove({id:'createcasing:cutting/brass_ingot'})
    event.remove({id:'minecraft:netherite_ingot_from_netherite_block'})
    event.remove({id:'minecraft:netherite_ingot'})
    event.remove({id:'createdeco:netherite_ingot'})
    event.remove({id:'create:crafting/materials/andesite_alloy_block'})
    event.remove({id:'ad_astra:desh_ingot'})
    event.remove({id:'ad_astra:desh_ingot_from_desh_block'})
    event.remove({id:'ad_astra:ostrum_ingot'})
    event.remove({id:'ad_astra:ostrum_ingot_from_ostrum_block'})
    event.remove({id:'ad_astra:calorite_block'})
    event.remove({id:'ad_astra:calorite_ingot_from_calorite_block'})
    event.remove({id:'ad_astra:calorite_ingot'})
    event.remove({id:'ad_astra:calorite_nugget'})
    event.remove({id:'ad_astra:ostrum_nugget'})
    event.remove({id:'ad_astra:ostrum_block'})
    event.remove({id:'ad_astra:desh_block'})
    event.remove({id:'ad_astra:desh_nugget'})
    event.remove({id:'minecraft:kjs/gtceu_manganese_phosphide_nugget'})
    event.remove({id:'ad_astra:rocket_nose_cone'})
    event.remove({id:'treetap:tap'})
    event.remove({id:'ad_astra:rocket_fin'})
    event.remove({id:'ad_astra:engine_frame'})
    event.remove({id:'ad_astra:steel_engine'})
    event.remove({id:'productivetrees:sawmill'})
    event.remove({id:'ad_astra:desh_engine'})
    event.remove({id:'ad_astra:ostrum_engine'})
    event.remove({id:'ad_astra:calorite_engine'})
    event.remove({id:'pointblank:guninternals'})
    event.remove({id:'pointblank:gunmetal_ingot_from_nuggets'})
    event.remove({id:'pointblank:gunmetal_ingot_from_blasting_gunmetal_mesh'})
    event.remove({id:'pointblank:gunmetal_ingot_from_smelting_gunmetal_mesh'})
    event.remove({id:'pointblank:gunmetal_mesh'})
    event.remove({id:'pointblank:gunmetal_nugget'})
    event.remove({id:'minecraft:netherite_scrap_from_blasting'})
    event.remove({id:'minecraft:netherite_scrap'})
    event.remove({id:'gtceu:smelting/dust_netherite_alloy__demagnetize_from_dust'})
    event.remove({id:'gtceu:macerator/macerate_netherite_scrap'})
    event.remove({id:'ad_astra:raw_desh_block'})
    event.remove({id:'ad_astra:raw_ostrum_block'})
    event.remove({id:'ad_astra:raw_calorite_block'})
    event.remove({id:'ad_astra:raw_desh'})
    event.remove({id:'ad_astra:raw_ostrum'})
    event.remove({id:'ad_astra:raw_calorite'})
    event.remove({id:'draconicevolution:decompress/draconium_nugget'})
    event.remove({id:'draconicevolution:compress/draconium_ingot'})
    event.remove({id:'draconicevolution:decompress/draconium_ingot'})
    event.remove({id:'draconicevolution:compress/draconium_block'})
    event.remove({id:'draconicevolution:decompress/awakened_draconium_nugget'})
    event.remove({id:'draconicevolution:compress/awakened_draconium_ingot'})
    event.remove({id:'draconicevolution:decompress/awakened_draconium_ingot'})
    event.remove({id:'draconicevolution:compress/awakened_draconium_block'})
    event.remove({id:'vintageimprovements:pressurizing/sulfuric_acid'})
    event.remove({id:'vintageimprovements:pressurizing/copper_sulfate'})
    event.remove({id:'vintageimprovements:pressurizing/sulfur_dioxide'})
    event.remove({id:'vintageimprovements:pressurizing/sulfur_trioxide_alt'})
    event.remove({id:'vintageimprovements:pressurizing/sulfur_trioxide'})
    event.remove({id:'minecraft:copper_ingot'})
    event.remove({id:'create:crafting/materials/brass_ingot_from_decompacting'})
    event.remove({id:'ad_astra:steel_ingot_from_steel_block'})
    event.remove({id:'create:crafting/materials/zinc_ingot_from_decompacting'})
    event.remove({id:'vintageimprovements:curving/diamond'})
    event.remove({id:'vintageimprovements:hammering/netherite_ingot'})
    event.remove({id:'vintageimprovements:coiling/blaze_rod'})
    event.remove({id:'tfmg:crafting/steel_tank'})
    event.remove({id:'create_connected:crafting/kinetics/fluid_vessel'})
    event.remove({id:'tfmg:crafting/pipes/steel_pipe_horizontal'})
    event.remove({id:'tfmg:crafting/pipes/steel_pipe_vertical'})
    event.remove({id:'tfmg:crafting/pipes/steel_fluid_pump'})
    event.remove({id:'tfmg:crafting/pipes/brass_fluid_pump'})
    event.remove({id:'tfmg:crafting/pipes/plastic_pipe_vertical'})
    event.remove({id:'tfmg:crafting/pipes/plastic_pipe_horizontal'})
    event.remove({id:'tfmg:crafting/pipes/plastic_fluid_pump'})
    event.remove({id:'tfmg:crafting/pipes/plastic_smart_fluid_pipe'})
    event.remove({id:'tfmg:crafting/pipes/plastic_fluid_valve'})
    event.remove({id:'tfmg:crafting/pipes/aluminum_fluid_pump'})
    event.remove({id:'tfmg:crafting/pipes/aluminum_smart_fluid_pipe'})
    event.remove({id:'tfmg:crafting/pipes/aluminum_fluid_valve'})
    event.remove({id:'tfmg:industrial_blasting/steel'})
    event.remove({id:'ad_astra:steel_ingot'})
    event.remove({id:'tfmg:stonecutting/ingot_mold'})
    event.remove({id:'gtceu:smelting/dust_obsidian__demagnetize_from_dust'})
    event.remove({id:'tfmg:item_application/steel_casing_using_deployer'})
    event.remove({id:'tfmg:item_application/steel_casing'})
    event.remove({id:'create:crafting/kinetics/brass_hand'})
    event.remove({id:'create:crafting/kinetics/smart_fluid_pipe'})
    event.remove({id:'tfmg:crafting/pipes/steel_smart_fluid_pipe'})
    event.remove({id:'tfmg:crafting/pipes/brass_smart_fluid_pipe'})
    event.remove({id:'tfmg:crafting/pipes/cast_iron_smart_fluid_pipe'})
    event.remove({id:'create:sandpaper_polishing/rose_quartz'})
    event.remove({id:'gtceu:fluid_solidifier/solidify_stellar_matter_to_ingot'})
    event.remove({id:'vintageimprovements:craft/vacuum_chamber'})
    event.remove({id:'vintageimprovements:craft/curving_press'})
    event.remove({id:'gtceu:implosion_compressor/implode_dust_magneto_resonatic__powderbarrel'})
    event.remove({id:'gtceu:implosion_compressor/implode_dust_magneto_resonatic__itnt'})
    event.remove({id:'gtceu:implosion_compressor/implode_dust_magneto_resonatic__dynamite'})
    event.remove({id:'createbigcannons:compacting/iron_to_cast_iron_block'})
    event.remove({id:'createbigcannons:cast_iron_block'})
    event.remove({id:'createbigcannons:compacting/iron_to_cast_iron_ingot'})
    event.remove({id:'createbigcannons:compacting/forge_cast_iron_ingot'})
    event.remove({id:'createbigcannons:cast_iron_ingot_from_block'})
    event.remove({id:'createbigcannons:cast_iron_ingot_from_nuggets'})
    event.remove({id:'createbigcannons:compacting/forge_cast_iron_nugget'})
    event.remove({id:'createbigcannons:cast_iron_nugget'})
    event.remove({id:'createbigcannons:melting/melt_cast_iron_ingot'})
    event.remove({id:'createbigcannons:melting/melt_cast_iron_block'})
    event.remove({id:'createbigcannons:melting/melt_cast_iron_nugget'})
    event.remove({id:'createbigcannons:melting/melt_bronze_ingot'})
    event.remove({id:'createbigcannons:melting/melt_bronze_nugget'})
    event.remove({id:'createbigcannons:melting/melt_bronze_block'})
    event.remove({id:'createbigcannons:melting/melt_steel_block'})
    event.remove({id:'createbigcannons:melting/melt_steel_nugget'})
    event.remove({id:'createbigcannons:melting/melt_steel_ingot'})
    event.remove({id:'createbigcannons:melting/melt_nethersteel_nugget'})
    event.remove({id:'createbigcannons:melting/melt_nethersteel_block'})
    event.remove({id:'createbigcannons:melting/melt_nethersteel_ingot'})
    event.remove({id:'createbigcannons:compacting/forge_nethersteel_ingot'})
    event.remove({id:'createbigcannons:compacting/forge_nethersteel_nugget'})
    event.remove({id:'createbigcannons:compacting/forge_steel_ingot'})
    event.remove({id:'createbigcannons:compacting/forge_bronze_ingot'})
    event.remove({id:'tfmg:crafting/aluminum_from_block'})
    event.remove({id:'tfmg:crafting/aluminum_block'})
    event.remove({id:'vintageimprovements:hammering/nethersteel_ingot'})
    event.remove({id:'createdeco:industrial_iron_block'})
    event.remove({id:'create:industrial_iron_block_from_ingots_iron_stonecutting'})
    event.remove({id:'create:industrial_iron_block_from_iron_ingots_stonecutting'})
    event.remove({id:'tfmg:crafting/cast_iron_block'})
    event.remove({id:'tfmg:crafting/steel_coghweel'})
    event.remove({id:'tfmg:crafting/large_steel_coghweel'})
    event.remove({id:'tfmg:crafting/aluminum_coghweel'})
    event.remove({id:'tfmg:crafting/large_aluminum_coghweel'})
    event.remove({id:'tfmg:smelting/fireclay_brick'})
    event.remove({id:'tfmg:crafting/fireproof_bricks'})
    event.remove({id:'tfmg:crafting/blast_furnace_output'})
    event.remove({id:'tfmg:crafting/resistor_item'})
    event.remove({id:'tfmg:crafting/capacitor_item'})
    event.remove({id:'gtceu:shaped/iron_helmet'})
    event.remove({id:'gtceu:shaped/iron_chestplate'})
    event.remove({id:'gtceu:shaped/iron_leggings'})
    event.remove({id:'gtceu:shaped/iron_boots'})
    event.remove({id:'gtceu:shaped/golden_helmet'})
    event.remove({id:'gtceu:shaped/golden_chestplate'})
    event.remove({id:'gtceu:shaped/golden_leggings'})
    event.remove({id:'gtceu:shaped/golden_boots'})
    event.remove({id:'tfmg:crafting/armor/steel_helmet'})
    event.remove({id:'tfmg:crafting/armor/steel_chestplate'})
    event.remove({id:'tfmg:crafting/armor/steel_leggings'})
    event.remove({id:'tfmg:crafting/armor/steel_boots'})
    event.remove({id:'tfmg:crafting/lithium_block'})
    event.remove({id:'tfmg:crafting/coal_coke_block'})
    event.remove({id:'tfmg:crafting/coal_coke_from_block'})
    event.remove({id:'tfmg:crafting/electric_casing'})
    event.remove({id:'tfmg:crafting/cable_connector'})
    event.remove({id:'vintageimprovements:coiling/nethersteel_wire'})
    event.remove({id:'vintageimprovements:coiling/nethersteel_rod'})
    event.remove({id:'tfmg:cinderblock_from_concrete_stonecutting'})
    event.remove({id:'tfmg:compacting/cinderflourblock'})
    event.remove({id:'gtceu:shaped/casing_coke_bricks'})
    event.remove({id:'tfmg:crafting/cinder_block'})
    event.remove({id:'tfmg:crafting/cinderflour_block'})
    event.remove({id:'minecraft:nether_bricks'})
    event.remove({id:'gtceu:shaped/bronze_primitive_blast_furnace'})
    event.remove({id:'minecraft:beehive'})
    event.remove({id:'productivetrees:sawdust_to_paper_water_bottle'})
    event.remove({id:'productivetrees:sawdust_to_paper'})
    event.remove({id:'experienceobelisk:cognitive_amalgam_smelting'})
    event.remove({id:'experienceobelisk:cognitive_flux'})
    event.remove({id:'experienceobelisk:cognitive_alloy'})
    event.remove({id:'experienceobelisk:cognitive_alloy_from_block'})
    event.remove({id:'experienceobelisk:cognitive_crystal'})
    event.remove({id:'experienceobelisk:cognitive_crystal_from_block'})
    event.remove({id:'experienceobelisk:metamorpher/cognitive_crystal_metamorphosis'})
    event.remove({id:'experienceobelisk:metamorpher/cognitive_alloy_metamorphosis'})
    event.remove({id:'experienceobelisk:cognitive_alloy_block'})
    event.remove({id:'experienceobelisk:cognitive_crystal_block'})
    event.remove({id:'experienceobelisk:cognitive_amalgam_blasting'})
    event.remove({id:'nuclearcraft:plate_basic'})
    event.remove({id:'nuclearcraft:plate_basic2'})
    event.remove({id:'nuclearcraft:plate_advanced'})
    event.remove({id:'nuclearcraft:plate_du'})
    event.remove({id:'nuclearcraft:plate_elite'})
    event.remove({id:'nuclearcraft:plate_extreme'})
    event.remove({id:'nuclearcraft:chassis'})
    event.remove({id:'nuclearcraft:fission_reactor_casing'})
    event.remove({id:'nuclearcraft:fission_reactor_glass'})
    event.remove({id:'enderio:copper_alloy_ingot'})
    event.remove({id:'enderio:copper_alloy_nugget_to_ingot'})
    event.remove({id:'enderio:copper_alloy_block'})
    event.remove({id:'enderio:copper_alloy_nugget'})
    event.remove({id:'enderio:energetic_alloy_ingot'})
    event.remove({id:'enderio:energetic_alloy_nugget_to_ingot'})
    event.remove({id:'enderio:energetic_alloy_block'})
    event.remove({id:'enderio:energetic_alloy_nugget'})
    event.remove({id:'enderio:vibrant_alloy_ingot'})
    event.remove({id:'enderio:vibrant_alloy_nugget_to_ingot'})
    event.remove({id:'enderio:vibrant_alloy_block'})
    event.remove({id:'enderio:vibrant_alloy_nugget'})
    event.remove({id:'enderio:redstone_alloy_ingot'})
    event.remove({id:'enderio:redstone_alloy_nugget_to_ingot'})
    event.remove({id:'enderio:redstone_alloy_block'})
    event.remove({id:'enderio:redstone_alloy_nugget'})
    event.remove({id:'enderio:conductive_alloy_ingot'})
    event.remove({id:'enderio:conductive_alloy_nugget_to_ingot'})
    event.remove({id:'enderio:conductive_alloy_block'})
    event.remove({id:'enderio:conductive_alloy_nugget'})
    event.remove({id:'enderio:pulsating_alloy_ingot'})
    event.remove({id:'enderio:pulsating_alloy_nugget_to_ingot'})
    event.remove({id:'enderio:pulsating_alloy_block'})
    event.remove({id:'enderio:pulsating_alloy_nugget'})
    event.remove({id:'enderio:dark_steel_ingot'})
    event.remove({id:'enderio:dark_steel_nugget_to_ingot'})
    event.remove({id:'enderio:dark_steel_block'})
    event.remove({id:'enderio:dark_steel_nugget'})
    event.remove({id:'enderio:soularium_ingot'})
    event.remove({id:'enderio:soularium_nugget_to_ingot'})
    event.remove({id:'enderio:soularium_block'})
    event.remove({id:'enderio:soularium_nugget'})
    event.remove({id:'enderio:end_steel_ingot'})
    event.remove({id:'enderio:end_steel_nugget_to_ingot'})
    event.remove({id:'enderio:end_steel_block'})
    event.remove({id:'enderio:end_steel_nugget'})
    event.remove({id:'enderio:conduit_binder_composite'})
    event.remove({id:'productivebees:quartz_dust_to_quartz'})
    event.remove({id:'terralith:piston_alt'})
    event.remove({id:'gtceu:arc_furnace/arc_obsidian_block'})
    event.remove({id:'gtceu:assembler/coil_cupronickel'})
    event.remove({id:'gtceu:assembler/coil_kanthal'})
    event.remove({id:'gtceu:assembler/coil_nichrome'})
    event.remove({id:'gtceu:assembler/coil_rtm_alloy'})
    event.remove({id:'gtceu:assembler/coil_hssg'})
    event.remove({id:'gtceu:assembler/coil_naquadah'})
    event.remove({id:'gtceu:assembler/coil_trinium'})
    event.remove({id:'gtceu:assembler/coil_tritanium'})
    event.remove({id:'draconicevolution:components/awakened_draconium_ingot_from_dust'})
    event.remove({id:'nuclearcraft:analyzer'})
    event.remove({id:'nuclearcraft:pump'})
    event.remove({id:'nuclearcraft:leacher'})
    event.remove({id:'nuclearcraft:rock_crusher'})
    event.remove({id:'nuclearcraft:decay_hastener'})
    event.remove({id:'nuclearcraft:electrolyzer'})
    event.remove({id:'nuclearcraft:pressurizer'})
    event.remove({id:'nuclearcraft:melter'})
    event.remove({id:'nuclearcraft:ingot_former'})
    event.remove({id:'nuclearcraft:fuel_reprocessor'})
    event.remove({id:'nuclearcraft:isotope_separator'})
    event.remove({id:'createqol:mixing/shadow_radiance'})
    event.remove({id:'nuclearcraft:assembler'})
    event.remove({id:'nuclearcraft:manufactory'})
    event.remove({id:'nuclearcraft:fluid_infuser'})
    event.remove({id:'gtceu:shaped/solar_panel_ulv'})
    event.remove({id:'gtceu:shaped/solar_panel_lv'})
    event.remove({id:'vintageimprovements:craft/aluminum_rod'})
    event.remove({id:'vintageimprovements:craft/bronze_rod'})
    event.remove({id:'vintageimprovements:craft/cast_iron_rod'})
    event.remove({id:'vintageimprovements:craft/cobalt_rod'})
    event.remove({id:'vintageimprovements:craft/invar_rod'})
    event.remove({id:'vintageimprovements:craft/lead_rod'})
    event.remove({id:'vintageimprovements:craft/manyullyn_rod'})
    event.remove({id:'vintageimprovements:craft/nickel_rod'})
    event.remove({id:'vintageimprovements:craft/osmium_rod'})
    event.remove({id:'vintageimprovements:craft/palladium_rod'})
    event.remove({id:'vintageimprovements:craft/platinum_rod'})
    event.remove({id:'vintageimprovements:craft/rhodium_rod'})
    event.remove({id:'vintageimprovements:craft/rose_gold_rod'})
    event.remove({id:'vintageimprovements:craft/silver_rod'})
    event.remove({id:'vintageimprovements:craft/steel_rod'})
    event.remove({id:'vintageimprovements:craft/tin_rod'})
    event.remove({id:'vintageimprovements:craft/uranium_rod'})
    event.remove({id:'create:crafting/materials/copper_ingot'})
    event.remove({id:'nuclearcraft:actuator'})
    event.remove({id:'nuclearcraft:motor'})
    event.remove({id:'nuclearcraft:servo'})
    event.remove({id:'nuclearcraft:nitrogen_collector'})
    event.remove({id:'nuclearcraft:compact_nitrogen_collector'})
    event.remove({id:'nuclearcraft:lava_collector'})
    event.remove({id:'nuclearcraft:compact_water_collector'})
    event.remove({id:'nuclearcraft:compact_helium_collector'})
    event.remove({id:'nuclearcraft:helium_collector'})
    event.remove({id:'nuclearcraft:water_collector'})
    event.remove({id:'create:crafting/materials/zinc_ingot_from_compacting'})
    event.remove({id:'create:crafting/materials/zinc_block_from_compacting'})
    event.remove({id:'create:crafting/materials/brass_ingot_from_compacting'})
    event.remove({id:'create:crafting/materials/brass_block_from_compacting'})
    event.remove({id:'enderio:conduit_binder_from_smelting'})
    event.remove({id:'enderio:conduit_binder_from_blasting'})
    event.remove({id:'jei:/enderio/alloy_smelting/redstone_alloy_ingot'})
    event.remove({id:'jei:/enderio/alloy_smelting/copper_alloy_ingot'})
    event.remove({id:'enderio:soularium_grinding_ball'})
    event.remove({id:'enderio:conductive_alloy_grinding_ball'})
    event.remove({id:'enderio:pulsating_alloy_grinding_ball'})
    event.remove({id:'enderio:redstone_alloy_grinding_ball'})
    event.remove({id:'enderio:energetic_alloy_grinding_ball'})
    event.remove({id:'enderio:vibrant_alloy_grinding_ball'})
    event.remove({id:'enderio:copper_alloy_grinding_ball'})
    event.remove({id:'enderio:dark_steel_grinding_ball'})
    event.remove({id:'enderio:end_steel_grinding_ball'})
    event.remove({id:'jei:/enderio/smelting/enderio/conduit_binder_from_smelting'})
    event.remove({id:'jei:/createqol/mixing/chromatic_compound'})
    event.remove({id:'enderio:alloy_smelter'})
    event.remove({id:'create:smelting/zinc_ingot_from_raw_ore'})
    event.remove({id:'tfmg:crafting/lead_block'})
    event.remove({id:'tfmg:crafting/lead_from_block'})
    event.remove({id:'caupona:crafting/lead_ingot_from_nugget'})
    event.remove({id:'caupona:crafting/lead_ingot_from_block'})
    event.remove({id:'caupona:crafting/lead_block_from_nugget'})
    event.remove({id:'jei:/ae2/inscriber/calculation_processor_print'})
    event.remove({id:'jei:/ae2/inscriber/engineering_processor_print'})
    event.remove({id:'jei:/ae2/inscriber/logic_processor_print'})
    event.remove({id:'jei:/ae2/inscriber/silicon_print'})
    event.remove({id:'ae2:network/cells/spatial_components'})
    event.remove({id:'ae2:network/cells/spatial_components_0'})
    event.remove({id:'ae2:network/cells/spatial_components_1'})
    event.remove({id:'ae2:network/cells/item_storage_components_cell_1k_part'})
    event.remove({id:'ae2:network/cells/item_storage_components_cell_4k_part'})
    event.remove({id:'ae2:network/cells/item_storage_components_cell_16k_part'})
    event.remove({id:'ae2:network/cells/item_storage_components_cell_64k_part'})
    event.remove({id:'ae2:network/cells/item_storage_components_cell_256k_part'})
    event.remove({id:'ae2:network/parts/panels_semi_dark_monitor'})
    event.remove({id:'ae2:network/parts/terminals_crafting'})
    event.remove({id:'ae2:network/parts/terminals'})
    event.remove({id:'ae2:network/parts/monitors_conversion'})
    event.remove({id:'ae2:network/parts/terminals_pattern_access'})
    event.remove({id:'ae2:network/parts/tunnels_me'})
    event.remove({id:'ae2:network/parts/quartz_fiber_part'})
    event.remove({id:'ae2:network/cables/glass_fluix'})
    event.remove({id:'ae2:network/cables/dense_smart_fluix'})
    event.remove({id:'ae2:network/cables/dense_smart_from_smart'})
    event.remove({id:'ae2:network/cables/dense_covered_fluix'})
    event.remove({id:'ae2:network/cables/covered_fluix'})
    event.remove({id:'ae2:network/cables/smart_fluix'})
    event.remove({id:'ae2:network/blocks/crystal_processing_charger'})
    event.remove({id:'ae2:network/parts/terminals_pattern_encoding'})
    event.remove({id:'jei:/ae2/inscriber/silicon_print'})
    event.remove({id:'jei:/ae2/inscriber/engineering_processor_print'})
    event.remove({id:'jei:/ae2/inscriber/certus_quartz_dust'})
    event.remove({id:'jei:/ae2/inscriber/engineering_processor'})
    event.remove({id:'jei:/ae2/inscriber/ender_dust'})
    event.remove({id:'jei:/ae2/inscriber/calculation_processor'})
    event.remove({id:'jei:/ae2/inscriber/logic_processor'})
    event.remove({id:'jei:/ae2/inscriber/logic_processor_print'})
    event.remove({id:'jei:/ae2/inscriber/silicon_print'})
    event.remove({id:'jei:/ae2/inscriber/fluix_dust'})
    event.remove({id:'jei:/ae2/inscriber/calculation_processor_print'})
    event.remove({id:'jei:/ad_astra_giselle_addon/compat/ae2/inscriber/sky_stone_dust'})
    event.remove({id:'jei:/ae2/inscriber/sky_stone_dust'})
    event.remove({id:'jei:/enderio/alloy_smelting/soularium_ingot'})
    event.remove({id:'jei:/enderio/alloy_smelting/dark_steel_ingot'})
    event.remove({id:'jei:/enderio/alloy_smelting/pulsating_alloy_ingot'})
    event.remove({id:'jei:/enderio/alloy_smelting/conductive_alloy_ingot'})
    event.remove({id:'jei:/enderio/alloy_smelting/redstone_alloy_ingot'})
    event.remove({id:'jei:/enderio/alloy_smelting/vibrant_alloy_ingot'})
    event.remove({id:'jei:/enderio/alloy_smelting/energetic_alloy_ingot'})
    event.remove({id:'jei:/enderio/alloy_smelting/copper_alloy_ingot'})
    event.remove({id:'jei:/enderio/alloy_smelting/end_steel_ingot'})
    event.remove({id:'jei:/ae2/inscriber/fluix_dust'})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({output: '#forge:nuggets/manganese_phosphide'})
    event.remove({output: '#forge:ingots/manganese_phosphide'})
    event.remove({output: '#forge:storage_blocks/manganese_phosphide'})
    event.remove({output: '#forge:dusts/manganese_phosphide'})
    event.remove({output: '#forge:small_dusts/manganese_phosphide'})
    event.remove({output: '#forge:tiny_dusts/manganese_phosphide'})
    event.remove({output: 'gtceu:manganese_phosphide'})
    event.remove({output: 'gtceu:molten_manganese_phosphide'})
    event.remove({output: 'gtceu:manganese_phosphide_bucket'})
    event.remove({output: 'gtceu:molten_manganese_phosphide_bucket'})
    event.remove({output: 'gtceu:manganese_phosphide_bucket_single_wire'})
    event.remove({output: 'gtceu:manganese_phosphide_bucket_double_wire'})
    event.remove({output: 'gtceu:manganese_phosphide_bucket_quadruple_wire'})
    event.remove({output: 'gtceu:manganese_phosphide_bucket_octal_wire'})
    event.remove({output: 'gtceu:manganese_phosphide_bucket_hex_wire'})
    event.remove({output: 'nuclearcraft:ferroboron_ingot'})
    event.remove({type: 'framedblocks:framing_saw'})
    event.remove({type: 'productivebees:centrifuge'})
    event.remove({type: 'create:pressing'})
    event.remove({type: 'vintageimprovements:craft'})
    event.remove({type: 'nuclearcraft:decay_hastener'})
    event.remove({type: 'nuclearcraft:fuel_reprocessor'})
    event.remove({type: 'nuclearcraft:isotope_separator'})
    event.remove({type: 'nuclearcraft:rock_crusher'})
    event.remove({type: 'nuclearcraft:electrolyzer'})
    event.remove({type: 'nuclearcraft:pressurizer'})
    event.remove({type: 'nuclearcraft:manufactory'})
    event.remove({type: 'nuclearcraft:melter'})
    event.remove({type: 'nuclearcraft:ingot_former'})
    event.remove({type: 'nuclearcraft:leacher'})
    event.remove({type: 'nuclearcraft:pump'})
    event.remove({type: 'nuclearcraft:analyzer'})
    event.remove({type: 'nuclearcraft:assembler'})
    event.remove({type: 'nuclearcraft:fluid_infuser'})
    event.remove({type: 'jei:/enderio/smelting'})
    event.remove({type: 'jei:/enderio/smelting'})
    //event.remove({type: ''})
    //event.remove({type: ''})
    //event.remove({type: ''})
    //event.remove({type: ''})
    //event.remove({type: ''})
    //event.remove({type: ''})
    //event.remove({type: ''})
    event.remove({mod: 'antiblocksrechiseled'})
    event.remove({mod: 'createmetallurgy'})
    event.remove({input: 'create:crushed_raw_aluminum'})

//Productive Trees
    const shaft = ['oak', 'spruce', 'birch', 'jungle', 'acacia', 'dark_oak', 'mangrove', 'cherry', 'crimson', 'warped', 'glass', 'bamboo']

    const beemixer = ['honeycomb_experience', 'honeycomb_neutronium', 'honeycomb_slimy', 'honeycomb_sticky_resin_gtceu', 'ae2/honeycomb_silicon', 'gtceu/honeycomb_tetrahedrite', 
    'honeycomb_bone', 'shroom/honeycomb_brown_shroom', 'shroom/honeycomb_crimson', 'gtceu/honeycomb_neodymium', 'shroom/honeycomb_warped', 'gtceu/honeycomb_oilsands', 
    'gtceu/honeycomb_chromite', 'gtceu/honeycomb_tricalcium_phosphate', 'honeycomb_withered', 'gtceu/honeycomb_barite', 'gtceu/honeycomb_scheelite', 'gems/honeycomb_amethyst', 
    'honeycomb_draconic', 'raw_materials/honeycomb_iron', 'gtceu/honeycomb_ilmenite', 'honeycomb_fossilised', 'gtceu/honeycomb_sheldonite', 'honeycomb_prismarine', 
    'gems/honeycomb_emerald', 'raw_materials/honeycomb_copper', 'gtceu/honeycomb_bastnasite', 'dusts/honeycomb_redstone', 'shroom/honeycomb_red_shroom', 'gtceu/honeycomb_graphite', 
    'gtceu/honeycomb_tantalite', 'raw_materials/honeycomb_gold', 'gtceu/honeycomb_pyrochlore', 'tetra/honeycomb_scrapped', 'honeycomb_powdery', 'honeycomb_ghostly', 
    'gtceu/honeycomb_bauxite', 'gems/honeycomb_rose_quartz', 'gtceu/honeycomb_stibnite', 'gtceu/honeycomb_sphalerite', 'gems/honeycomb_diamond', 'honeycomb_ender', 
    'alloys/honeycomb_brazen', 'gtceu/honeycomb_lepidolite', 'honeycomb_rotten', 'gtceu/honeycomb_palladium', 'dusts/honeycomb_blazing', 'honeycomb_cheese', 
    'dusts/honeycomb_glowing', 'gtceu/honeycomb_naquadah', 'gems/honeycomb_quartz', 'gtceu/honeycomb_galena', 'raw_materials/honeycomb_zinc', 'raw_materials/honeycomb_netherite', 
    'honeycomb_sculk', 'gems/honeycomb_lapis', 'gtceu/honeycomb_realgar', 'honeycomb_obsidian', 'gtceu/honeycomb_cobaltite', 'honeycomb_frosty', 'gtceu/honeycomb_vanadium_magnetite', 
    'ae2/honeycomb_spacial', 'gtceu/honeycomb_pyrolusite', 'honeycomb_magmatic', 'gtceu/honeycomb_molybdenum', 'gtceu/honeycomb_tungstate', 'honeycomb_silky', 
    'gtceu/honeycomb_electrotine', 'honeycomb_flux']

    const createcoiling = ['silver', 'vanadium', 'rose_gold', 'cobalt', 'platinum', 'uranium', 'palladium', 'invar', 'osmium', 'aluminum', 'zinc', 'lead', 'tin', 'rhodium', 
    'netherite', 'cast_iron', 'nickel', 'bronze', 'electrum', 'andesite', 'shadow_steel', 'refined_radiance', ]

    const frames = ['steel', 'aluminum', 'cast_iron', 'lead', 'nickel', 'copper', 'zinc', 'brass']

    const tfmgtool = ['steel', 'aluminum', 'lead']

    //['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ]

    function removals(output){
        event.remove({id: output})
    }
    shaft.forEach( (base) => {
        let id = 'createcasing:crafting/shafts/' + base + '_shaft'
        removals(id)
    })
    beemixer.forEach( (base) => {
        let id = 'productivebees:create/mixing/' + base
        removals(id)
    })
    createcoiling.forEach( (base) => {
        let id = 'vintageimprovements:coiling/' + base + '_rod'
        let ida = 'vintageimprovements:coiling/' + base + '_wire'
        removals(id)
        removals(ida)
    })
    frames.forEach( (base) => {
        let id = 'tfmg:stonecutting/' + base + '_truss'
        removals(id)
    })
    frames.forEach( (base) => {
        let id = 'tfmg:' + base + '_truss_from_ingots_' + base + '_stonecutting'
        removals(id)
    })
    tfmgtool.forEach( (base) => {
        let ida = 'tfmg:crafting/tools/' + base + '_axe'
        let idb = 'tfmg:crafting/tools/' + base + '_hoe'
        let idc = 'tfmg:crafting/tools/' + base + '_shovel'
        let idd = 'tfmg:crafting/tools/' + base + '_pickaxe'
        let ide = 'tfmg:crafting/tools/' + base + '_sword'
        removals(ida)
        removals(idb)
        removals(idc)
        removals(idd)
        removals(ide)
    })
    const nukenug = ['magnesium', 'aluminum', 'lithium', 'thorium', 'beryllium', 'zirconium', 'boron']
    nukenug.forEach( (base) => {
        event.remove({id:'nuclearcraft:' + base +'_nugget'})
        event.remove({id:'nuclearcraft:' + base +'_block'})
    })
    const nc_stuff = ['manganese_oxide', 'niobium_tin', 'lithium', 'yttrium', 'thorium', 'palladium', 'beryllium', 'silicon_carbide', 'extreme', 'tungsten_carbide', 
        'stainless_steel', 'magnesium', 'sodium', 'niobium_titanium', 'tough_alloy', 'potassium', 'ferroboron', 'titanium', 'aluminum', 'manganese', 'hard_carbon', 'niobium', 
        'zirconium', 'chromium', 'calcium', 'strontium', 'lithium_manganese_dioxide', 'osmiridium', 'hsla_steel', 'nichrome', 'boron', 'magnesium_diboride', 'hafnium', 
        'thermoconducting', 'zircaloy', 'graphite', 'platinum', 'tungsten', 'zirconium_molybdenum', 'tin', 'zinc', 'carbon_manganese', 'shibuichi', 'bronze', 'tin_silver', 
        'pyrolitic_carbon', 'manganese_dioxide', 'silver', 'uranium', 'super_alloy', 'cobalt', 'sic_sic_cmc', 'electrum', 'osmium', 'lead', 'lead_platinum', 'steel', 
        'boron_arsenide', 'carobbiite', 'villiaumite', 'fluorite', 'rhodochrosite', 'boron_nitride', 'barium', 'germanium', 'molybdenum', 'borax', 'potassium_hydroxide', 
        'iodine', 'neodymium', 'sodium_hydroxide', 'samarium', 'arsenic', 'potassium_iodide', 'bismuth', 'iron', 'copper', 'netherite']
    nc_stuff.forEach( (base) => {
        event.remove({id:'minecraft:nuclearcraft_' + base + '_dust'})
        event.remove({id:'minecraft:nuclearcraft_' + base + '_plate'})
        event.remove({id:'minecraft:nuclearcraft_' + base + '_raw'})
        event.remove({id:'minecraft:nuclearcraft_' + base + '_ore'})
        event.remove({id:'minecraft:' + base + '_from_nugget'})
        event.remove({id:'minecraft:' + base + '_from_block'})
        event.remove({id:'nuclearcraft:blast_' + base + '_dust'})
        event.remove({id:'nuclearcraft:blast_' + base + '_raw'})
        event.remove({id:'nuclearcraft:blast_' + base + '_ore'})
        event.remove({id:'nuclearcraft:' + base + '_block'})
        event.remove({id:'nuclearcraft:' + base + '_nugget'})
    })
})
