ServerEvents.recipes(event => {
    event.remove({mod: 'ae2', output: 'ae2:inscriber'})
    event.remove({mod: 'expatternprovider', output: 'expatternprovider:ex_inscriber'})
    event.remove({mod: 'create', output: 'create:propeller'})
    event.remove({mod: 'create', output: 'create:whisk'})
    event.remove({mod: 'create', output: 'create:copper_casing'})
    event.remove({mod: 'create', output: 'create:brass_casing'})
    event.remove({mod: 'create', output: 'create:andesite_casing'})
    event.remove({mod: 'create', output: 'create:shaft'})
    event.remove({mod: 'create', output: 'create:belt_connector'})
    event.remove({mod: 'create', output: 'create:large_cogwheel'})
    event.remove({mod: 'create', output: 'create:cogwheel'})
    event.remove({mod: 'create', output: 'create:windmill_bearing'})
    event.remove({mod: 'create', output: 'create:basin'})
    event.remove({mod: 'create', output: 'create:encased_fan'})
    event.remove({mod: 'create', output: 'create:water_wheel'})
    event.remove({mod: 'create', output: 'create:large_water_wheel'})
    event.remove({mod: 'create', output: 'create:mechanical_press'})
    event.remove({mod: 'create', output: 'create:fluid_tank'})
    event.remove({mod: 'create', output: 'create:rose_quartz'})
    event.remove({mod: 'create', output: 'precision_mechanism'})
    event.remove({mod: 'create', output: 'brass_ingot'})
    event.remove({mod: 'create', output: 'obsidian_plate'})
    event.remove({mod: 'create', output: 'mechanical_crafter'})
    event.remove({mod: 'create', output:'#minecraft:planks'})
    event.remove({mod: 'create', output:'create:goggles'})
    event.remove({mod: 'create', output: 'create:mechanical_pump'})
    event.remove({mod: 'create', output: 'create:mechanical_saw'})
    event.remove({mod: 'create', output: 'create:deployer'})
    event.remove({mod: 'createcasing', output: 'createcasing:industrial_press'})
    event.remove({mod: 'createcasing', output: 'createcasing:brass_press'})
    event.remove({mod: 'createcasing', output: 'createcasing:copper_press'})
    event.remove({mod: 'createcasing', output: 'createcasing:railway_press'})
    event.remove({mod: 'createcasing', output: 'createcasing:creative_press'})
    event.remove({mod: 'create', output: 'create:mechanical_mixer'})
    event.remove({mod: 'createcasing', output: 'createcasing:industrial_iron_mixer'})
    event.remove({mod: 'createcasing', output: 'createcasing:brass_mixer'})
    event.remove({mod: 'createcasing', output: 'createcasing:copper_mixer'})
    event.remove({mod: 'createcasing', output: 'createcasing:railway_mixer'})
    event.remove({mod: 'createcasing', output: 'createcasing:creative_mixer'})
    event.remove({mod: 'create_new_age', output: 'create_new_age:generator_coil'})
    event.remove({mod: 'tfmg', output: 'tfmg:cast_iron_ingot'})
    event.remove({mod: 'createdeco', output: 'createdeco:industrial_iron_ingot'})
    event.remove({mod: 'create', output: 'create:andesite_alloy'})
    event.remove({mod: 'tfmg', output: 'tfmg:screw'})
    event.remove({mod: 'tfmg', output: 'tfmg:screwdriver'})
    event.remove({mod: 'tfmg', output: 'tfmg:coke_oven'})
    event.remove({mod: 'tfmg', output: 'tfmg:molten_steel'})
    event.remove({mod: 'tfmg', output: 'tfmg:slag'})
    event.remove({mod: 'tfmg', output: 'tfmg:industrial_pipe'})
    event.remove({mod: 'tfmg', output: 'tfmg:steel_frame'})
    event.remove({mod: 'tfmg', output: 'tfmg:steel_truss'})
    event.remove({mod: 'tfmg', output: 'tfmg:heavy_machine_casing'})
    event.remove({mod: 'tfmg', output: 'tfmg:pumpjack_hammer_head'})
    event.remove({mod: 'tfmg', output: 'tfmg:pumpjack_hammer_part'})
    event.remove({mod: 'tfmg', output: 'tfmg:pumpjack_hammer_connector'})
    event.remove({mod: 'tfmg', output: 'tfmg:pumpjack_crank'})
    event.remove({mod: 'tfmg', output: 'tfmg:pumpjack_base'})
    event.remove({mod: 'tfmg', output: 'tfmg:pumpjack_hammer'})
    event.remove({mod: 'tfmg', output: 'tfmg:machine_input'})
    event.remove({mod: 'ironchests', output:'ironchests:iron_chest'})
    event.remove({mod: 'gtceu', output:'gtceu:iv_processing_array'})
    event.remove({mod: 'gtceu', output:'gtceu:luv_processing_array'})
    event.remove({mod: 'gtceu', output:'ae2:printed_silicon'})
    event.remove({mod: 'gtceu', output:'ae2:printed_calculation_processor'})
    event.remove({mod: 'gtceu', output:'ae2:printed_engineering_processor'})
    event.remove({mod: 'gtceu', output:'ae2:printed_logic_processor'})
    event.remove({mod: 'gtceu', output:'ae2:calculation_processor'})//
    event.remove({mod: 'gtceu', output:'ae2:engineering_processor'})//
    event.remove({mod: 'gtceu', output:'ae2:logic_processor'})//
    event.remove({mod: 'create', output: 'ad_astra:cheese'})
    event.remove({mod: 'create', output: 'ad_astra:ice_shard'})
    event.remove({mod: 'create', output: 'ad_astra:raw_calorite'})
    event.remove({mod: 'create', output: 'ad_astra:raw_ostrum'})
    event.remove({mod: 'create', output: 'ad_astra:raw_desh'})
    event.remove({mod: 'create', output: 'create:crushed_raw_iron'})
    event.remove({mod: 'create', output: 'create:crushed_raw_tin'})
    event.remove({mod: 'create', output: 'create:crushed_raw_gold'})
    event.remove({mod: 'create', output: 'create:crushed_raw_silver'})
    event.remove({mod: 'create', output: 'create:crushed_raw_copper'})
    event.remove({mod: 'create', output: 'create:crushed_raw_uranium'})
    event.remove({mod: 'create', output: 'create:crushed_raw_lead'})
    event.remove({mod: 'create', output: 'create:crushed_raw_platinum'})
    event.remove({mod: 'create', output: 'create:crushed_raw_nickel'})
    event.remove({mod: 'create', output: 'create:crushed_raw_aluminum'})
    event.remove({mod: 'create', output: 'create:crushed_raw_osmium'})
    event.remove({mod: 'create', output: 'create:crushed_raw_zinc'})
    event.remove({output: 'gtceu:wrought_iron_nugget', type: 'minecraft:smelting'})
    event.remove({output: 'minecraft:iron_nugget', type: 'minecraft:smelting'})
    event.remove({output: 'minecraft:iron_nugget', type: 'minecraft:blasting'})
    event.remove({output: 'minecraft:gold_nugget', type: 'minecraft:smelting'})
    event.remove({output: 'minecraft:gold_nugget', type: 'minecraft:blasting'})
    event.remove({output: 'gtceu:zircon_dust', type: 'minecraft:smelting'})
    event.remove({output: 'gtceu:zircon_dust', type: 'minecraft:blasting'})
    event.remove({output: 'minecraft:charcoal', type: 'minecraft:smelting'})
    event.remove({output: 'gtceu:steel_ingot', type: 'minecraft:blasting'})
    event.remove({output: 'gtceu:steel_ingot', type: 'minecraft:shaped'})
    event.remove({output: 'gtceu:steel_ingot', type: 'minecraft:shapless'})
    event.remove({output: 'ad_astra:steel_ingot' })
    event.remove({id:'gtceu:shaped/compressed_coke_clay'})
    event.remove({id:'gtceu:shapeless/compressed_clay'})
    event.remove({id:'gtceu:shapeless/dust_bronze'})
    event.remove({id:'gtceu:shapeless/dust_brass'})
    event.remove({id:'gtceu:mixer/mixer/ae2/transform/fluix_crystal'})
    event.remove({id:'gtceu:create_mixer/mixer/ae2/transform/fluix_crystal'})
    event.remove({id:'gtceu:fluid_solidifier/fluid_solidfication/ae2/charged_certus_quartz_crystal'})
    event.remove({id:'gtceu:forming_press/forming_press/ae2/calculation_processor_press'})
    event.remove({id:'gtceu:forming_press/forming_press/ae2/engineering_processor_press'})
    event.remove({id:'gtceu:forming_press/forming_press/ae2/logic_processor_press'})
    event.remove({id:'tfmg:casting_steel'})
    event.remove({id:'ironchests:blank_chest_upgrade'})
    event.remove({id:'ironchests:copper_chest_upgrade'})
    event.remove({id:'ironchests:iron_chest_upgrade'})
    event.remove({id:'ironchests:gold_chest_upgrade'})
    event.remove({id:'ironchests:diamond_chest_upgrade'})
    event.remove({id:'ironchests:crystal_chest_upgrade'})
    event.remove({id:'ironchests:obsidian_chest_upgrade'})
    event.remove({id:'ironchests:copper_barrel'})
    event.remove({id:'ironchests:iron_barrel'})
    event.remove({id:'ironchests:gold_barrel'})
    event.remove({id:'ironchests:diamond_barrel'})
    event.remove({id:'ironchests:crystal_barrel'})
    event.remove({id:'ironchests:obsidian_barrel'})
    event.remove({id:'ironchests:copper_chest'})
    event.remove({id:'ironchests:iron_chest'})
    event.remove({id:'ironchests:gold_chest'})
    event.remove({id:'ironchests:diamond_chest'})
    event.remove({id:'ironchests:crystal_chest'})
    event.remove({id:'ironchests:obsidian_chest'})
    event.remove({id:'ironchests:iron_dolly'})
    event.remove({id:'ironchests:diamond_dolly'})
    event.remove({id:'create:compat/ae2/mixing/fluix_crystal'})
    event.remove({id:'dawnoftimebuilder:mulberry_paper'})
    event.remove({id:'farmersdelight:paper_from_tree_bark'})
    event.remove({id:'pamhc2crops:paper_x2_paper_plants'})
    event.remove({id:'create:crafting/kinetics/fluid_pipe_vertical'})
    event.remove({id:'create:crafting/kinetics/mechanical_crafter'})
    event.remove({id:'create:crafting/kinetics/item_drain'})
    event.remove({id:'create:crafting/kinetics/spout'})
    event.remove({id:'create:crafting/logistics/andesite_funnel'})
    event.remove({id:'create:crafting/logistics/andesite_tunnel'})
    event.remove({id:'create:crafting/logistics/brass_funnel'})
    event.remove({id:'create:crafting/logistics/brass_tunnel'})
    event.remove({id:'create:crafting/kinetics/chute'})
    event.remove({id:'create:crafting/kinetics/smart_chute'})
    event.remove({id:'createlowheated:charcoal_burner'})
    event.remove({id:'create:crafting/kinetics/steam_engine'})
    event.remove({id:'create:crafting/kinetics/empty_blaze_burner'})
    event.remove({id:'pamhc2foodextended:charcoal_coconut_x1'})
    event.remove({id:'productivebees:create/mixing/gtceu/honeycomb_electrotine'})
    event.remove({id:'productivebees:create/mixing/honeycomb_silky'})
    event.remove({id:'productivebees:create/mixing/gtceu/honeycomb_tungstate'})
    event.remove({id:'productivebees:create/mixing/gtceu/honeycomb_molybdenum'})
    event.remove({id:'productivebees:create/mixing/honeycomb_magmatic'})
    event.remove({id:'productivebees:create/mixing/gtceu/honeycomb_pyrolusite'})
    event.remove({id:'productivebees:create/mixing/ae2/honeycomb_spacial'})
    event.remove({id:'productivebees:create/mixing/gtceu/honeycomb_vanadium_magnetite'})
    event.remove({id:'productivebees:create/mixing/honeycomb_frosty'})
    event.remove({id:'productivebees:create/mixing/gtceu/honeycomb_cobaltite'})
    event.remove({id:'productivebees:create/mixing/honeycomb_obsidian'})
    event.remove({id:'productivebees:create/mixing/gtceu/honeycomb_realgar'})
    event.remove({id:'productivebees:create/mixing/gems/honeycomb_lapis'})
    event.remove({id:'productivebees:create/mixing/honeycomb_sculk'})
    event.remove({id:'productivebees:create/mixing/raw_materials/honeycomb_netherite'})
    event.remove({id:'productivebees:create/mixing/raw_materials/honeycomb_zinc'})
    event.remove({id:'productivebees:create/mixing/gtceu/honeycomb_galena'})
    event.remove({id:'productivebees:create/mixing/gems/honeycomb_quartz'})
    event.remove({id:'productivebees:create/mixing/gtceu/honeycomb_naquadah'})
    event.remove({id:'productivebees:create/mixing/dusts/honeycomb_glowing'})
    event.remove({id:'productivebees:create/mixing/honeycomb_cheese'})
    event.remove({id:'productivebees:create/mixing/dusts/honeycomb_blazing'})
    event.remove({id:'productivebees:create/mixing/gtceu/honeycomb_palladium'})
    event.remove({id:'productivebees:create/mixing/honeycomb_rotten'})
    event.remove({id:'productivebees:create/mixing/gtceu/honeycomb_lepidolite'})
    event.remove({id:'productivebees:create/mixing/alloys/honeycomb_brazen'})
    event.remove({id:'productivebees:create/mixing/honeycomb_ender'})
    event.remove({id:'productivebees:create/mixing/gems/honeycomb_diamond'})
    event.remove({id:'productivebees:create/mixing/gtceu/honeycomb_sphalerite'})
    event.remove({id:'productivebees:create/mixing/gtceu/honeycomb_stibnite'})
    event.remove({id:'productivebees:create/mixing/gems/honeycomb_rose_quartz'})
    event.remove({id:'productivebees:create/mixing/gtceu/honeycomb_bauxite'})
    event.remove({id:'productivebees:create/mixing/honeycomb_ghostly'})
    event.remove({id:'productivebees:create/mixing/honeycomb_powdery'})
    event.remove({id:'productivebees:create/mixing/tetra/honeycomb_scrapped'})
    event.remove({id:'productivebees:create/mixing/gtceu/honeycomb_pyrochlore'})
    event.remove({id:'productivebees:create/mixing/raw_materials/honeycomb_gold'})
    event.remove({id:'productivebees:create/mixing/gtceu/honeycomb_tantalite'})
    event.remove({id:'productivebees:create/mixing/gtceu/honeycomb_graphite'})
    event.remove({id:'productivebees:create/mixing/shroom/honeycomb_red_shroom'})
    event.remove({id:'productivebees:create/mixing/dusts/honeycomb_redstone'})
    event.remove({id:'productivebees:create/mixing/gtceu/honeycomb_bastnasite'})
    event.remove({id:'productivebees:create/mixing/raw_materials/honeycomb_copper'})
    event.remove({id:'productivebees:create/mixing/gems/honeycomb_emerald'})
    event.remove({id:'productivebees:create/mixing/honeycomb_prismarine'})
    event.remove({id:'productivebees:create/mixing/gtceu/honeycomb_sheldonite'})
    event.remove({id:'productivebees:create/mixing/honeycomb_fossilised'})
    event.remove({id:'productivebees:create/mixing/gtceu/honeycomb_ilmenite'})
    event.remove({id:'productivebees:create/mixing/raw_materials/honeycomb_iron'})
    event.remove({id:'productivebees:create/mixing/honeycomb_draconic'})
    event.remove({id:'productivebees:create/mixing/gems/honeycomb_amethyst'})
    event.remove({id:'productivebees:create/mixing/gtceu/honeycomb_scheelite'})
    event.remove({id:'productivebees:create/mixing/gtceu/honeycomb_barite'})
    event.remove({id:'productivebees:create/mixing/honeycomb_withered'})
    event.remove({id:'productivebees:create/mixing/gtceu/honeycomb_tricalcium_phosphate'})
    event.remove({id:'productivebees:create/mixing/gtceu/honeycomb_chromite'})
    event.remove({id:'productivebees:create/mixing/gtceu/honeycomb_oilsands'})
    event.remove({id:'productivebees:create/mixing/shroom/honeycomb_warped'})
    event.remove({id:'productivebees:create/mixing/gtceu/honeycomb_neodymium'})
    event.remove({id:'productivebees:create/mixing/shroom/honeycomb_crimson'})
    event.remove({id:'productivebees:create/mixing/shroom/honeycomb_brown_shroom'})
    event.remove({id:'productivebees:create/mixing/honeycomb_bone'})
    event.remove({id:'productivebees:create/mixing/gtceu/honeycomb_tetrahedrite'})
    event.remove({id:'productivebees:create/mixing/ae2/honeycomb_silicon'})
    event.remove({id:'productivebees:create/mixing/materials/honeycomb_sticky_resin_gtceu'})
    event.remove({id:'productivebees:create/mixing/honeycomb_slimy'})
    event.remove({id:'productivebees:create/mixing/honeycomb_neutronium'})
    event.remove({id:'productivebees:create/mixing/honeycomb_experience'})
    event.remove({id:'vintageimprovements:craft/belt_grinder'})
    event.remove({id:'vintageimprovements:craft/spring_coiling_machine'})
    event.remove({id:'vintageimprovements:coiling/brass_ingot'})
    event.remove({id:'vintageimprovements:coiling/calorite_wire'})
    event.remove({id:'vintageimprovements:coiling/calorite_rod'})
    event.remove({id:'vintageimprovements:coiling/copper_plate'})
    event.remove({id:'vintageimprovements:coiling/steel_wire'})
    event.remove({id:'vintageimprovements:coiling/desh_rod'})
    event.remove({id:'vintageimprovements:coiling/iron_plate'})
    event.remove({id:'vintageimprovements:coiling/golden_plate'})
    event.remove({id:'vintageimprovements:coiling/desh_wire'})
    event.remove({id:'vintageimprovements:coiling/ostrum_wire'})
    event.remove({id:'vintageimprovements:coiling/brass_wire'})
    event.remove({id:'vintageimprovements:coiling/ostrum_rod'})
    event.remove({id:'vintageimprovements:coiling/copper_ingot'})
    event.remove({id:'vintageimprovements:coiling/iron_ingot'})
    event.remove({id:'vintageimprovements:coiling/steel_rod'})
    event.remove({id:'vintageimprovements:coiling/golden_ingot'})
    event.remove({id:'vintageimprovements:craft/vanadium_nuggets_to_ingot'})
    event.remove({id:'vintageimprovements:craft/vanadium_block_to_ingots'})
    event.remove({id:'vintageimprovements:craft/vanadium_ingots_to_block'})
    event.remove({id:'vintageimprovements:craft/sulfur_items_to_block'})
    event.remove({id:'vintageimprovements:craft/sulfur_nuggets_to_item'})
    event.remove({id:'vintageimprovements:craft/sulfur_block_to_items'})
    event.remove({id:'vintageimprovements:craft/sulfur_item_to_nuggets'})
    event.remove({id:'vintageimprovements:crushing/scoria_recycling'})
    event.remove({id:'vintageimprovements:crushing/scoria'})
    event.remove({id:'gtceu:shaped/rechiseledcreate/mechanical_chisel'})
    event.remove({id:'gtceu:shaped/steel_bricks_hull'})
    event.remove({id:'gtceu:shaped/steel_hull'})
    event.remove({id:'gtceu:shaped/bronze_bricks_hull'})
    event.remove({id:'gtceu:shaped/bronze_hull'})
    event.remove({id:'gtceu:shaped/steam_boiler_coal_bronze'})
    event.remove({id:'gtceu:shaped/steam_boiler_lava_bronze'})
    event.remove({id:'gtceu:shaped/steam_boiler_solar_bronze'})
    event.remove({id:'gtceu:shaped/steam_boiler_coal_steel'})
    event.remove({id:'gtceu:shaped/steam_boiler_lava_steel'})
    event.remove({id:'gtceu:shaped/steam_boiler_solar_steel'})
    event.remove({id:'create:mixing/brass_ingot'})
    event.remove({id:'create:crafting/kinetics/rope_pulley'})
    event.remove({id:'create:crafting/kinetics/mechanical_drill'})
    event.remove({id:'sliceanddice:slicer'})
    event.remove({id:'create:crafting/kinetics/mechanical_roller'})
    event.remove({id:'create:crafting/kinetics/mechanical_piston'})
    event.remove({id:'create:crafting/kinetics/millstone'})
    event.remove({id:'create:crafting/kinetics/cuckoo_clock'})
    event.remove({id:'create:crafting/kinetics/mechanical_bearing'})
    event.remove({id:'create:crafting/kinetics/speedometer'})
    event.remove({id:'create:crafting/kinetics/gantry_carriage'})
    event.remove({id:'vintageimprovements:mechanical_crafting/helve_hammer'})
    event.remove({id:'gtceu:shapeless/rubber_wood_planks'})
    event.remove({id:'tfmg:sequenced_assembly/heavy_plate'})
    event.remove({id:'createqol:item_application/botanist_saw_using_deployer'})
    event.remove({id:'createqol:item_application/glassblower_saw_using_deployer'})
    event.remove({id:'createqol:item_application/loom_saw_using_deployer'})
    event.remove({id:'createqol:item_application/loom_saw_using_deployer'})
    event.remove({id:'createqol:item_application/tinkering_saw_using_deployer'})
    event.remove({id:'createdeco:industrial_iron_nugget_from_industrial_iron_ingot'})
    event.remove({id:'createdeco:netherite_nugget_from_netherite_ingot'})
    event.remove({id:'gtceu:assembly_line/wetware_mainframe_uhv'})
    event.remove({id:'gtceu:assembly_line/wetware_super_computer_uv'})
    event.remove({id:'gtceu:assembly_line/crystal_mainframe_uv'})
    event.remove({id:'gtceu:implosion_compressor/implode_dust_magneto_resonatic__tnt'})
    event.remove({id:'tfmg:crushing/lignite'})
    event.remove({id:'etched:blank_music_disc'})
    event.remove({id:'create:milling/charcoal'})
    event.remove({id:'create:milling/coal'})
    event.remove({id:'create:milling/andesite'})
    event.remove({id:'create:milling/clay'})
    event.remove({id:'minecraft:bread'})
    event.remove({id:'pamhc2crops:bread_grain'})
    event.remove({id:'vintagedelight:oat_bread'})
    event.remove({id:'vintagedelight:oat_dough_from_eggs'})
    event.remove({id:'vintagedelight:oat_dough_from_water'})
    event.remove({id:'create:crafting/appliances/dough'})
    event.remove({id:'create_central_kitchen:crafting/dough_4'})
    event.remove({id:'create_central_kitchen:crafting/dough_3'})
    event.remove({id:'create_central_kitchen:crafting/dough_2'})
    event.remove({id:'create_central_kitchen:crafting/dough_1'})
    event.remove({id:'farmersdelight:wheat_dough_from_water'})
    event.remove({id:'farmersdelight:wheat_dough_from_eggs'})
    event.remove({id:'create:mixing/dough_by_mixing'})
    event.remove({id:'pamhc2foodcore:bread_dough'})
    event.remove({id:'vintagedelight:cutting/oat_cutting'})
    event.remove({id:'vintagedelight:cutting/oat_cutting_using_deployer'})
    event.remove({id:'create:crafting/kinetics/fluid_pipe'})
    event.remove({id:'createlowheated:basic_burner'})
    event.remove({id:'ad_astra:iron_rod'})
    event.remove({id:'ad_astra:steel_rod'})
    event.remove({id:'ad_astra:photovoltaic_etrium_cell'})
    event.remove({id:'gtceu:extruder/extrude_wood_ingot_to_small_gear'})
    event.remove({id:'gtceu:alloy_smelter/alloy_smelt_wood_ingot_to_small_gear'})
    event.remove({id:'gtceu:shaped/treated_wood_planks'})
    event.remove({id:'gtceu:shaped/good_circuit_board'})
    event.remove({id:'gtceu:shaped/electronic_circuit_mv'})
    event.remove({id:'gtceu:shaped/electronic_circuit_lv'})
    event.remove({id:'gtceu:shaped/resistor_wire'})
    event.remove({id:'gtceu:shaped/resistor_wire_fine_charcoal'})
    event.remove({id:'gtceu:shaped/resistor_wire_carbon'})
    event.remove({id:'gtceu:shaped/resistor_wire_fine_carbon'})
    event.remove({id:'gtceu:shaped/resistor_wire_fine'})
    event.remove({id:'gtceu:shaped/resistor_wire_charcoal'})
    event.remove({id:'gtceu:shaped/vacuum_tube'})
    event.remove({id:'gtceu:shaped/basic_circuit_board'})
    event.remove({id:'tfmg:crafting/casting_spout'})
    event.remove({id:'tfmg:crafting/pipes/cast_iron_pipe_vertical'})
    event.remove({id:'tfmg:crafting/pipes/cast_iron_pipe_horizontal'})
    event.remove({id:'tfmg:crafting/casting_basin'})
    event.remove({id:'tfmg:crafting/pipes/cast_iron_fluid_pump'})
    event.remove({id:'tfmg:casting/steel'})
    event.remove({id:'framedblocks:framed_lever'})
    event.remove({id:'supplementaries:sconce_lever'})
    event.remove({id:'ad_astra:alloying/steel_ingot_from_alloying_iron_ingot_and_coals'})
    event.remove({id:'caupona:crafting/walnut_planks'})
    event.remove({id:'dawnoftimebuilder:charred_spruce_planks'})
    event.remove({id:'dawnoftimebuilder:waxed_oak_planks'})
    event.remove({id:'ad_astra:aeronos_planks'})
    event.remove({id:'ad_astra:strophar_planks'})
    event.remove({id:'ad_astra:glacian_planks'})
    event.remove({id:'ad_astra:compressor'})
    event.remove({id:'ad_astra:compressing/iron_plate_from_compressing_iron_ingot'})
    event.remove({id:'ad_astra:compressing/calorite_plate_from_compressing_calorite_blocks'})
    event.remove({id:'ad_astra:compressing/ostrum_plate_from_compressing_ostrum_blocks'})
    event.remove({id:'ad_astra:compressing/steel_plate_from_compressing_steel_blocks'})
    event.remove({id:'ad_astra:compressing/desh_plate_from_compressing_desh_blocks'})
    event.remove({id:'ad_astra:compressing/desh_plate_from_compressing_desh_ingots'})
    event.remove({id:'ad_astra:compressing/calorite_plate_from_compressing_calorite_ingots'})
    event.remove({id:'ad_astra:compressing/steel_plate_from_compressing_steel_ingots'})
    event.remove({id:'ad_astra:compressing/ostrum_plate_from_compressing_ostrum_ingots'})
    event.remove({id:'ad_astra:compressing/iron_plate_from_compressing_iron_block'})
    event.remove({id:'framedblocks:powered_framing_saw'})
    event.remove({id:'framedblocks:framing_saw'})
    event.remove({id:'minecraft:polished_blackstone_pressure_plate'})
    event.remove({id:'minecraft:polished_blackstone_button'})
    event.remove({id:'gtceu:shaped/biomesoplenty/fir_button'})
    event.remove({id:'gtceu:shaped/biomesoplenty/redwood_button'})
    event.remove({id:'gtceu:shaped/biomesoplenty/mahogany_button'})
    event.remove({id:'gtceu:shaped/biomesoplenty/jacaranda_button'})
    event.remove({id:'gtceu:shaped/biomesoplenty/palm_button'})
    event.remove({id:'gtceu:shaped/biomesoplenty/willow_button'})
    event.remove({id:'gtceu:shaped/biomesoplenty/dead_button'})
    event.remove({id:'gtceu:shaped/biomesoplenty/magic_button'})
    event.remove({id:'gtceu:shaped/biomesoplenty/umbran_button'})
    event.remove({id:'gtceu:shaped/biomesoplenty/hellbark_button'})
    event.remove({id:'framedblocks:framed_button'})
    event.remove({id:'framedblocks:framed_stone_button'})
    event.remove({id:'framedblocks:framed_obsidian_pressure_plate'})
    event.remove({id:'framedblocks:framed_gold_pressure_plate'})
    event.remove({id:'framedblocks:framed_iron_pressure_plate'})
    event.remove({id:'ad_astra:iron_plating_button'})
    event.remove({id:'ad_astra:steel_plating_button'})
    event.remove({id:'ad_astra:desh_plating_button'})
    event.remove({id:'ad_astra:ostrum_plating_button'})
    event.remove({id:'ad_astra:calorite_plating_button'})
    event.remove({id:'ad_astra:glacian_button'})
    event.remove({id:'caupona:crafting/walnut_button'})
    event.remove({id:'caupona:crafting/walnut_pressure_plate'})
    event.remove({id:'minecraft:cherry_pressure_plate'})
    event.remove({id:'minecraft:bamboo_pressure_plate'})
    event.remove({id:'framedblocks:framed_pressure_plate'})
    event.remove({id:'ad_astra:iron_plating_pressure_plate'})
    event.remove({id:'ad_astra:steel_plating_pressure_plate'})
    event.remove({id:'ad_astra:desh_plating_pressure_plate'})
    event.remove({id:'ad_astra:ostrum_plating_pressure_plate'})
    event.remove({id:'ad_astra:calorite_plating_pressure_plate'})
    event.remove({id:'ad_astra:glacian_pressure_plate'})
    event.remove({id:'framedblocks:framed_stone_pressure_plate'})
    event.remove({id:'minecraft:polished_blackstone_pressure_plate'})
    event.remove({id:'apotheosis:torch'})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({id:''})
    event.remove({output: '#forge:nuggets/manganese_phosphide'})
    event.remove({output: '#forge:ingots/manganese_phosphide'})
    event.remove({output: '#forge:storage_blocks/manganese_phosphide'})
    event.remove({output: '#forge:dusts/manganese_phosphide'})
    event.remove({output: '#forge:small_dusts/manganese_phosphide'})
    event.remove({output: '#forge:tiny_dusts/manganese_phosphide'})
    event.remove({output: 'gtceu:manganese_phosphide'})
    event.remove({output: 'gtceu:molten_manganese_phosphide'})
    event.remove({output: 'gtceu:manganese_phosphide_bucket'})
    event.remove({output: 'gtceu:molten_manganese_phosphide_bucket'})
    event.remove({output: 'gtceu:manganese_phosphide_bucket_single_wire'})
    event.remove({output: 'gtceu:manganese_phosphide_bucket_double_wire'})
    event.remove({output: 'gtceu:manganese_phosphide_bucket_quadruple_wire'})
    event.remove({output: 'gtceu:manganese_phosphide_bucket_octal_wire'})
    event.remove({output: 'gtceu:manganese_phosphide_bucket_hex_wire'})
    event.remove({type: 'framedblocks:framing_saw'})
    event.remove({type: 'productivebees:centrifuge'})
    event.remove({type: 'create:pressing'})
    event.remove({mod: 'antiblocksrechiseled'})
})