ServerEvents.tags('item', event => {
//Circuits
    event.add('gtceu:circuits/ulv', 'kubejs:ulv_magneto_resonance_circuit')
    event.add('gtceu:circuits/lv', 'kubejs:lv_magneto_resonance_circuit')
    event.add('gtceu:circuits/mv', 'kubejs:mv_magneto_resonance_circuit')
    event.add('gtceu:circuits/hv', 'kubejs:hv_magneto_resonance_circuit')
    event.add('gtceu:circuits/ev', 'kubejs:ev_magneto_resonance_circuit')
    event.add('gtceu:circuits/iv', 'kubejs:iv_magneto_resonance_circuit')
    event.add('gtceu:circuits/luv', 'kubejs:luv_magneto_resonance_circuit')

    event.add('gtceu:circuits/zpm', 'kubejs:zpm_magneto_resonance_circuit')
    event.add('gtceu:circuits/zpm', 'kubejs:fungal_processor')

    event.add('gtceu:circuits/uv', 'kubejs:uv_magneto_resonance_circuit')
    event.add('gtceu:circuits/uv', 'kubejs:optical_processor')
    event.add('gtceu:circuits/uv', 'kubejs:fungal_processor_assembly')

    event.add('gtceu:circuits/uhv', 'kubejs:uhv_magneto_resonance_circuit')
    event.add('gtceu:circuits/uhv', 'kubejs:fungal_processor_computer')
    event.add('gtceu:circuits/uhv', 'kubejs:optical_processor_assembly')
    event.add('gtceu:circuits/uhv', 'kubejs:deep_space_processor')

    event.add('forge:circuits/uev', 'kubejs:uev_magneto_resonance_circuit')
    event.add('forge:circuits/uev', 'kubejs:fungal_processor_mainframe')
    event.add('forge:circuits/uev', 'kubejs:optical_processor_computer')
    event.add('forge:circuits/uev', 'kubejs:deep_space_processor_assembly')
    event.add('forge:circuits/uev', 'kubejs:singularity_processor')

    event.add('forge:circuits/uiv', 'kubejs:optical_processor_mainframe')
    event.add('forge:circuits/uiv', 'kubejs:deep_space_processor_computer')
    event.add('forge:circuits/uiv', 'kubejs:singularity_processor_assembly')
    event.add('forge:circuits/uiv', 'kubejs:4d_processor')

    event.add('forge:circuits/uxv', 'kubejs:deep_space_processor_mainframe')
    event.add('forge:circuits/uxv', 'kubejs:singularity_processor_computer')
    event.add('forge:circuits/uxv', 'kubejs:4d_processor_assembly')

    event.add('forge:circuits/opv', 'kubejs:singularity_processor_mainframe')
    event.add('forge:circuits/opv', 'kubejs:4d_processor_computer')

    event.add('forge:circuits/max', 'kubejs:4d_processor_mainframe')
//Lenses
    event.add('forge:lenses/red', 'gtceu:almandine_lens')
    event.add('forge:lenses/red', 'gtceu:cinnabar_lens')
    event.add('forge:lenses/red', 'gtceu:rutile_lens')
    event.add('forge:lenses/red', 'gtceu:pyrope_lens')
    event.add('forge:lenses/red', 'gtceu:realgar_lens')
    event.add('forge:lenses/red', 'gtceu:red_garnet_lens')
    event.add('forge:lenses/red', 'gtceu:rose_quartz_lens')
    event.add('forge:lenses/yellow', 'gtceu:andradite_lens')
    event.add('forge:lenses/yellow', 'gtceu:topaz_lens')
    event.add('forge:lenses/yellow', 'gtceu:yellow_garnet_lens')
    event.add('forge:lenses/yellow', 'gtceu:monazite_lens')
    event.add('forge:lenses/yellow', 'gtceu:prasiolite_lens')
    event.add('forge:lenses/light_blue', 'gtceu:blue_topaz_lens')
    event.add('forge:lenses/light_blue', 'gtceu:certus_quartz_lens')
    event.add('forge:lenses/light_blue', 'gtceu:enriched_certus_lens')
    event.add('forge:lenses/light_blue', 'gtceu:cubic_zirconium_lens')
    event.add('forge:lenses/black', 'gtceu:coal_lens')
    event.add('forge:lenses/lime', 'gtceu:green_sapphire_lens')
    event.add('forge:lenses/lime', 'gtceu:malachite_lens')
    event.add('forge:lenses/lime', 'gtceu:olivine_lens')
    event.add('forge:lenses/orange', 'gtceu:grossular_lens')
    event.add('forge:lenses/orange', 'gtceu:spessartine_lens')
    event.add('forge:lenses/blue', 'gtceu:lazurite_lens')
    event.add('forge:lenses/blue', 'gtceu:sodalite_lens')
    event.add('forge:lenses/blue', 'gtceu:lapis_lens')
    event.add('forge:lenses/white', 'gtceu:rock_salt_lens')
    event.add('forge:lenses/white', 'gtceu:salt_lens')
    event.add('forge:lenses/white', 'gtceu:nether_quartz_lens')
    event.add('forge:lenses/white', 'gtceu:quartzite_lens')
    event.add('forge:lenses/grey', 'gtceu:coke_lens')
    event.add('forge:lenses/brown', 'gtceu:lignite_lens')
    event.add('forge:lenses/green', 'gtceu:uvarovite_lens')
    event.add('forge:lenses/pink', 'gtceu:opal_lens')
    event.add('forge:lenses/pink', 'gtceu:magneto_resonatic_lens')
    event.add('forge:lenses/purple', 'gtceu:amethyst_lens')
    event.add('forge:lenses/cyan', 'gtceu:apatite_lens')
    event.add('forge:lenses/cyan', 'gtceu:lunite_lens')
//Tools
    event.add('forge:tools/screwdrivers', 'tfmg:screwdriver')
    event.add('createlowheated:burner_starters', 'minecraft:torch')
//Bakelite and Wood
    event.add('forge:small_bakelite', 'gtceu:small_wood_gear')
    event.add('forge:bakelite', 'gtceu:wood_gear')
    event.add('forge:small_bakelite', 'gtceu:small_bakelite_gear')
    event.add('forge:bakelite', 'gtceu:bakelite_gear')
})

ServerEvents.tags('block', event => {
//Ore
    event.add('minecraft:mineable/pickaxe', '#forge:ores_in_ground/sand')
    event.add('minecraft:mineable/pickaxe', '#forge:ores_in_ground/red_sand')
    event.add('minecraft:mineable/pickaxe', '#forge:ores_in_ground/gravel')
    event.add('minecraft:mineable/pickaxe', '#forge:ores_in_ground/moon_stone')
    event.add('minecraft:needs_iron_tool', '#forge:ores_in_ground/moon_stone')
    event.add('minecraft:mineable/pickaxe', '#forge:ores_in_ground/moon_deepslate')
    event.add('minecraft:needs_iron_tool', '#forge:ores_in_ground/moon_deepslate')
    event.add('minecraft:mineable/pickaxe', '#forge:ores_in_ground/mars_stone')
    event.add('minecraft:needs_iron_tool', '#forge:ores_in_ground/mars_stone')
    event.add('minecraft:mineable/pickaxe', '#forge:ores_in_ground/venus_stone')
    event.add('minecraft:needs_iron_tool', '#forge:ores_in_ground/venus_stone')
    event.add('minecraft:mineable/pickaxe', '#forge:ores_in_ground/venus_sandstone')
    event.add('minecraft:needs_iron_tool', '#forge:ores_in_ground/venus_sandstone')
    event.add('minecraft:mineable/pickaxe', '#forge:ores_in_ground/mercury_stone')
    event.add('minecraft:needs_iron_tool', '#forge:ores_in_ground/mercury_stone')
    event.add('minecraft:mineable/pickaxe', '#forge:ores_in_ground/glacio_stone')
    event.add('minecraft:needs_iron_tool', '#forge:ores_in_ground/glacio_stone')
    event.add('minecraft:mineable/pickaxe', '#forge:ores_in_ground/permafrost')
    event.add('minecraft:needs_iron_tool', '#forge:ores_in_ground/permafrost')
})