ServerEvents.recipes(event => {
    function antiblock(id, input, dye, output){
    event.recipes.gtceu.builders_press(id)
        .circuit(0)
        .itemInputs('16x minecraft:glowstone_dust', input)
        .inputFluids('gtceu:construction_foam 4000', dye)
        .itemOutputs(output)
        .EUt(60)
        .duration(400)
    }
    antiblock('wool_white', '24x minecraft:white_wool', 'gtceu:white_dye 1000', '64x antiblocksrechiseled:wool_white')
    antiblock('wool_orange', '24x minecraft:white_wool', 'gtceu:orange_dye 1000', '64x antiblocksrechiseled:wool_orange')
    antiblock('wool_magenta', '24x minecraft:white_wool', 'gtceu:magenta_dye 1000', '64x antiblocksrechiseled:wool_magenta')
    antiblock('wool_light_blue', '24x minecraft:white_wool', 'gtceu:light_blue_dye 1000', '64x antiblocksrechiseled:wool_light_blue')
    antiblock('wool_yellow', '24x minecraft:white_wool', 'gtceu:yellow_dye 1000', '64x antiblocksrechiseled:wool_yellow')
    antiblock('wool_lime', '24x minecraft:white_wool', 'gtceu:lime_dye 1000', '64x antiblocksrechiseled:wool_lime')
    antiblock('wool_pink', '24x minecraft:white_wool', 'gtceu:pink_dye 1000', '64x antiblocksrechiseled:wool_pink')
    antiblock('wool_gray', '24x minecraft:white_wool', 'gtceu:gray_dye 1000', '64x antiblocksrechiseled:wool_gray')
    antiblock('wool_light_gray', '24x minecraft:white_wool', 'gtceu:light_gray_dye 1000', '64x antiblocksrechiseled:wool_light_gray')
    antiblock('wool_cyan', '24x minecraft:white_wool', 'gtceu:cyan_dye 1000', '64x antiblocksrechiseled:wool_cyan')
    antiblock('wool_purple', '24x minecraft:white_wool', 'gtceu:purple_dye 1000', '64x antiblocksrechiseled:wool_purple')
    antiblock('wool_blue', '24x minecraft:white_wool', 'gtceu:blue_dye 1000', '64x antiblocksrechiseled:wool_blue')
    antiblock('wool_brown', '24x minecraft:white_wool', 'gtceu:brown_dye 1000', '64x antiblocksrechiseled:wool_brown')
    antiblock('wool_green', '24x minecraft:white_wool', 'gtceu:green_dye 1000', '64x antiblocksrechiseled:wool_green')
    antiblock('wool_red', '24x minecraft:white_wool', 'gtceu:red_dye 1000', '64x antiblocksrechiseled:wool_red')

    antiblock('bright_white', '16x minecraft:stone', 'gtceu:white_dye 1000', '64x antiblocksrechiseled:bright_white')
    antiblock('bright_orange', '16x minecraft:stone', 'gtceu:orange_dye 1000', '64x antiblocksrechiseled:bright_orange')
    antiblock('bright_magenta', '16x minecraft:stone', 'gtceu:magenta_dye 1000', '64x antiblocksrechiseled:bright_magenta')
    //antiblock('bright_light_blue', '16x minecraft:stone', 'gtceu:light_blue_dye 1000', '64x antiblocksrechiseled:bright_light_blue')
    antiblock('bright_yellow', '16x minecraft:stone', 'gtceu:yellow_dye 1000', '64x antiblocksrechiseled:bright_yellow')
    //antiblock('bright_lime', '16x minecraft:stone', 'gtceu:lime_dye 1000', '64x antiblocksrechiseled:bright_lime')
    //antiblock('bright_pink', '16x minecraft:stone', 'gtceu:pink_dye 1000', '64x antiblocksrechiseled:bright_pink')
    //antiblock('bright_gray', '16x minecraft:stone', 'gtceu:gray_dye 1000', '64x antiblocksrechiseled:bright_gray')
    //antiblock('bright_light_gray', '16x minecraft:stone', 'gtceu:light_gray_dye 1000', '64x antiblocksrechiseled:bright_light_gray')
    antiblock('bright_cyan', '16x minecraft:stone', 'gtceu:cyan_dye 1000', '64x antiblocksrechiseled:bright_cyan')
    //antiblock('bright_purple', '16x minecraft:stone', 'gtceu:purple_dye 1000', '64x antiblocksrechiseled:bright_purple')
    antiblock('bright_blue', '16x minecraft:stone', 'gtceu:blue_dye 1000', '64x antiblocksrechiseled:bright_blue')
    //antiblock('bright_brown', '16x minecraft:stone', 'gtceu:brown_dye 1000', '64x antiblocksrechiseled:bright_brown')
    antiblock('bright_green', '16x minecraft:stone', 'gtceu:green_dye 1000', '64x antiblocksrechiseled:bright_green')
    antiblock('bright_red', '16x minecraft:stone', 'gtceu:red_dye 1000', '64x antiblocksrechiseled:bright_red')
    antiblock('bright_black', '16x minecraft:stone', 'gtceu:black_dye 1000', '64x antiblocksrechiseled:bright_black')

    function antiblockborder(id, input, dye, output){
    event.recipes.gtceu.builders_press(id)
        .circuit(1)
        .itemInputs('16x minecraft:glowstone_dust', input)
        .inputFluids('gtceu:construction_foam 4000', dye)
        .itemOutputs(output)
        .EUt(60)
        .duration(400)
    }
    antiblockborder('wool_white_border', '24x minecraft:white_wool', 'gtceu:white_dye 1000', '64x antiblocksrechiseled:wool_white_border')
    antiblockborder('wool_orange_border', '24x minecraft:white_wool', 'gtceu:orange_dye 1000', '64x antiblocksrechiseled:wool_orange_border')
    antiblockborder('wool_magenta_border', '24x minecraft:white_wool', 'gtceu:magenta_dye 1000', '64x antiblocksrechiseled:wool_magenta_border')
    antiblockborder('wool_light_blue_border', '24x minecraft:white_wool', 'gtceu:light_blue_dye 1000', '64x antiblocksrechiseled:wool_light_blue_border')
    antiblockborder('wool_yellow_border', '24x minecraft:white_wool', 'gtceu:yellow_dye 1000', '64x antiblocksrechiseled:wool_yellow_border')
    antiblockborder('wool_lime_border', '24x minecraft:white_wool', 'gtceu:lime_dye 1000', '64x antiblocksrechiseled:wool_lime_border')
    antiblockborder('wool_pink_border', '24x minecraft:white_wool', 'gtceu:pink_dye 1000', '64x antiblocksrechiseled:wool_pink_border')
    antiblockborder('wool_gray_border', '24x minecraft:white_wool', 'gtceu:gray_dye 1000', '64x antiblocksrechiseled:wool_gray_border')
    antiblockborder('wool_light_gray_border', '24x minecraft:white_wool', 'gtceu:light_gray_dye 1000', '64x antiblocksrechiseled:wool_light_gray_border')
    antiblockborder('wool_cyan_border', '24x minecraft:white_wool', 'gtceu:cyan_dye 1000', '64x antiblocksrechiseled:wool_cyan_border')
    antiblockborder('wool_purple_border', '24x minecraft:white_wool', 'gtceu:purple_dye 1000', '64x antiblocksrechiseled:wool_purple_border')
    antiblockborder('wool_blue_border', '24x minecraft:white_wool', 'gtceu:blue_dye 1000', '64x antiblocksrechiseled:wool_blue_border')
    antiblockborder('wool_brown_border', '24x minecraft:white_wool', 'gtceu:brown_dye 1000', '64x antiblocksrechiseled:wool_brown_border')
    antiblockborder('wool_green_border', '24x minecraft:white_wool', 'gtceu:green_dye 1000', '64x antiblocksrechiseled:wool_green_border')
    antiblockborder('wool_red_border', '24x minecraft:white_wool', 'gtceu:red_dye 1000', '64x antiblocksrechiseled:wool_red_border')

    antiblockborder('bright_white_border', '16x minecraft:stone', 'gtceu:white_dye 1000', '64x antiblocksrechiseled:bright_white_border')
    antiblockborder('bright_orange_border', '16x minecraft:stone', 'gtceu:orange_dye 1000', '64x antiblocksrechiseled:bright_orange_border')
    antiblockborder('bright_magenta_border', '16x minecraft:stone', 'gtceu:magenta_dye 1000', '64x antiblocksrechiseled:bright_magenta_border')
    //antiblockborder('bright_light_blue_border', '16x minecraft:stone', 'gtceu:light_blue_dye 1000', '64x antiblocksrechiseled:bright_light_blue_border')
    antiblockborder('bright_yellow_border', '16x minecraft:stone', 'gtceu:yellow_dye 1000', '64x antiblocksrechiseled:bright_yellow_border')
    //antiblockborder('bright_lime_border', '16x minecraft:stone', 'gtceu:lime_dye 1000', '64x antiblocksrechiseled:bright_lime_border')
    //antiblockborder('bright_pink_border', '16x minecraft:stone', 'gtceu:pink_dye 1000', '64x antiblocksrechiseled:bright_pink_border')
    //antiblockborder('bright_gray_border', '16x minecraft:stone', 'gtceu:gray_dye 1000', '64x antiblocksrechiseled:bright_gray_border')
    //antiblockborder('bright_light_gray_border', '16x minecraft:stone', 'gtceu:light_gray_dye 1000', '64x antiblocksrechiseled:bright_light_gray_border')
    antiblockborder('bright_cyan_border', '16x minecraft:stone', 'gtceu:cyan_dye 1000', '64x antiblocksrechiseled:bright_cyan_border')
    //antiblockborder('bright_purple_border', '16x minecraft:stone', 'gtceu:purple_dye 1000', '64x antiblocksrechiseled:bright_purple_border')
    antiblockborder('bright_blue_border', '16x minecraft:stone', 'gtceu:blue_dye 1000', '64x antiblocksrechiseled:bright_blue_border')
    //antiblockborder('bright_brown_border', '16x minecraft:stone', 'gtceu:brown_dye 1000', '64x antiblocksrechiseled:bright_brown_border')
    antiblockborder('bright_green_border', '16x minecraft:stone', 'gtceu:green_dye 1000', '64x antiblocksrechiseled:bright_green_border')
    antiblockborder('bright_red_border', '16x minecraft:stone', 'gtceu:red_dye 1000', '64x antiblocksrechiseled:bright_red_border')
    antiblockborder('bright_black_border', '16x minecraft:stone', 'gtceu:black_dye 1000', '64x antiblocksrechiseled:bright_black_border')

    function antiblockslab(id, input, dye, output){
    event.recipes.gtceu.builders_press(id)
        .circuit(2)
        .itemInputs('8x minecraft:glowstone_dust', input)
        .inputFluids('gtceu:construction_foam 2000', dye)
        .itemOutputs(output)
        .EUt(60)
        .duration(400)
    }
    antiblockslab('slab_wool_white', '12x minecraft:white_wool', 'gtceu:white_dye 1000', '64x antiblocksrechiseled:slab_white_wool')
    antiblockslab('slab_wool_orange', '12x minecraft:white_wool', 'gtceu:orange_dye 1000', '64x antiblocksrechiseled:slab_orange_wool')
    antiblockslab('slab_wool_magenta', '12x minecraft:white_wool', 'gtceu:magenta_dye 1000', '64x antiblocksrechiseled:slab_magenta_wool')
    antiblockslab('slab_wool_light_blue', '12x minecraft:white_wool', 'gtceu:light_blue_dye 1000', '64x antiblocksrechiseled:slab_light_blue_wool')
    antiblockslab('slab_wool_yellow', '12x minecraft:white_wool', 'gtceu:yellow_dye 1000', '64x antiblocksrechiseled:slab_yellow_wool')
    antiblockslab('slab_wool_lime', '12x minecraft:white_wool', 'gtceu:lime_dye 1000', '64x antiblocksrechiseled:slab_lime_wool')
    antiblockslab('slab_wool_pink', '12x minecraft:white_wool', 'gtceu:pink_dye 1000', '64x antiblocksrechiseled:slab_pink_wool')
    antiblockslab('slab_wool_gray', '12x minecraft:white_wool', 'gtceu:gray_dye 1000', '64x antiblocksrechiseled:slab_gray_wool')
    antiblockslab('slab_wool_light_gray', '12x minecraft:white_wool', 'gtceu:light_gray_dye 1000', '64x antiblocksrechiseled:slab_light_gray_wool')
    antiblockslab('slab_wool_cyan', '12x minecraft:white_wool', 'gtceu:cyan_dye 1000', '64x antiblocksrechiseled:slab_cyan_wool')
    antiblockslab('slab_wool_purple', '12x minecraft:white_wool', 'gtceu:purple_dye 1000', '64x antiblocksrechiseled:slab_purple_wool')
    antiblockslab('slab_wool_blue', '12x minecraft:white_wool', 'gtceu:blue_dye 1000', '64x antiblocksrechiseled:slab_blue_wool')
    antiblockslab('slab_wool_brown', '12x minecraft:white_wool', 'gtceu:brown_dye 1000', '64x antiblocksrechiseled:slab_brown_wool')
    antiblockslab('slab_wool_green', '12x minecraft:white_wool', 'gtceu:green_dye 1000', '64x antiblocksrechiseled:slab_green_wool')
    antiblockslab('slab_wool_red', '12x minecraft:white_wool', 'gtceu:red_dye 1000', '64x antiblocksrechiseled:slab_red_wool')

    antiblockslab('slab_bright_white', '8x minecraft:stone', 'gtceu:white_dye 1000', '64x antiblocksrechiseled:slab_white_bright')
    antiblockslab('slab_bright_orange', '8x minecraft:stone', 'gtceu:orange_dye 1000', '64x antiblocksrechiseled:slab_orange_bright')
    antiblockslab('slab_bright_magenta', '8x minecraft:stone', 'gtceu:magenta_dye 1000', '64x antiblocksrechiseled:slab_magenta_bright')
    //antiblockslab('slab_bright_light_blue', '8x minecraft:stone', 'gtceu:light_blue_dye 1000', '64x antiblocksrechiseled:slab_light_blue_bright')
    antiblockslab('slab_bright_yellow', '8x minecraft:stone', 'gtceu:yellow_dye 1000', '64x antiblocksrechiseled:slab_yellow_bright')
    //antiblockslab('slab_bright_lime', '8x minecraft:stone', 'gtceu:lime_dye 1000', '64x antiblocksrechiseled:slab_lime_bright')
    //antiblockslab('slab_bright_pink', '8x minecraft:stone', 'gtceu:pink_dye 1000', '64x antiblocksrechiseled:slab_pink_bright')
    //antiblockslab('slab_bright_gray', '8x minecraft:stone', 'gtceu:gray_dye 1000', '64x antiblocksrechiseled:slab_gray_bright')
    //antiblockslab('slab_bright_light_gray', '8x minecraft:stone', 'gtceu:light_gray_dye 1000', '64x antiblocksrechiseled:slab_light_gray_bright')
    antiblockslab('slab_bright_cyan', '8x minecraft:stone', 'gtceu:cyan_dye 1000', '64x antiblocksrechiseled:slab_cyan_bright')
    //antiblockslab('slab_bright_purple', '8x minecraft:stone', 'gtceu:purple_dye 1000', '64x antiblocksrechiseled:slab_purple_bright')
    antiblockslab('slab_bright_blue', '8x minecraft:stone', 'gtceu:blue_dye 1000', '64x antiblocksrechiseled:slab_blue_bright')
    //antiblockslab('slab_bright_brown', '8x minecraft:stone', 'gtceu:brown_dye 1000', '64x antiblocksrechiseled:slab_brown_bright')
    antiblockslab('slab_bright_green', '8x minecraft:stone', 'gtceu:green_dye 1000', '64x antiblocksrechiseled:slab_green_bright')
    antiblockslab('slab_bright_red', '8x minecraft:stone', 'gtceu:red_dye 1000', '64x antiblocksrechiseled:slab_red_bright')

    function antiblockstair(id, input, dye, output){
    event.recipes.gtceu.builders_press(id)
        .circuit(3)
        .itemInputs('12x minecraft:glowstone_dust', input)
        .inputFluids('gtceu:construction_foam 3000', dye)
        .itemOutputs(output)
        .EUt(60)
        .duration(400)
    }
    antiblockstair('stair_wool_white', '18x minecraft:white_wool', 'gtceu:white_dye 1000', '64x antiblocksrechiseled:stair_white_wool')
    antiblockstair('stair_wool_orange', '18x minecraft:white_wool', 'gtceu:orange_dye 1000', '64x antiblocksrechiseled:stair_orange_wool')
    antiblockstair('stair_wool_magenta', '18x minecraft:white_wool', 'gtceu:magenta_dye 1000', '64x antiblocksrechiseled:stair_magenta_wool')
    antiblockstair('stair_wool_light_blue', '18x minecraft:white_wool', 'gtceu:light_blue_dye 1000', '64x antiblocksrechiseled:stair_light_blue_wool')
    antiblockstair('stair_wool_yellow', '18x minecraft:white_wool', 'gtceu:yellow_dye 1000', '64x antiblocksrechiseled:stair_yellow_wool')
    antiblockstair('stair_wool_lime', '18x minecraft:white_wool', 'gtceu:lime_dye 1000', '64x antiblocksrechiseled:stair_lime_wool')
    antiblockstair('stair_wool_pink', '18x minecraft:white_wool', 'gtceu:pink_dye 1000', '64x antiblocksrechiseled:stair_pink_wool')
    antiblockstair('stair_wool_gray', '18x minecraft:white_wool', 'gtceu:gray_dye 1000', '64x antiblocksrechiseled:stair_gray_wool')
    antiblockstair('stair_wool_light_gray', '18x minecraft:white_wool', 'gtceu:light_gray_dye 1000', '64x antiblocksrechiseled:stair_light_gray_wool')
    antiblockstair('stair_wool_cyan', '18x minecraft:white_wool', 'gtceu:cyan_dye 1000', '64x antiblocksrechiseled:stair_cyan_wool')
    antiblockstair('stair_wool_purple', '18x minecraft:white_wool', 'gtceu:purple_dye 1000', '64x antiblocksrechiseled:stair_purple_wool')
    antiblockstair('stair_wool_blue', '18x minecraft:white_wool', 'gtceu:blue_dye 1000', '64x antiblocksrechiseled:stair_blue_wool')
    antiblockstair('stair_wool_brown', '18x minecraft:white_wool', 'gtceu:brown_dye 1000', '64x antiblocksrechiseled:stair_brown_wool')
    antiblockstair('stair_wool_green', '18x minecraft:white_wool', 'gtceu:green_dye 1000', '64x antiblocksrechiseled:stair_green_wool')
    antiblockstair('stair_wool_red', '18x minecraft:white_wool', 'gtceu:red_dye 1000', '64x antiblocksrechiseled:stair_red_wool')

    antiblockstair('stair_bright_white', '12x minecraft:stone', 'gtceu:white_dye 1000', '64x antiblocksrechiseled:stair_white_bright')
    antiblockstair('stair_bright_orange', '12x minecraft:stone', 'gtceu:orange_dye 1000', '64x antiblocksrechiseled:stair_orange_bright')
    antiblockstair('stair_bright_magenta', '12x minecraft:stone', 'gtceu:magenta_dye 1000', '64x antiblocksrechiseled:stair_magenta_bright')
    //antiblockstair('stair_bright_light_blue', '12x minecraft:stone', 'gtceu:light_blue_dye 1000', '64x antiblocksrechiseled:stair_light_blue_bright')
    antiblockstair('stair_bright_yellow', '12x minecraft:stone', 'gtceu:yellow_dye 1000', '64x antiblocksrechiseled:stair_yellow_bright')
    //antiblockstair('stair_bright_lime', '12x minecraft:stone', 'gtceu:lime_dye 1000', '64x antiblocksrechiseled:stair_lime_bright')
    //antiblockstair('stair_bright_pink', '12x minecraft:stone', 'gtceu:pink_dye 1000', '64x antiblocksrechiseled:stair_pink_bright')
    //antiblockstair('stair_bright_gray', '12x minecraft:stone', 'gtceu:gray_dye 1000', '64x antiblocksrechiseled:stair_gray_bright')
    //antiblockstair('stair_bright_light_gray', '12x minecraft:stone', 'gtceu:light_gray_dye 1000', '64x antiblocksrechiseled:stair_light_gray_bright')
    antiblockstair('stair_bright_cyan', '12x minecraft:stone', 'gtceu:cyan_dye 1000', '64x antiblocksrechiseled:stair_cyan_bright')
    //antiblockstair('stair_bright_purple', '12x minecraft:stone', 'gtceu:purple_dye 1000', '64x antiblocksrechiseled:stair_purple_bright')
    antiblockstair('stair_bright_blue', '12x minecraft:stone', 'gtceu:blue_dye 1000', '64x antiblocksrechiseled:stair_blue_bright')
    //antiblockstair('stair_bright_brown', '12x minecraft:stone', 'gtceu:brown_dye 1000', '64x antiblocksrechiseled:stair_brown_bright')
    antiblockstair('stair_bright_green', '12x minecraft:stone', 'gtceu:green_dye 1000', '64x antiblocksrechiseled:stair_green_bright')
    antiblockstair('stair_bright_red', '12x minecraft:stone', 'gtceu:red_dye 1000', '64x antiblocksrechiseled:stair_red_bright')
})