ServerEvents.recipes(event => {
    event.recipes.gtceu.mixer('cognitive_flux')
        .itemInputs('gtceu:nether_quartz_dust', 'gtceu:lapis_dust', 'gtceu:quartz_sand_dust')
        .itemOutputs('3x experienceobelisk:cognitive_flux')
        .EUt(lv)
        .duration(min)

    event.recipes.gtceu.forming_press('cognitive_amalgam')
        .itemInputs('experienceobelisk:cognitive_flux')
        .notConsumable('gtceu:ingot_casting_mold')
        .chancedInput('create:experience_nugget', 500, 0)
        .itemOutputs('experienceobelisk:cognitive_amalgam')
        .EUt(lv)
        .duration(min*5)

    event.recipes.gtceu.electric_blast_furnace('cognitive_alloy')
        .itemInputs('4x minecraft:copper_ingot', 'experienceobelisk:cognitive_amalgam')
        .chancedInput('create:experience_nugget', 1000, 1)
        .inputFluids('gtceu:nitrogen')
        .itemOutputs('5x experienceobelisk:cognitive_alloy')
        .chancedFluidOutput('gtceu:experience 50', 10, 1)
        .blastFurnaceTemp(1200)
        .EUt(mv)
        .duration(min*5)

    event.recipes.gtceu.chemical_reactor('cognitive_gem')
        .itemInputs('minecraft:emerald', '4x experienceobelisk:cognitive_amalgam')
        .chancedFluidInput('experienceobelisk:cognitium 144', 500, 0)
        .itemOutputs('5x experienceobelisk:cognitive_crystal')
        .EUt(lv)
        .duration(min*5)

    event.recipes.gtceu.distillery('xp_convert_a')
        .inputFluids('create_enchantment_industry:experience 10')
        .circuit(1)
        .outputFluids('experienceobelisk:cognitium 10')
    event.recipes.gtceu.distillery('xp_convert_b')
        .inputFluids('sophisticatedcore:xp_still 10')
        .circuit(1)
        .outputFluids('experienceobelisk:cognitium 10')
})