ServerEvents.recipes(event => {
//Recipe Replacements
    /*event.replaceInput(
        { input: 'tfmg:screw' },
        'tfmg:screw',
        'gtceu:poor_steel_screw'
        )*/
    event.recipes.gtceu.alloy_smelter('basic_plate')
        .itemInputs('gtceu:graphite_dust', 'gtceu:lead_ingot')
        .itemOutputs('nuclearcraft:plate_basic')
        .duration(min/2)
        .EUt(ev)
    event.recipes.gtceu.electric_blast_furnace('advanced_plate')
        .itemInputs('nuclearcraft:plate_basic', '2x minecraft:redstone', '2x gtceu:tough_alloy_ingot')
        .itemOutputs('nuclearcraft:plate_advanced')
        .blastFurnaceTemp(3500)
        .duration(min/2)
        .EUt(iv)
    event.recipes.gtceu.electric_blast_furnace('du_plate')
        .itemInputs('nuclearcraft:plate_advanced', '4x nuclearcraft:uranium_238', '4x gtceu:sulfur_dust')
        .itemOutputs('nuclearcraft:plate_du')
        .blastFurnaceTemp(4400)
        .duration(min/2)
        .EUt(luv)
    event.recipes.gtceu.electric_blast_furnace('elite_plate')
        .itemInputs('nuclearcraft:plate_du', '4x gtceu:boron_ingot', '4x gtceu:crystal_binder_dust')
        .itemOutputs('nuclearcraft:plate_elite')
        .blastFurnaceTemp(5300)
        .duration(min/2)
        .EUt(zpm)
    event.recipes.gtceu.electric_blast_furnace('extreme_plate')
        .itemInputs('nuclearcraft:plate_elite', '4x gtceu:extreme_ingot', '4x gtceu:hsla_steel_dust')
        .itemOutputs('nuclearcraft:plate_extreme')
        .blastFurnaceTemp(7200)
        .duration(min/2)
        .EUt(uv)

    event.recipes.gtceu.assembler('chassis')
        .circuit(16)
        .itemInputs('4x gtceu:lead_plate', '4x gtceu:steel_plate', 'gtceu:tough_alloy_frame')
        .itemOutputs('nuclearcraft:chassis')
        .duration(min/4)
        .EUt(ev/2)
    event.recipes.gtceu.assembler('fission_casing')
        .circuit(16)
        .itemInputs('4x gtceu:lead_plate', 'nuclearcraft:plate_advanced', 'gtceu:tough_alloy_frame')
        .itemOutputs('2x nuclearcraft:fission_reactor_casing')
        .duration(min/4)
        .EUt(ev)
    event.recipes.gtceu.forming_press('fission_glass')
        .itemInputs('nuclearcraft:fission_reactor_casing', '4x gtceu:laminated_glass')
        .itemOutputs('2x nuclearcraft:fission_reactor_glass')
        .duration(min/4)
        .EUt(ev)

//Heat Sinks
    function heatsink(id, input) {
        event.recipes.gtceu.canner('kubejs:gtceu/nuclearcraft/canner' + id + '_heat_sink')
            .itemInputs('nuclearcraft:empty_heat_sink', input)
            .itemOutputs('nuclearcraft:' + id + '_heat_sink')
            .EUt(hv)
            .duration(sec*15)
    }
    heatsink('lapis', '4x gtceu:lapis_dust')
    heatsink('emerald', '4x gtceu:emerald_dust')
    heatsink('copper', '4x gtceu:copper_dust')
    heatsink('cryotheum', '4x gtceu:cryotheum_dust')
    heatsink('slime', '4x minecraft:slime_ball')
    heatsink('netherite', '4x gtceu:netherite_alloy_dust')
    heatsink('enderium', '4x gtceu:ender_pearl_dust')
    heatsink('quartz', '4x gtceu:nether_quartz_dust')
    heatsink('end_stone', '4x gtceu:endstone_dust')
    heatsink('prismarine', '4x minecraft:prismarine_shard')
    heatsink('tin', '4x gtceu:tin_dust')
    heatsink('obsidian', '4x gtceu:obsidian_dust')
    heatsink('purpur', '4x nuclearcraft:purpur_dust')
    heatsink('fluorite', '4x gtceu:fluorite_dust')
    heatsink('redstone', '4x minecraft:redstone')
    heatsink('aluminum', '4x gtceu:aluminium_dust')
    heatsink('nether_brick', '4x minecraft:nether_brick')
    heatsink('carobbiite', '4x gtceu:carobbiite_dust')
    heatsink('lithium', '4x gtceu:lithium_dust')
    heatsink('magnesium', '4x gtceu:magnesium_dust')
    heatsink('diamond', '4x gtceu:diamond_dust')
    heatsink('arsenic', '4x gtceu:aresnic_dust')
    heatsink('villiaumite', '4x gtceu:villiaumite_dust')
    heatsink('iron', '4x gtceu:iron_dust')
    heatsink('manganese', '4x gtceu:manganese_dust')
    heatsink('lead', '4x gtceu:lead_dust')
    heatsink('gold', '4x gtceu:gold_dust')
    heatsink('boron', '4x gtceu:boron_dust')
    heatsink('glowstone', '4x minecraft:glowstone_dust')
    heatsink('silver', '4x gtceu:silver_dust')
    function heatsinkliquid(id, input) {
        event.recipes.gtceu.canner('kubejs:gtceu/nuclearcraft/canner' + id + '_heat_sink')
            .itemInputs('nuclearcraft:empty_heat_sink')
            .inputFluids(input)
            .itemOutputs('nuclearcraft:' + id + '_heat_sink')
            .EUt(hv)
            .duration(sec*15)
    }
    heatsinkliquid('water', 'minecraft:water 1000')
    heatsinkliquid('liquid_helium', 'gtceu:helium 1000')
    heatsinkliquid('liquid_nitrogen', 'gtceu:nitrogen 1000')

//Decay Hastener
    function decay(id, input, output) {
        event.recipes.gtceu.decay_hastener(id)
            .itemInputs(input)
            .itemOutputs(output)
            .EUt(hv)
            .duration(sec*10)
    }
    decay('californium_249', 'nuclearcraft:californium_249', 'nuclearcraft:curium_245')
    decay('berkelium_247', 'nuclearcraft:berkelium_247', 'nuclearcraft:americium_243')
    decay('berkelium_248', 'nuclearcraft:berkelium_248', 'gtceu:thorium_dust')
    decay('ruthenium_106_dust', 'nuclearcraft:ruthenium_106_dust', 'gtceu:palladium_dust')
    decay('plutonium_238', 'nuclearcraft:plutonium_238', 'gtceu:lead_dust')
    decay('thorium_dust', '4x gtceu:thorium_dust', 'nuclearcraft:thorium_232')
    decay('caesium_137_dust', 'nuclearcraft:caesium_137_dust', 'gtceu:barium_dust')
    decay('plutonium_239', 'nuclearcraft:plutonium_239', 'nuclearcraft:uranium_233')
    decay('californium_251', 'nuclearcraft:californium_251', 'nuclearcraft:curium_247')
    decay('tbp_dust', 'nuclearcraft:tbp_dust', 'nuclearcraft:thorium_230')
    decay('californium_252', 'nuclearcraft:californium_252', 'gtceu:thorium_dust')
    decay('strontium_90_dust', 'nuclearcraft:strontium_90_dust', 'gtceu:strontium_dust')
    decay('protactinium_233_dust', 'nuclearcraft:protactinium_233_dust', 'nuclearcraft:uranium_233')
    decay('californium_250', 'nuclearcraft:californium_250', 'nuclearcraft:curium_246')
    decay('uranium_238', 'nuclearcraft:uranium_238', 'gtceu:radium_dust')
    decay('uranium_235', 'nuclearcraft:uranium_235', 'gtceu:lead_dust')
    decay('curium_243', 'nuclearcraft:curium_243', 'nuclearcraft:plutonium_239')
    decay('neptunium_237', 'nuclearcraft:neptunium_237', 'nuclearcraft:uranium_233')
    decay('uranium_233', 'nuclearcraft:uranium_233', 'gtceu:bismuth_dust')
    decay('curium_245', 'nuclearcraft:curium_245', 'nuclearcraft:plutonium_241')
    decay('curium_246', 'nuclearcraft:curium_246', 'nuclearcraft:plutonium_242')
    decay('radium_dust', 'gtceu:radium_dust', 'gtceu:lead_dust')
    decay('polonium_dust', 'gtceu:polonium_dust', 'gtceu:lead_dust')
    decay('curium_247', 'nuclearcraft:curium_247', 'nuclearcraft:americium_243')
    decay('americium_241', 'nuclearcraft:americium_241', 'nuclearcraft:neptunium_237')
    decay('americium_242', 'nuclearcraft:americium_242', 'gtceu:lead_dust')
    decay('neptunium_236', 'nuclearcraft:neptunium_236', 'gtceu:thorium_dust')
    decay('bismuth_dust', 'gtceu:bismuth_dust', 'gtceu:thallium_dust')
    decay('promethium_147_dust', 'nuclearcraft:promethium_147_dust', 'gtceu:neodymium_dust')
    decay('europium_155_dust', 'nuclearcraft:europium_155_dust', 'gtceu:gadolinium_dust')
    decay('americium_243', 'nuclearcraft:americium_243', 'nuclearcraft:plutonium_238')
    decay('plutonium_241', 'nuclearcraft:plutonium_241', 'nuclearcraft:neptunium_237')
    decay('plutonium_242', 'nuclearcraft:plutonium_242', 'nuclearcraft:uranium_238')

//Isotope Separator
    function isotope_sep(id, input, output_a, output_b, time) {
        event.recipes.gtceu.isotope_separator(id)
            .itemInputs(input)
            .itemOutputs(output_a, output_b)
            .EUt(hv)
            .duration(time)
    }
    isotope_sep('heu_235', '9x nuclearcraft:fuel_uranium_heu_235', '3x nuclearcraft:uranium_235', '6x nuclearcraft:uranium_238', sec*20)
    isotope_sep('lecf_249', '9x nuclearcraft:fuel_californium_lecf_249', 'nuclearcraft:californium_249', '8x nuclearcraft:californium_252', sec*20)
    isotope_sep('hecm_243', '9x nuclearcraft:fuel_curium_hecm_243', '3x nuclearcraft:curium_243', '6x nuclearcraft:curium_246', sec*20)
    isotope_sep('leb_248', '9x nuclearcraft:fuel_berkelium_leb_248', 'nuclearcraft:berkelium_248', '8x nuclearcraft:berkelium_247', sec*20)
    isotope_sep('heu_233', '9x nuclearcraft:fuel_uranium_heu_233', '3x nuclearcraft:uranium_233', '6x nuclearcraft:uranium_238', sec*20)
    isotope_sep('hecm_245', '9x nuclearcraft:fuel_curium_hecm_245', '3x nuclearcraft:curium_245', '6x nuclearcraft:curium_246', sec*20)
    isotope_sep('lithium', '10x gtceu:lithium_dust', '9x nuclearcraft:lithium_7', 'nuclearcraft:lithium_6', sec*50)
    isotope_sep('hecm_247', '9x nuclearcraft:fuel_curium_hecm_247', '3x nuclearcraft:curium_247', '6x nuclearcraft:curium_246', sec*20)
    isotope_sep('lecm_247', '9x nuclearcraft:fuel_curium_lecm_247', 'nuclearcraft:curium_247', '8x nuclearcraft:curium_246', sec*20)
    isotope_sep('lecm_245', '9x nuclearcraft:fuel_curium_lecm_245', 'nuclearcraft:curium_245', '8x nuclearcraft:curium_246', sec*20)
    isotope_sep('lecm_243', '9x nuclearcraft:fuel_curium_lecm_243', 'nuclearcraft:curium_243', '8x nuclearcraft:curium_246', sec*20)
    isotope_sep('hecf_249', '9x nuclearcraft:fuel_californium_hecf_249', '3x nuclearcraft:californium_249', '6x nuclearcraft:californium_252', sec*20)
    isotope_sep('lea_242', '9x nuclearcraft:fuel_americium_lea_242', 'nuclearcraft:americium_242', '8x nuclearcraft:americium_243', sec*20)
    isotope_sep('lep_241', '9x nuclearcraft:fuel_plutonium_lep_241', 'nuclearcraft:plutonium_241', '8x nuclearcraft:plutonium_242', sec*20)
    isotope_sep('hecf_251', '9x nuclearcraft:fuel_californium_hecf_251', '3x nuclearcraft:californium_251', '6x nuclearcraft:californium_252', sec*20)
    isotope_sep('hep_239', '9x nuclearcraft:fuel_plutonium_hep_239', '3x nuclearcraft:plutonium_239', '6x nuclearcraft:plutonium_242', sec*20)
    isotope_sep('hen_236', '9x nuclearcraft:fuel_neptunium_hen_236', '3x nuclearcraft:neptunium_236', '6x nuclearcraft:neptunium_237', sec*20)
    isotope_sep('lecf_251', '9x nuclearcraft:fuel_californium_lecf_251', 'nuclearcraft:californium_251', '8x nuclearcraft:californium_252', sec*20)
    isotope_sep('yellowcake', '10x nuclearcraft:yellowcake_dust', '7x nuclearcraft:uranium_238', '2x nuclearcraft:uranium_235', sec*50)
    isotope_sep('tbu', '9x nuclearcraft:fuel_thorium_tbu', 'nuclearcraft:thorium_232', '8x nuclearcraft:thorium_232', sec*20)
    isotope_sep('mix_239', '9x nuclearcraft:fuel_mixed_mix_239', 'nuclearcraft:plutonium_239', '8x nuclearcraft:plutonium_238_ni', sec*20)
    isotope_sep('len_236', '9x nuclearcraft:fuel_neptunium_len_236', 'nuclearcraft:neptunium_236', '8x nuclearcraft:neptunium_237', sec*20)
    isotope_sep('uranium', '10x gtceu:uranium_dust', '9x nuclearcraft:uranium_238', 'nuclearcraft:uranium_235', sec*40)
    isotope_sep('leu_235', '9x nuclearcraft:fuel_uranium_leu_235', 'nuclearcraft:uranium_235', '8x nuclearcraft:uranium_238', sec*20)
    isotope_sep('heb_248', '9x nuclearcraft:fuel_berkelium_heb_248', '3x nuclearcraft:berkelium_248', '6x nuclearcraft:berkelium_247', sec*20)
    isotope_sep('mix_241', '9x nuclearcraft:fuel_mixed_mix_241', 'nuclearcraft:plutonium_241_ni', '8x nuclearcraft:plutonium_238_ni', sec*20)
    isotope_sep('lep_239', '9x nuclearcraft:fuel_plutonium_lep_239', 'nuclearcraft:plutonium_239', '8x nuclearcraft:plutonium_242', sec*20)
    isotope_sep('leu_233', '9x nuclearcraft:fuel_uranium_leu_233', 'nuclearcraft:uranium_233', '8x nuclearcraft:uranium_238', sec*20)
    isotope_sep('hep_241', '9x nuclearcraft:fuel_plutonium_hep_241', '3x nuclearcraft:plutonium_241', '6x nuclearcraft:plutonium_242', sec*20)
    isotope_sep('hea_242', '9x nuclearcraft:fuel_americium_hea_242', '3x nuclearcraft:americium_242', '6x nuclearcraft:americium_243', sec*20)
})