ServerEvents.recipes(event => {
//Oil
    event.recipes.gtceu.distillery('gtceu:oil')
        .inputFluids('tfmg:crude_oil 1000')
        .outputFluids('gtceu:oil 1000')
        .circuit(1)
        .duration(240)
        .EUt(30)
//Pumpjack
    event.recipes.gtceu.assembler('machine_input')
        .circuit(9)
        .itemInputs(
            'gtceu:solid_machine_casing', 
            'kubejs:advanced_clockwork_mechanism', 
            'create:shaft'
        )
        .itemOutputs('tfmg:machine_input')
        .duration(200)
        .EUt(16)
    event.recipes.gtceu.assembler('pumpjack_crank')
        .circuit(9)
        .itemInputs(
            '2x gtceu:steel_plate', 
            '2x gtceu:steel_rod', 
            'minecraft:string', 
            'gtceu:solid_machine_casing'
        )
        .itemOutputs('tfmg:pumpjack_crank')
        .duration(200)
        .EUt(16)
    event.recipes.gtceu.assembler('pumpjack_base')
        .circuit(11)
        .itemInputs(
            '4x gtceu:steel_plate',
            '2x kubejs:advanced_clockwork_mechanism', 
            'tfmg:industrial_pipe', 
            'minecraft:string', 
            'gtceu:solid_machine_casing'
        )
        .itemOutputs('tfmg:pumpjack_base')
        .duration(200)
        .EUt(16)
    event.recipes.gtceu.assembler('pumpjack_hammer')
        .circuit(9)
        .itemInputs('2x gtceu:steel_frame', 'create:shaft')
        .itemOutputs('tfmg:pumpjack_hammer')
        .duration(200)
        .EUt(16)
    event.recipes.gtceu.assembler('pumpjack_head')
        .circuit(9)
        .itemInputs('4x gtceu:steel_plate', 'gtceu:steel_block')
        .itemOutputs('tfmg:pumpjack_hammer_head')
        .duration(200)
        .EUt(16)
    event.recipes.gtceu.assembler('pumpjack_arm')
        .circuit(11)
        .itemInputs('6x gtceu:steel_plate')
        .itemOutputs('tfmg:pumpjack_hammer_part')
        .duration(200)
        .EUt(16)
    event.recipes.gtceu.assembler('pumpjack_connector')
        .circuit(13)
        .itemInputs('tfmg:pumpjack_hammer_part', 'create:shaft')
        .itemOutputs('tfmg:pumpjack_hammer_connector')
        .duration(200)
        .EUt(16)
//Industrial Pipe Wiremill
    event.recipes.gtceu.wiremill('tsipw')
        .itemInputs('gtceu:steel_tiny_fluid_pipe')
        .itemOutputs('tfmg:industrial_pipe')
        .duration(200)
        .EUt(16)
    event.recipes.gtceu.wiremill('ssipw')
        .itemInputs('gtceu:steel_small_fluid_pipe')
        .itemOutputs('2x tfmg:industrial_pipe')
        .duration(150)
        .EUt(7)
    event.recipes.gtceu.wiremill('sipw')
        .itemInputs('gtceu:steel_normal_fluid_pipe')
        .itemOutputs('4x tfmg:industrial_pipe')
        .duration(200)
        .EUt(16)
    event.recipes.gtceu.wiremill('lsipw')
        .itemInputs('gtceu:steel_large_fluid_pipe')
        .itemOutputs('8x tfmg:industrial_pipe')
        .duration(250)
        .EUt(30)
    event.recipes.gtceu.wiremill('hsipw')
        .itemInputs('gtceu:steel_huge_fluid_pipe')
        .itemOutputs('16x tfmg:industrial_pipe')
        .duration(300)
        .EUt(64)
    event.recipes.gtceu.wiremill('tsstipw')
        .itemInputs('gtceu:stainless_steel_tiny_fluid_pipe')
        .itemOutputs('8x tfmg:industrial_pipe')
        .duration(200)
        .EUt(64)
    event.recipes.gtceu.wiremill('ssstipw')
        .itemInputs('gtceu:stainless_steel_small_fluid_pipe')
        .itemOutputs('16x tfmg:industrial_pipe')
        .duration(250)
        .EUt(96)
    event.recipes.gtceu.wiremill('sstipw')
        .itemInputs('gtceu:stainless_steel_normal_fluid_pipe')
        .itemOutputs('32x tfmg:industrial_pipe')
        .duration(300)
        .EUt(120)
    event.recipes.gtceu.wiremill('lsstipw')
        .itemInputs('gtceu:stainless_steel_large_fluid_pipe')
        .itemOutputs('64x tfmg:industrial_pipe')
        .duration(350)
        .EUt(256)
//Industrial Pipe Extruder
    event.recipes.gtceu.extruder('tsipe')
        .itemInputs('gtceu:steel_tiny_fluid_pipe')
        .notConsumable('gtceu:tiny_pipe_extruder_mold')
        .itemOutputs('tfmg:industrial_pipe')
        .duration(1)
        .EUt(64)
    event.recipes.gtceu.extruder('ssipe')
        .itemInputs('gtceu:steel_small_fluid_pipe')
        .notConsumable('gtceu:tiny_pipe_extruder_mold')
        .itemOutputs('2x tfmg:industrial_pipe')
        .duration(4)
        .EUt(64)
    event.recipes.gtceu.extruder('sipe')
        .itemInputs('gtceu:steel_normal_fluid_pipe')
        .notConsumable('gtceu:tiny_pipe_extruder_mold')
        .itemOutputs('4x tfmg:industrial_pipe')
        .duration(8)
        .EUt(64)
    event.recipes.gtceu.extruder('lsipe')
        .itemInputs('gtceu:steel_large_fluid_pipe')
        .notConsumable('gtceu:tiny_pipe_extruder_mold')
        .itemOutputs('8x tfmg:industrial_pipe')
        .duration(16)
        .EUt(64)
    event.recipes.gtceu.extruder('hsipe')
        .itemInputs('gtceu:steel_huge_fluid_pipe')
        .notConsumable('gtceu:tiny_pipe_extruder_mold')
        .itemOutputs('16x tfmg:industrial_pipe')
        .duration(32)
        .EUt(64)
    event.recipes.gtceu.extruder('tsstipe')
        .itemInputs('gtceu:stainless_steel_tiny_fluid_pipe')
        .notConsumable('gtceu:tiny_pipe_extruder_mold')
        .itemOutputs('8x tfmg:industrial_pipe')
        .duration(4)
        .EUt(120)
    event.recipes.gtceu.extruder('ssstipe')
        .itemInputs('gtceu:stainless_steel_small_fluid_pipe')
        .notConsumable('gtceu:tiny_pipe_extruder_mold')
        .itemOutputs('16x tfmg:industrial_pipe')
        .duration(8)
        .EUt(120)
    event.recipes.gtceu.extruder('sstipe')
        .itemInputs('gtceu:stainless_steel_normal_fluid_pipe')
        .notConsumable('gtceu:tiny_pipe_extruder_mold')
        .itemOutputs('32x tfmg:industrial_pipe')
        .duration(16)
        .EUt(120)
    event.recipes.gtceu.extruder('lsstipe')
        .itemInputs('gtceu:stainless_steel_large_fluid_pipe')
        .notConsumable('gtceu:tiny_pipe_extruder_mold')
        .itemOutputs('64x tfmg:industrial_pipe')
        .duration(32)
        .EUt(120)
    event.recipes.create.crushing(['gtceu:raw_lignite', Item.of('gtceu:raw_lignite').withChance(0.005)], 'tfmg:lignite')
    event.recipes.create.milling([Item.of('gtceu:raw_lignite').withChance(0.95)], 'tfmg:lignite')
    event.recipes.gtceu.distillery('tfmg_bitumen')
        .inputFluids('tfmg:heavy_oil 10')
        .circuit(5)
        .itemOutputs('tfmg:bitumen')
        .chancedFluidOutput('gtceu:sulfur_dioxide 10', 5000, 500)
        .EUt(lv/2)
        .duration(8)
    event.recipes.gtceu.distillery('gt_bitumen')
        .inputFluids('gtceu:oil_heavy 10')
        .circuit(5)
        .itemOutputs('tfmg:bitumen')
        .chancedFluidOutput('gtceu:sulfur_dioxide 10', 5000, 500)
        .EUt(lv/2)
        .duration(8)
    event.recipes.gtceu.mixer('asphalt')
        .inputFluids('minecraft:water 500')
        .itemInputs('tfmg:bitumen', 'minecraft:gravel', '#forge:sand')
        .outputFluids('tfmg:liquid_asphalt 1440')
        .EUt(lv/2)
        .duration(sec*2)
    event.recipes.gtceu.fluid_solidifier('asphalt')
        .inputFluids('tfmg:liquid_asphalt 144')
        .notConsumable('gtceu:block_casting_mold')
        .itemOutputs('tfmg:asphalt')
        .EUt(ulv)
        .duration(98)
})