StartupEvents.registry('item', event => {
	event.create('incomplete_wrought_iron', 'create:sequenced_assembly')
	event.create('incomplete_cog', 'create:sequenced_assembly')
	event.create('incomplete_large_cog', 'create:sequenced_assembly')
	event.create('incomplete_rudimentary_mechanism', 'create:sequenced_assembly')
	event.create('incomplete_sealed_mechanism', 'create:sequenced_assembly')
	event.create('incomplete_clockwork_mechanism', 'create:sequenced_assembly')
	event.create('incomplete_advanced_clockwork_mechanism', 'create:sequenced_assembly')
	event.create('incomplete_conductive_mechanism', 'create:sequenced_assembly')
	event.create('incomplete_electron_tube', 'create:sequenced_assembly')
	event.create('incomplete_generator_coil', 'create:sequenced_assembly')
	event.create('incomplete_blaze_burner', 'create:sequenced_assembly')
	event.create('incomplete_vacuum_tube', 'create:sequenced_assembly')
	event.create('incomplete_coal_resistor', 'create:sequenced_assembly')
	event.create('incomplete_carbon_resistor', 'create:sequenced_assembly')
	event.create('incomplete_charcoal_resistor', 'create:sequenced_assembly')
	event.create('incomplete_basic_electronic_circuit', 'create:sequenced_assembly')
	event.create('incomplete_good_electronic_circuit', 'create:sequenced_assembly')
	event.create('incomplete_resin_printed_circuit_board', 'create:sequenced_assembly')
	//event.create('incomplete_', 'create:sequenced_assembly')
	//event.create('incomplete_', 'create:sequenced_assembly')
	//event.create('incomplete_', 'create:sequenced_assembly')
	//event.create('incomplete_', 'create:sequenced_assembly')
	//event.create('incomplete_', 'create:sequenced_assembly')
	//event.create('incomplete_', 'create:sequenced_assembly')
	//event.create('incomplete_', 'create:sequenced_assembly')
	//event.create('incomplete_', 'create:sequenced_assembly')
	//event.create('incomplete_', 'create:sequenced_assembly')

// IRON CHESTS RESTOCKED
	let createIncompleteChest = (material) => {
		event.create('incomplete_' + material + '_barrel', 'create:sequenced_assembly')
		event.create('incomplete_' + material + '_chest_upgrade', 'create:sequenced_assembly')
		event.create('incomplete_' + material + '_chest', 'create:sequenced_assembly')
	}
	createIncompleteChest('copper')
	createIncompleteChest('crystal')
	createIncompleteChest('diamond')
	createIncompleteChest('gold')
	createIncompleteChest('iron')
	createIncompleteChest('netherite')
	createIncompleteChest('obsidian')
})