ServerEvents.recipes(event => {
    event.recipes.gtceu.macerator('netherite_scrap')
        .itemInputs('minecraft:ancient_debris')
        .itemOutputs('gtceu:netherite_scrap_dust')
        .EUt(hv)
        .duration(sec*20)
    event.recipes.gtceu.macerator('crushed_scrap')
        .itemInputs('minecraft:netherite_scrap')
        .itemOutputs('kubejs:crushed_netherite_scrap')
        .EUt(hv)
        .duration(sec*20)
    event.recipes.gtceu.mixer('impure_netherite_slurry')
        .itemInputs('2x kubejs:crushed_netherite_scrap')
        .inputFluids('gtceu:aqua_regia 3000')
        .outputFluids('gtceu:impure_netherite_slurry 3000')
        .EUt(hv)
        .duration(sec*20)
    event.recipes.gtceu.chemical_reactor('pure_netherite_slurry')
        .inputFluids('gtceu:impure_netherite_slurry 1000', 'gtceu:sulfuric_acid 1000')
        .outputFluids('gtceu:pure_netherite_slurry 1000', 'gtceu:diluted_sulfuric_acid 1000')
        .EUt(hv)
        .duration(sec*20)
    event.recipes.gtceu.centrifuge('netherite_dust')
        .inputFluids('gtceu:pure_netherite_slurry 3000')
        .outputFluids('gtceu:diluted_hydrochloric_acid 2000')
        .itemOutputs('gtceu:netherite_dust')
        .EUt(hv)
        .duration(sec*20)
    event.recipes.gtceu.mixer('netherite_alloy_dust')
        .circuit(17)
        .itemInputs('gtceu:netherite_dust', '4x gtceu:gold_dust')
        .itemOutputs('5x gtceu:netherite_alloy_dust')
        .EUt(hv)
        .duration(min)
})