
[air]
	#Range: > 1
	uses_per_tank = 512
	#Range: > 1
	uses_per_tank_hover = 5120

[speed]
	#Range: 0.01 ~ 100.0
	horizontal = 0.01
	#Range: 0.01 ~ 100.0
	vertical = 0.1
	#Range: 0.01 ~ 100.0
	acceleration = 0.06
	#Range: -100.0 ~ 0.0
	hover_descend = -0.05
	#Range: 0.0 ~ 100.0
	swim_modifier = 1.8

[features]
	#Range: 1.0 ~ 100.0
	elytra_boost = 1.25

[enchantments]
	list = []
	is_blacklist = true

