
##Basic Burner Requirements
[basic_burner]
	#When set to True, an active Basic Burner produces the same heat as a Kindled Blaze Burner and an empowered Basic Burner produces the same heat as a Seething Blaze Burner. Inactive state is unaffected.
	hotBurners = false
	#When set to True, ignores Basic Burner Fuel Item Tag Whitelist, instead accepts anything with a valid BurnTime.
	ignoresFuelTagWhitelist = true
	#How much more fuel a non-empowered Basic Burner consumes. Use fanMultiplier for fan-empowered burners. Intended for use with the hotBurners option, the default value of 1 is recommended otherwise.
	#Range: > 1
	baseMultiplier = 1
	#How much more fuel a Basic Burner consumes when empowered by a maxed encased fan.
	#Range: > 1
	fanMultiplier = 32

