GTCEuStartupEvents.registry('gtceu:world_gen_layer', event => {
    event.create('moon_stone')
        .targets('#ad_astra:moon_stone_replaceables')
        .dimensions('ad_astra:moon')
    event.create('mars_stone')
        .targets('#ad_astra:mars_stone_replaceables')
        .dimensions('ad_astra:mars')
    event.create('mercury_stone')
        .targets('#ad_astra:mercury_stone_replaceables')
        .dimensions('ad_astra:mercury')
    event.create('venus_stone')
        .targets('#ad_astra:venus_stone_replaceables')
        .dimensions('ad_astra:venus')
})