ClientEvents.lang('en_us', event => {
    event.renameItem("fluidtank:tank_wood", "Tank")
    event.renameItem("fluidtank:tank_stone", "Obsidian Tank")
    event.renameItem("fluidtank:tank_tin", "Aluminium Tank")
    event.renameItem("fluidtank:tank_silver", "Stainless Steel Tank")
    event.renameItem("fluidtank:tank_bronze", "Titanium Tank")
    event.renameItem("fluidtank:tank_lead", "Tungstensteel Tank")
    event.renameItem("minecraft:gunpowder", "Black Powder")
    event.renameItem("sophisticatedbackpacks:copper_backpack", "Aluminium Backpack")
    event.renameItem("sophisticatedbackpacks:iron_backpack", "Stainless Steel Backpack")
    event.renameItem("sophisticatedbackpacks:gold_backpack", "Titanium Backpack")
    event.renameItem("sophisticatedbackpacks:diamond_backpack", "Tungsten Steel Backpack")
    event.renameItem("sophisticatedbackpacks:netherite_backpack", "Rhodium Plated Palladium Backpack")
    event.renameItem("create:blaze_burner", "Clockwork Burner")
    event.renameItem("ad_astra:rocket_nose_cone", "Basic Command Pod")
    event.renameItem("tfmg:copper_sulfate", "Cupric Sulfate")
//Wöhler Aluminium
    event.renameItem("tfmg:aluminum_ingot", "Wöhler Aluminium Ingot")
    event.renameItem("tfmg:aluminum_block", "Wöhler Aluminium Block")
    event.renameItem("tfmg:aluminum_cable_hub", "Wöhler Aluminium Cable Hub")
    event.renameItem("tfmg:aluminum_cogwheel", "Wöhler Aluminium Cogwheel")
    event.renameItem("tfmg:large_aluminum_cogwheel", "Large Wöhler Aluminium Cogwheel")
    event.renameItem("tfmg:aluminum_wire", "Wöhler Aluminium Wire")
    event.renameItem("tfmg:aluminum_truss", "Wöhler Aluminium Truss")
    event.renameItem("tfmg:aluminum_frame", "Wöhler Aluminium Frame")
    event.renameItem("tfmg:aluminum_scaffolding", "Wöhler Aluminium Scaffolding")
    event.renameItem("tfmg:aluminum_bars", "Wöhler Aluminium Bars")
    event.renameItem("tfmg:aluminum_ladder", "Wöhler Aluminium Ladder")
    event.renameItem("tfmg:aluminum_flywheel", "Wöhler Aluminium Flywheel")
    event.renameItem("tfmg:aluminum_pipe", "Wöhler Aluminium Pipe")
    event.renameItem("tfmg:aluminum_mechanical_pump", "Wöhler Aluminium Mechanical Pump")
    event.renameItem("tfmg:aluminum_smart_fluid_pipe", "Wöhler Aluminium Smart Fluid Pipe")
    event.renameItem("tfmg:aluminum_fluid_valve", "Wöhler Aluminium Fluid Valve")
});