ClientEvents.lang('en_us', event => {
    event.renameItem("fluidtank:tank_wood", "Tank")
    event.renameItem("fluidtank:tank_stone", "Obsidian Tank")
    event.renameItem("fluidtank:tank_tin", "Aluminium Tank")
    event.renameItem("fluidtank:tank_silver", "Stainless Steel Tank")
    event.renameItem("fluidtank:tank_bronze", "Titanium Tank")
    event.renameItem("fluidtank:tank_lead", "Tungstensteel Tank")
    event.renameItem("minecraft:gunpowder", "Black Powder")
    event.renameItem("sophisticatedbackpacks:copper_backpack", "Aluminium Backpack")
    event.renameItem("sophisticatedbackpacks:iron_backpack", "Stainless Steel Backpack")
    event.renameItem("sophisticatedbackpacks:gold_backpack", "Titanium Backpack")
    event.renameItem("sophisticatedbackpacks:diamond_backpack", "Tungsten Steel Backpack")
    event.renameItem("sophisticatedbackpacks:netherite_backpack", "Rhodium Plated Palladium Backpack")
    event.renameItem("create:blaze_burner", "Clockwork Burner")
    event.renameItem("ad_astra:rocket_nose_cone", "Command Pod")
});