StartupEvents.registry('item', event => {
//Line one (purple)
    event.create('optical_processing_unit')
        //.displayName()
        //.texture()
        //.tooltip()

    event.create('optical_circuit_board')
        //.displayName()
        //.texture()
        //.tooltip()

    event.create('optical_printed_circuit_board')
        //.displayName()
        //.texture()
        //.tooltip()

    event.create('optical_processor')
        //.displayName()
        .texture('gtceu:item/line_one/optical_processor')
        .tooltip('§5ZPM-tier Circuit')

    event.create('optical_processor_assembly')
        //.displayName()
        .texture('gtceu:item/line_one/optical_processor_assembly')
        .tooltip('§5UV-tier Circuit')

    event.create('optical_processor_computer')
        //.displayName()
        .texture('gtceu:item/line_one/optical_processor_computer')
        .tooltip('§5UHV-tier Circuit')

    event.create('optical_processor_mainframe')
        //.displayName()
        .texture('gtceu:item/line_one/optical_processor_mainframe')
        .tooltip('§5UEV-tier Circuit')

//Line two (dark green)
    event.create('quantum_processing_unit')
        //.displayName()
        //.texture()
        //.tooltip()

    event.create('quantum_circuit_board')
        //.displayName()
        //.texture()
        //.tooltip()

    event.create('quantum_printed_circuit_board')
        //.displayName()
        //.texture()
        //.tooltip()

    event.create('quantum_processor')
        //.displayName()
        .texture('gtceu:item/line_two/quantum_processor')
        .tooltip('§2UV-tier Circuit')

    event.create('quantum_processor_assembly')
        //.displayName()
        .texture('gtceu:item/line_two/quantum_processor_assembly')
        .tooltip('§2UHV-tier Circuit')

    event.create('quantum_processor_computer')
        //.displayName()
        .texture('gtceu:item/line_two/quantum_processor_computer')
        .tooltip('§2UEV-tier Circuit')

    event.create('quantum_processor_mainframe')
        //.displayName()
        .texture('gtceu:item/line_two/quantum_processor_mainframe')
        .tooltip('§2UIV-tier Circuit')

//Line three (white)
    event.create('deep_space_processing_unit')
        //.displayName()
        //.texture()
        //.tooltip()

    event.create('deep_space_circuit_board')
        //.displayName()
        //.texture()
        //.tooltip()

    event.create('deep_space_printed_circuit_board')
        //.displayName()
        //.texture()
        //.tooltip()

    event.create('deep_space_processor')
        //.displayName()
        .texture('gtceu:item/line_three/deep_space_processor')
        .tooltip('§fUHV-tier Circuit')

    event.create('deep_space_processor_assembly')
        //.displayName()
        .texture('gtceu:item/line_three/deep_space_processor_assembly')
        .tooltip('§fUEV-tier Circuit')

    event.create('deep_space_processor_computer')
        //.displayName()
        .texture('gtceu:item/line_three/deep_space_processor_computer')
        .tooltip('§fUIV-tier Circuit')

    event.create('deep_space_processor_mainframe')
        //.displayName()
        .texture('gtceu:item/line_three/deep_space_processor_mainframe')
        .tooltip('§fUXV-tier Circuit')

//Line four (dark grey)
    event.create('singularity_processing_unit')
        //.displayName()
        //.texture()
        //.tooltip()

    event.create('singularity_circuit_board')
        //.displayName()
        //.texture()
        //.tooltip()

    event.create('singularity_printed_circuit_board')
        //.displayName()
        //.texture()
        //.tooltip()

    event.create('singularity_processor')
        //.displayName()
        .texture('gtceu:item/line_four/singularity_processor')
        .tooltip('§8UEV-tier Circuit')

    event.create('singularity_processor_assembly')
        //.displayName()
        .texture('gtceu:item/line_four/singularity_processor_assembly')
        .tooltip('§8UIV-tier Circuit')

    event.create('singularity_processor_computer')
        //.displayName()
        .texture('gtceu:item/line_four/singularity_processor_computer')
        .tooltip('§8UXV-tier Circuit')

    event.create('singularity_processor_mainframe')
        //.displayName()
        .texture('gtceu:item/line_four/singularity_processor_mainframe')
        .tooltip('§8OPV-tier Circuit')

//Line five (gold)
    event.create('4d_processing_unit')
        //.displayName()
        //.texture()
        //.tooltip()

    event.create('4d_circuit_board')
        //.displayName()
        //.texture()
        //.tooltip()

    event.create('4d_printed_circuit_board')
        //.displayName()
        //.texture()
        //.tooltip()

    event.create('4d_processor')
        //.displayName()
        .texture('gtceu:item/line_five/4d_processor')
        .tooltip('§6UIV-tier Circuit')

    event.create('4d_processor_assembly')
        //.displayName()
        .texture('gtceu:item/line_five/4d_processor_assembly')
        .tooltip('§6UXV-tier Circuit')

    event.create('4d_processor_computer')
        //.displayName()
        .texture('gtceu:item/line_five/4d_processor_computer')
        .tooltip('§6OPV-tier Circuit')

    event.create('4d_processor_mainframe')
        //.displayName()
        .texture('gtceu:item/line_five/4d_processor_mainframe')
        .tooltip('§6MAX-tier Circuit')

//Optical SMD
    event.create('optical_transistor')
        //.displayName()
        //.texture()
        //.tooltip()
    event.create('optical_resistor')
        //.displayName()
        //.texture()
        //.tooltip()
    event.create('optical_capacitor')
        //.displayName()
        //.texture()
        //.tooltip()
    event.create('optical_diode')
        //.displayName()
        //.texture()
        //.tooltip()
    event.create('optical_inductor')
        //.displayName()
        //.texture()
        //.tooltip()
})