ServerEvents.recipes(event => {
    function crushwheel(output, input){
        event.recipes.create.crushing(output, input)
    }
    function wash(output, input){
        event.recipes.create.splashing(output, input)
    }
    crushwheel(['gtceu:crushed_aluminium_ore', Item.of('gtceu:crushed_aluminium_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_aluminium')
    crushwheel(['gtceu:impure_aluminium_dust', Item.of('gtceu:impure_aluminium_dust').withChance(0.5), Item.of('gtceu:bauxite_dust').withChance(0.1)], 'gtceu:crushed_aluminium_ore')
    wash('gtceu:aluminium_dust', 'gtceu:impure_aluminium_dust')
    crushwheel(['gtceu:crushed_antimony_ore', Item.of('gtceu:crushed_antimony_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_antimony')
    crushwheel(['gtceu:impure_antimony_dust', Item.of('gtceu:impure_antimony_dust').withChance(0.5), Item.of('gtceu:antimony_dust').withChance(0.1)], 'gtceu:crushed_antimony_ore')
    wash('gtceu:antimony_dust', 'gtceu:impure_antimony_dust')    
    crushwheel(['gtceu:crushed_arsenic_ore', Item.of('gtceu:crushed_arsenic_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_arsenic')
    crushwheel(['gtceu:impure_arsenic_dust', Item.of('gtceu:impure_arsenic_dust').withChance(0.5), Item.of('gtceu:arsenic_dust').withChance(0.1)], 'gtceu:crushed_arsenic_ore')
    wash('gtceu:arsenic_dust', 'gtceu:impure_arsenic_dust')
    crushwheel(['gtceu:crushed_beryllium_ore', Item.of('gtceu:crushed_beryllium_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_beryllium')
    crushwheel(['gtceu:impure_beryllium_dust', Item.of('gtceu:impure_beryllium_dust').withChance(0.5), Item.of('gtceu:emerald_dust').withChance(0.1)], 'gtceu:crushed_beryllium_ore')
    wash('gtceu:beryllium_dust', 'gtceu:impure_beryllium_dust')
    crushwheel(['gtceu:crushed_bismuth_ore', Item.of('gtceu:crushed_bismuth_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_bismuth')
    crushwheel(['gtceu:impure_bismuth_dust', Item.of('gtceu:impure_bismuth_dust').withChance(0.5), Item.of('gtceu:bismuth_dust').withChance(0.1)], 'gtceu:crushed_bismuth_ore')
    wash('gtceu:bismuth_dust', 'gtceu:impure_bismuth_dust')
    crushwheel(['gtceu:crushed_chromium_ore', Item.of('gtceu:crushed_chromium_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_chromium')
    crushwheel(['gtceu:impure_chromium_dust', Item.of('gtceu:impure_chromium_dust').withChance(0.5), Item.of('gtceu:chromium_dust').withChance(0.1)], 'gtceu:crushed_chromium_ore')
    wash('gtceu:chromium_dust', 'gtceu:impure_chromium_dust')
    crushwheel(['gtceu:crushed_cobalt_ore', Item.of('gtceu:crushed_cobalt_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_cobalt')
    crushwheel(['gtceu:impure_cobalt_dust', Item.of('gtceu:impure_cobalt_dust').withChance(0.5), Item.of('gtceu:cobalt_oxide_dust').withChance(0.1)], 'gtceu:crushed_cobalt_ore')
    wash('gtceu:cobalt_dust', 'gtceu:impure_cobalt_dust')
    crushwheel(['gtceu:crushed_copper_ore', Item.of('gtceu:crushed_copper_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'minecraft:raw_copper')
    crushwheel(['gtceu:impure_copper_dust', Item.of('gtceu:impure_copper_dust').withChance(0.5), Item.of('gtceu:cobalt_dust').withChance(0.1)], 'gtceu:crushed_copper_ore')
    wash('gtceu:copper_dust', 'gtceu:impure_copper_dust')
    crushwheel(['gtceu:crushed_gallium_ore', Item.of('gtceu:crushed_gallium_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_gallium')
    crushwheel(['gtceu:impure_gallium_dust', Item.of('gtceu:impure_gallium_dust').withChance(0.5), Item.of('gtceu:gallium_dust').withChance(0.1)], 'gtceu:crushed_gallium_ore')
    wash('gtceu:gallium_dust', 'gtceu:impure_gallium_dust')
    crushwheel(['gtceu:crushed_gold_ore', Item.of('gtceu:crushed_gold_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'minecraft:raw_gold')
    crushwheel(['gtceu:impure_gold_dust', Item.of('gtceu:impure_gold_dust').withChance(0.5), Item.of('gtceu:copper_dust').withChance(0.1)], 'gtceu:crushed_gold_ore')
    wash('gtceu:gold_dust', 'gtceu:impure_gold_dust')
    crushwheel(['gtceu:crushed_iridium_ore', Item.of('gtceu:crushed_iridium_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_iridium')
    crushwheel(['gtceu:impure_iridium_dust', Item.of('gtceu:impure_iridium_dust').withChance(0.5), Item.of('gtceu:iridium_dust').withChance(0.1)], 'gtceu:crushed_iridium_ore')
    wash('gtceu:iridium_dust', 'gtceu:impure_iridium_dust')
    crushwheel(['gtceu:crushed_iron_ore', Item.of('gtceu:crushed_iron_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'minecraft:raw_iron')
    crushwheel(['gtceu:impure_iron_dust', Item.of('gtceu:impure_iron_dust').withChance(0.5), Item.of('gtceu:nickel_dust').withChance(0.1)], 'gtceu:crushed_iron_ore')
    wash('gtceu:iron_dust', 'gtceu:impure_iron_dust')
    crushwheel(['gtceu:crushed_lead_ore', Item.of('gtceu:crushed_lead_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_lead')
    crushwheel(['gtceu:impure_lead_dust', Item.of('gtceu:impure_lead_dust').withChance(0.5), Item.of('gtceu:silver_dust').withChance(0.1)], 'gtceu:crushed_lead_ore')
    wash('gtceu:lead_dust', 'gtceu:impure_lead_dust')
    crushwheel(['gtceu:crushed_lithium_ore', Item.of('gtceu:crushed_lithium_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_lithium')
    crushwheel(['gtceu:impure_lithium_dust', Item.of('gtceu:impure_lithium_dust').withChance(0.5), Item.of('gtceu:lithium_dust').withChance(0.1)], 'gtceu:crushed_lithium_ore')
    wash('gtceu:lithium_dust', 'gtceu:impure_lithium_dust')
    crushwheel(['gtceu:crushed_manganese_ore', Item.of('gtceu:crushed_manganese_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_manganese')
    crushwheel(['gtceu:impure_manganese_dust', Item.of('gtceu:impure_manganese_dust').withChance(0.5), Item.of('gtceu:manganese_dust').withChance(0.1)], 'gtceu:crushed_manganese_ore')
    wash('gtceu:manganese_dust', 'gtceu:impure_manganese_dust')
    crushwheel(['gtceu:crushed_molybdenum_ore', Item.of('gtceu:crushed_molybdenum_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_molybdenum')
    crushwheel(['gtceu:impure_molybdenum_dust', Item.of('gtceu:impure_molybdenum_dust').withChance(0.5), Item.of('gtceu:molybdenum_dust').withChance(0.1)], 'gtceu:crushed_molybdenum_ore')
    wash('gtceu:molybdenum_dust', 'gtceu:impure_molybdenum_dust')
    crushwheel(['gtceu:crushed_neodymium_ore', Item.of('gtceu:crushed_neodymium_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_neodymium')
    crushwheel(['gtceu:impure_neodymium_dust', Item.of('gtceu:impure_neodymium_dust').withChance(0.5), Item.of('gtceu:rare_earth_dust').withChance(0.1)], 'gtceu:crushed_neodymium_ore')
    wash('gtceu:neodymium_dust', 'gtceu:impure_neodymium_dust')
    crushwheel(['gtceu:crushed_nickel_ore', Item.of('gtceu:crushed_nickel_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_nickel')
    crushwheel(['gtceu:impure_nickel_dust', Item.of('gtceu:impure_nickel_dust').withChance(0.5), Item.of('gtceu:cobalt_dust').withChance(0.1)], 'gtceu:crushed_nickel_ore')
    wash('gtceu:nickel_dust', 'gtceu:impure_nickel_dust')
    crushwheel(['gtceu:crushed_niobium_ore', Item.of('gtceu:crushed_niobium_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_niobium')
    crushwheel(['gtceu:impure_niobium_dust', Item.of('gtceu:impure_niobium_dust').withChance(0.5), Item.of('gtceu:niobium_dust').withChance(0.1)], 'gtceu:crushed_niobium_ore')
    wash('gtceu:niobium_dust', 'gtceu:impure_niobium_dust')
    crushwheel(['gtceu:crushed_osmium_ore', Item.of('gtceu:crushed_osmium_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_osmium')
    crushwheel(['gtceu:impure_osmium_dust', Item.of('gtceu:impure_osmium_dust').withChance(0.5), Item.of('gtceu:osmium_dust').withChance(0.1)], 'gtceu:crushed_osmium_ore')
    wash('gtceu:osmium_dust', 'gtceu:impure_osmium_dust')
    crushwheel(['gtceu:crushed_palladium_ore', Item.of('gtceu:crushed_palladium_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_palladium')
    crushwheel(['gtceu:impure_palladium_dust', Item.of('gtceu:impure_palladium_dust').withChance(0.5), Item.of('gtceu:palladium_dust').withChance(0.1)], 'gtceu:crushed_palladium_ore')
    wash('gtceu:palladium_dust', 'gtceu:impure_palladium_dust')
    crushwheel(['gtceu:crushed_platinum_ore', Item.of('gtceu:crushed_platinum_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_platinum')
    crushwheel(['gtceu:impure_platinum_dust', Item.of('gtceu:impure_platinum_dust').withChance(0.5), Item.of('gtceu:nickel_dust').withChance(0.1)], 'gtceu:crushed_platinum_ore')
    wash('gtceu:platinum_dust', 'gtceu:impure_platinum_dust')
    crushwheel(['gtceu:crushed_plutonium_ore', Item.of('gtceu:crushed_plutonium_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_plutonium')
    crushwheel(['gtceu:impure_plutonium_dust', Item.of('gtceu:impure_plutonium_dust').withChance(0.5), Item.of('gtceu:uraninite_dust').withChance(0.1)], 'gtceu:crushed_plutonium_ore')
    wash('gtceu:plutonium_dust', 'gtceu:impure_plutonium_dust')
    crushwheel(['gtceu:crushed_plutonium_241_ore', Item.of('gtceu:crushed_plutonium_241_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_plutonium_241')
    crushwheel(['gtceu:impure_plutonium_241_dust', Item.of('gtceu:impure_plutonium_241_dust').withChance(0.5), Item.of('gtceu:plutonium_241_dust').withChance(0.1)], 'gtceu:crushed_plutonium_241_ore')
    wash('gtceu:plutonium_241_dust', 'gtceu:impure_plutonium_241_dust')
    crushwheel(['gtceu:crushed_silver_ore', Item.of('gtceu:crushed_silver_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_silver')
    crushwheel(['gtceu:impure_silver_dust', Item.of('gtceu:impure_silver_dust').withChance(0.5), Item.of('gtceu:lead_dust').withChance(0.1)], 'gtceu:crushed_silver_ore')
    wash('gtceu:silver_dust', 'gtceu:impure_silver_dust')
    crushwheel(['gtceu:crushed_sulfur_ore', Item.of('gtceu:crushed_sulfur_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_sulfur')
    crushwheel(['gtceu:impure_sulfur_dust', Item.of('gtceu:impure_sulfur_dust').withChance(0.5), Item.of('gtceu:sulfur_dust').withChance(0.1)], 'gtceu:crushed_sulfur_ore')
    wash('gtceu:sulfur_dust', 'gtceu:impure_sulfur_dust')
    crushwheel(['gtceu:crushed_thorium_ore', Item.of('gtceu:crushed_thorium_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_thorium')
    crushwheel(['gtceu:impure_thorium_dust', Item.of('gtceu:impure_thorium_dust').withChance(0.5), Item.of('gtceu:uraninite_dust').withChance(0.1)], 'gtceu:crushed_thorium_ore')
    wash('gtceu:thorium_dust', 'gtceu:impure_thorium_dust')
    crushwheel(['gtceu:crushed_tin_ore', Item.of('gtceu:crushed_tin_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_tin')
    crushwheel(['gtceu:impure_tin_dust', Item.of('gtceu:impure_tin_dust').withChance(0.5), Item.of('gtceu:iron_dust').withChance(0.1)], 'gtceu:crushed_tin_ore')
    wash('gtceu:tin_dust', 'gtceu:impure_tin_dust')
    crushwheel(['gtceu:crushed_titanium_ore', Item.of('gtceu:crushed_titanium_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_titanium')
    crushwheel(['gtceu:impure_titanium_dust', Item.of('gtceu:impure_titanium_dust').withChance(0.5), Item.of('gtceu:titanium_dust').withChance(0.1)], 'gtceu:crushed_titanium_ore')
    wash('gtceu:titanium_dust', 'gtceu:impure_titanium_dust')
    crushwheel(['gtceu:crushed_tungsten_ore', Item.of('gtceu:crushed_tungsten_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_tungsten')
    crushwheel(['gtceu:impure_tungsten_dust', Item.of('gtceu:impure_tungsten_dust').withChance(0.5), Item.of('gtceu:tungsten_dust').withChance(0.1)], 'gtceu:crushed_tungsten_ore')
    wash('gtceu:tungsten_dust', 'gtceu:impure_tungsten_dust')
    crushwheel(['gtceu:crushed_uranium_ore', Item.of('gtceu:crushed_uranium_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_uranium')
    crushwheel(['gtceu:impure_uranium_dust', Item.of('gtceu:impure_uranium_dust').withChance(0.5), Item.of('gtceu:uranium_dust').withChance(0.1)], 'gtceu:crushed_uranium_ore')
    wash('gtceu:uranium_dust', 'gtceu:impure_uranium_dust')
    crushwheel(['gtceu:crushed_uranium_235_ore', Item.of('gtceu:crushed_uranium_235_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_uranium_235')
    crushwheel(['gtceu:impure_uranium_235_dust', Item.of('gtceu:impure_uranium_235_dust').withChance(0.5), Item.of('gtceu:uranium_235_dust').withChance(0.1)], 'gtceu:crushed_uranium_235_ore')
    wash('gtceu:uranium_235_dust', 'gtceu:impure_uranium_235_dust')
    crushwheel(['gtceu:crushed_vanadium_ore', Item.of('gtceu:crushed_vanadium_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_vanadium')
    crushwheel(['gtceu:impure_vanadium_dust', Item.of('gtceu:impure_vanadium_dust').withChance(0.5), Item.of('gtceu:vanadium_dust').withChance(0.1)], 'gtceu:crushed_vanadium_ore')
    wash('gtceu:vanadium_dust', 'gtceu:impure_vanadium_dust')
    crushwheel(['gtceu:crushed_naquadah_ore', Item.of('gtceu:crushed_naquadah_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_naquadah')
    crushwheel(['gtceu:impure_naquadah_dust', Item.of('gtceu:impure_naquadah_dust').withChance(0.5), Item.of('gtceu:sulfur_dust').withChance(0.1)], 'gtceu:crushed_naquadah_ore')
    wash('gtceu:naquadah_dust', 'gtceu:impure_naquadah_dust')
    crushwheel(['gtceu:crushed_enriched_naquadah_ore', Item.of('gtceu:crushed_enriched_naquadah_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_enriched_naquadah')
    crushwheel(['gtceu:impure_enriched_naquadah_dust', Item.of('gtceu:impure_enriched_naquadah_dust').withChance(0.5), Item.of('gtceu:enriched_naquadah_dust').withChance(0.1)], 'gtceu:crushed_enriched_naquadah_ore')
    wash('gtceu:enriched_naquadah_dust', 'gtceu:impure_enriched_naquadah_dust')
    crushwheel(['gtceu:crushed_naquadria_ore', Item.of('gtceu:crushed_naquadria_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_naquadria')
    crushwheel(['gtceu:impure_naquadria_dust', Item.of('gtceu:impure_naquadria_dust').withChance(0.5), Item.of('gtceu:naquadria_dust').withChance(0.1)], 'gtceu:crushed_naquadria_ore')
    wash('gtceu:naquadria_dust', 'gtceu:impure_naquadria_dust')
    crushwheel(['gtceu:crushed_neutronium_ore', Item.of('gtceu:crushed_neutronium_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_neutronium')
    crushwheel(['gtceu:impure_neutronium_dust', Item.of('gtceu:impure_neutronium_dust').withChance(0.5), Item.of('gtceu:neutronium_dust').withChance(0.1)], 'gtceu:crushed_neutronium_ore')
    wash('gtceu:neutronium_dust', 'gtceu:impure_neutronium_dust')
    crushwheel(['2x gtceu:crushed_almandine_ore', Item.of('2x gtceu:crushed_almandine_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_almandine')
    crushwheel(['gtceu:impure_almandine_dust', Item.of('gtceu:impure_almandine_dust').withChance(0.5), Item.of('gtceu:red_garnet_dust').withChance(0.1)], 'gtceu:crushed_almandine_ore')
    wash('gtceu:almandine_dust', 'gtceu:impure_almandine_dust')
    crushwheel(['gtceu:crushed_andradite_ore', Item.of('gtceu:crushed_andradite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_andradite')
    crushwheel(['gtceu:impure_andradite_dust', Item.of('gtceu:impure_andradite_dust').withChance(0.5), Item.of('gtceu:andradite_dust').withChance(0.1)], 'gtceu:crushed_andradite_ore')
    wash('gtceu:andradite_dust', 'gtceu:impure_andradite_dust')
    crushwheel(['2x gtceu:crushed_asbestos_ore', Item.of('2x gtceu:crushed_asbestos_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_asbestos')
    crushwheel(['gtceu:impure_asbestos_dust', Item.of('gtceu:impure_asbestos_dust').withChance(0.5), Item.of('gtceu:diatomite_dust').withChance(0.1)], 'gtceu:crushed_asbestos_ore')
    wash('gtceu:asbestos_dust', 'gtceu:impure_asbestos_dust')
    crushwheel(['gtceu:crushed_hematite_ore', Item.of('gtceu:crushed_hematite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_hematite')
    crushwheel(['gtceu:impure_hematite_dust', Item.of('gtceu:impure_hematite_dust').withChance(0.5), Item.of('gtceu:magnetite_dust').withChance(0.1)], 'gtceu:crushed_hematite_ore')
    wash('gtceu:hematite_dust', 'gtceu:impure_hematite_dust')
    crushwheel(['gtceu:crushed_blue_topaz_ore', Item.of('gtceu:crushed_blue_topaz_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_blue_topaz')
    crushwheel(['gtceu:impure_blue_topaz_dust', Item.of('gtceu:impure_blue_topaz_dust').withChance(0.5), Item.of('gtceu:topaz_dust').withChance(0.1)], 'gtceu:crushed_blue_topaz_ore')
    wash('gtceu:blue_topaz_dust', 'gtceu:impure_blue_topaz_dust')
    crushwheel(['gtceu:crushed_goethite_ore', Item.of('gtceu:crushed_goethite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_goethite')
    crushwheel(['gtceu:impure_goethite_dust', Item.of('gtceu:impure_goethite_dust').withChance(0.5), Item.of('gtceu:malachite_dust').withChance(0.1)], 'gtceu:crushed_goethite_ore')
    wash('gtceu:goethite_dust', 'gtceu:impure_goethite_dust')
    crushwheel(['gtceu:crushed_calcite_ore', Item.of('gtceu:crushed_calcite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_calcite')
    crushwheel(['gtceu:impure_calcite_dust', Item.of('gtceu:impure_calcite_dust').withChance(0.5), Item.of('gtceu:calcium_dust').withChance(0.1)], 'gtceu:crushed_calcite_ore')
    wash('gtceu:calcite_dust', 'gtceu:impure_calcite_dust')
    crushwheel(['gtceu:crushed_cassiterite_ore', Item.of('gtceu:crushed_cassiterite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_cassiterite')
    crushwheel(['gtceu:impure_cassiterite_dust', Item.of('gtceu:impure_cassiterite_dust').withChance(0.5), Item.of('gtceu:tin_dust').withChance(0.1)], 'gtceu:crushed_cassiterite_ore')
    wash('gtceu:cassiterite_dust', 'gtceu:impure_cassiterite_dust')
    crushwheel(['gtceu:crushed_chalcopyrite_ore', Item.of('gtceu:crushed_chalcopyrite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_chalcopyrite')
    crushwheel(['gtceu:impure_chalcopyrite_dust', Item.of('gtceu:impure_chalcopyrite_dust').withChance(0.5), Item.of('gtceu:pyrite_dust').withChance(0.1)], 'gtceu:crushed_chalcopyrite_ore')
    wash('gtceu:chalcopyrite_dust', 'gtceu:impure_chalcopyrite_dust')
    crushwheel(['gtceu:crushed_chromite_ore', Item.of('gtceu:crushed_chromite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_chromite')
    crushwheel(['gtceu:impure_chromite_dust', Item.of('gtceu:impure_chromite_dust').withChance(0.5), Item.of('gtceu:iron_dust').withChance(0.1)], 'gtceu:crushed_chromite_ore')
    wash('gtceu:chromite_dust', 'gtceu:impure_chromite_dust')
    crushwheel(['gtceu:crushed_cinnabar_ore', Item.of('gtceu:crushed_cinnabar_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_cinnabar')
    crushwheel(['gtceu:impure_cinnabar_dust', Item.of('gtceu:impure_cinnabar_dust').withChance(0.5), Item.of('minecraft:redstone').withChance(0.1)], 'gtceu:crushed_cinnabar_ore')
    wash('gtceu:cinnabar_dust', 'gtceu:impure_cinnabar_dust')
    crushwheel(['gtceu:crushed_coal_ore', Item.of('gtceu:crushed_coal_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_coal')
    crushwheel(['gtceu:impure_coal_dust', Item.of('gtceu:impure_coal_dust').withChance(0.5), Item.of('gtceu:coal_dust').withChance(0.1)], 'gtceu:crushed_coal_ore')
    wash('gtceu:coal_dust', 'gtceu:impure_coal_dust')
    crushwheel(['gtceu:crushed_cobaltite_ore', Item.of('gtceu:crushed_cobaltite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_cobaltite')
    crushwheel(['gtceu:impure_cobaltite_dust', Item.of('gtceu:impure_cobaltite_dust').withChance(0.5), Item.of('gtceu:sulfur_dust').withChance(0.1)], 'gtceu:crushed_cobaltite_ore')
    wash('gtceu:cobaltite_dust', 'gtceu:impure_cobaltite_dust')
    crushwheel(['gtceu:crushed_cooperite_ore', Item.of('gtceu:crushed_cooperite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_cooperite')
    crushwheel(['gtceu:impure_cooperite_dust', Item.of('gtceu:impure_cooperite_dust').withChance(0.5), Item.of('gtceu:nickel_dust').withChance(0.1)], 'gtceu:crushed_cooperite_ore')
    wash('gtceu:cooperite_dust', 'gtceu:impure_cooperite_dust')
    crushwheel(['gtceu:crushed_diamond_ore', Item.of('gtceu:crushed_diamond_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_diamond')
    crushwheel(['gtceu:impure_diamond_dust', Item.of('gtceu:impure_diamond_dust').withChance(0.5), Item.of('gtceu:graphite_dust').withChance(0.1)], 'gtceu:crushed_diamond_ore')
    wash('gtceu:diamond_dust', 'gtceu:impure_diamond_dust')
    crushwheel(['gtceu:crushed_emerald_ore', Item.of('gtceu:crushed_emerald_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_emerald')
    crushwheel(['gtceu:impure_emerald_dust', Item.of('gtceu:impure_emerald_dust').withChance(0.5), Item.of('gtceu:beryllium_dust').withChance(0.1)], 'gtceu:crushed_emerald_ore')
    wash('gtceu:emerald_dust', 'gtceu:impure_emerald_dust')
    crushwheel(['gtceu:crushed_galena_ore', Item.of('gtceu:crushed_galena_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_galena')
    crushwheel(['gtceu:impure_galena_dust', Item.of('gtceu:impure_galena_dust').withChance(0.5), Item.of('gtceu:sulfur_dust').withChance(0.1)], 'gtceu:crushed_galena_ore')
    wash('gtceu:galena_dust', 'gtceu:impure_galena_dust')
    crushwheel(['gtceu:crushed_garnierite_ore', Item.of('gtceu:crushed_garnierite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_garnierite')
    crushwheel(['gtceu:impure_garnierite_dust', Item.of('gtceu:impure_garnierite_dust').withChance(0.5), Item.of('gtceu:iron_dust').withChance(0.1)], 'gtceu:crushed_garnierite_ore')
    wash('gtceu:garnierite_dust', 'gtceu:impure_garnierite_dust')
    crushwheel(['gtceu:crushed_green_sapphire_ore', Item.of('gtceu:crushed_green_sapphire_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_green_sapphire')
    crushwheel(['gtceu:impure_green_sapphire_dust', Item.of('gtceu:impure_green_sapphire_dust').withChance(0.5), Item.of('gtceu:aluminium_dust').withChance(0.1)], 'gtceu:crushed_green_sapphire_ore')
    wash('gtceu:green_sapphire_dust', 'gtceu:impure_green_sapphire_dust')
    crushwheel(['2x gtceu:crushed_grossular_ore', Item.of('2x gtceu:crushed_grossular_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_grossular')
    crushwheel(['gtceu:impure_grossular_dust', Item.of('gtceu:impure_grossular_dust').withChance(0.5), Item.of('gtceu:yellow_garnet_dust').withChance(0.1)], 'gtceu:crushed_grossular_ore')
    wash('gtceu:grossular_dust', 'gtceu:impure_grossular_dust')
    crushwheel(['gtceu:crushed_ilmenite_ore', Item.of('gtceu:crushed_ilmenite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_ilmenite')
    crushwheel(['gtceu:impure_ilmenite_dust', Item.of('gtceu:impure_ilmenite_dust').withChance(0.5), Item.of('gtceu:iron_dust').withChance(0.1)], 'gtceu:crushed_ilmenite_ore')
    wash('gtceu:ilmenite_dust', 'gtceu:impure_ilmenite_dust')
    crushwheel(['gtceu:crushed_rutile_ore', Item.of('gtceu:crushed_rutile_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_rutile')
    crushwheel(['gtceu:impure_rutile_dust', Item.of('gtceu:impure_rutile_dust').withChance(0.5), Item.of('gtceu:rutile_dust').withChance(0.1)], 'gtceu:crushed_rutile_ore')
    wash('gtceu:rutile_dust', 'gtceu:impure_rutile_dust')
    crushwheel(['gtceu:crushed_bauxite_ore', Item.of('gtceu:crushed_bauxite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_bauxite')
    crushwheel(['gtceu:impure_bauxite_dust', Item.of('gtceu:impure_bauxite_dust').withChance(0.5), Item.of('gtceu:grossular_dust').withChance(0.1)], 'gtceu:crushed_bauxite_ore')
    wash('gtceu:bauxite_dust', 'gtceu:impure_bauxite_dust')
    crushwheel(['3x gtceu:crushed_lazurite_ore', Item.of('3x gtceu:crushed_lazurite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_lazurite')
    crushwheel(['gtceu:impure_lazurite_dust', Item.of('gtceu:impure_lazurite_dust').withChance(0.5), Item.of('4x gtceu:sodalite_dust').withChance(0.1)], 'gtceu:crushed_lazurite_ore')
    wash('gtceu:lazurite_dust', 'gtceu:impure_lazurite_dust')
    crushwheel(['gtceu:crushed_magnesite_ore', Item.of('gtceu:crushed_magnesite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_magnesite')
    crushwheel(['gtceu:impure_magnesite_dust', Item.of('gtceu:impure_magnesite_dust').withChance(0.5), Item.of('gtceu:magnesium_dust').withChance(0.1)], 'gtceu:crushed_magnesite_ore')
    wash('gtceu:magnesite_dust', 'gtceu:impure_magnesite_dust')
    crushwheel(['gtceu:crushed_magnetite_ore', Item.of('gtceu:crushed_magnetite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_magnetite')
    crushwheel(['gtceu:impure_magnetite_dust', Item.of('gtceu:impure_magnetite_dust').withChance(0.5), Item.of('gtceu:iron_dust').withChance(0.1)], 'gtceu:crushed_magnetite_ore')
    wash('gtceu:magnetite_dust', 'gtceu:impure_magnetite_dust')
    crushwheel(['gtceu:crushed_molybdenite_ore', Item.of('gtceu:crushed_molybdenite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_molybdenite')
    crushwheel(['gtceu:impure_molybdenite_dust', Item.of('gtceu:impure_molybdenite_dust').withChance(0.5), Item.of('gtceu:molybdenum_dust').withChance(0.1)], 'gtceu:crushed_molybdenite_ore')
    wash('gtceu:molybdenite_dust', 'gtceu:impure_molybdenite_dust')
    crushwheel(['gtceu:crushed_powellite_ore', Item.of('gtceu:crushed_powellite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_powellite')
    crushwheel(['gtceu:impure_powellite_dust', Item.of('gtceu:impure_powellite_dust').withChance(0.5), Item.of('gtceu:iron_dust').withChance(0.1)], 'gtceu:crushed_powellite_ore')
    wash('gtceu:powellite_dust', 'gtceu:impure_powellite_dust')
    crushwheel(['gtceu:crushed_pyrite_ore', Item.of('gtceu:crushed_pyrite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_pyrite')
    crushwheel(['gtceu:impure_pyrite_dust', Item.of('gtceu:impure_pyrite_dust').withChance(0.5), Item.of('gtceu:sulfur_dust').withChance(0.1)], 'gtceu:crushed_pyrite_ore')
    wash('gtceu:pyrite_dust', 'gtceu:impure_pyrite_dust')
    crushwheel(['gtceu:crushed_pyrolusite_ore', Item.of('gtceu:crushed_pyrolusite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_pyrolusite')
    crushwheel(['gtceu:impure_pyrolusite_dust', Item.of('gtceu:impure_pyrolusite_dust').withChance(0.5), Item.of('gtceu:manganese_dust').withChance(0.1)], 'gtceu:crushed_pyrolusite_ore')
    wash('gtceu:pyrolusite_dust', 'gtceu:impure_pyrolusite_dust')
    crushwheel(['2x gtceu:crushed_pyrope_ore', Item.of('2x gtceu:crushed_pyrope_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_pyrope')
    crushwheel(['gtceu:impure_pyrope_dust', Item.of('gtceu:impure_pyrope_dust').withChance(0.5), Item.of('gtceu:red_garnet_dust').withChance(0.1)], 'gtceu:crushed_pyrope_ore')
    wash('gtceu:pyrope_dust', 'gtceu:impure_pyrope_dust')
    crushwheel(['gtceu:crushed_rock_salt_ore', Item.of('gtceu:crushed_rock_salt_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_rock_salt')
    crushwheel(['gtceu:impure_rock_salt_dust', Item.of('gtceu:impure_rock_salt_dust').withChance(0.5), Item.of('gtceu:salt_dust').withChance(0.1)], 'gtceu:crushed_rock_salt_ore')
    wash('gtceu:rock_salt_dust', 'gtceu:impure_rock_salt_dust')
    crushwheel(['gtceu:crushed_ruby_ore', Item.of('gtceu:crushed_ruby_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_ruby')
    crushwheel(['gtceu:impure_ruby_dust', Item.of('gtceu:impure_ruby_dust').withChance(0.5), Item.of('gtceu:chromium_dust').withChance(0.1)], 'gtceu:crushed_ruby_ore')
    wash('gtceu:ruby_dust', 'gtceu:impure_ruby_dust')
    crushwheel(['gtceu:crushed_salt_ore', Item.of('gtceu:crushed_salt_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_salt')
    crushwheel(['gtceu:impure_salt_dust', Item.of('gtceu:impure_salt_dust').withChance(0.5), Item.of('gtceu:rock_salt_dust').withChance(0.1)], 'gtceu:crushed_salt_ore')
    wash('gtceu:salt_dust', 'gtceu:impure_salt_dust')
    crushwheel(['gtceu:crushed_saltpeter_ore', Item.of('gtceu:crushed_saltpeter_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_saltpeter')
    crushwheel(['gtceu:impure_saltpeter_dust', Item.of('gtceu:impure_saltpeter_dust').withChance(0.5), Item.of('gtceu:saltpeter_dust').withChance(0.1)], 'gtceu:crushed_saltpeter_ore')
    wash('gtceu:saltpeter_dust', 'gtceu:impure_saltpeter_dust')
    crushwheel(['gtceu:crushed_sapphire_ore', Item.of('gtceu:crushed_sapphire_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_sapphire')
    crushwheel(['gtceu:impure_sapphire_dust', Item.of('gtceu:impure_sapphire_dust').withChance(0.5), Item.of('gtceu:aluminium_dust').withChance(0.1)], 'gtceu:crushed_sapphire_ore')
    wash('gtceu:sapphire_dust', 'gtceu:impure_sapphire_dust')
    crushwheel(['gtceu:crushed_scheelite_ore', Item.of('gtceu:crushed_scheelite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_scheelite')
    crushwheel(['gtceu:impure_scheelite_dust', Item.of('gtceu:impure_scheelite_dust').withChance(0.5), Item.of('gtceu:manganese_dust').withChance(0.1)], 'gtceu:crushed_scheelite_ore')
    wash('gtceu:scheelite_dust', 'gtceu:impure_scheelite_dust')
    crushwheel(['3x gtceu:crushed_sodalite_ore', Item.of('3x gtceu:crushed_sodalite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_sodalite')
    crushwheel(['gtceu:impure_sodalite_dust', Item.of('gtceu:impure_sodalite_dust').withChance(0.5), Item.of('gtceu:lazurite_dust').withChance(0.1)], 'gtceu:crushed_sodalite_ore')
    wash('gtceu:sodalite_dust', 'gtceu:impure_sodalite_dust')
    crushwheel(['gtceu:crushed_tantalite_ore', Item.of('gtceu:crushed_tantalite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_tantalite')
    crushwheel(['gtceu:impure_tantalite_dust', Item.of('gtceu:impure_tantalite_dust').withChance(0.5), Item.of('gtceu:manganese_dust').withChance(0.1)], 'gtceu:crushed_tantalite_ore')
    wash('gtceu:tantalite_dust', 'gtceu:impure_tantalite_dust')
    crushwheel(['2x gtceu:crushed_spessartine_ore', Item.of('2x gtceu:crushed_spessartine_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_spessartine')
    crushwheel(['gtceu:impure_spessartine_dust', Item.of('gtceu:impure_spessartine_dust').withChance(0.5), Item.of('gtceu:red_garnet_dust').withChance(0.1)], 'gtceu:crushed_spessartine_ore')
    wash('gtceu:spessartine_dust', 'gtceu:impure_spessartine_dust')
    crushwheel(['gtceu:crushed_sphalerite_ore', Item.of('gtceu:crushed_sphalerite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_sphalerite')
    crushwheel(['gtceu:impure_sphalerite_dust', Item.of('gtceu:impure_sphalerite_dust').withChance(0.5), Item.of('gtceu:yellow_garnet_dust').withChance(0.1)], 'gtceu:crushed_sphalerite_ore')
    wash('gtceu:sphalerite_dust', 'gtceu:impure_sphalerite_dust')
    crushwheel(['gtceu:crushed_stibnite_ore', Item.of('gtceu:crushed_stibnite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_stibnite')
    crushwheel(['gtceu:impure_stibnite_dust', Item.of('gtceu:impure_stibnite_dust').withChance(0.5), Item.of('gtceu:antimony_trioxide_dust').withChance(0.1)], 'gtceu:crushed_stibnite_ore')
    wash('gtceu:stibnite_dust', 'gtceu:impure_stibnite_dust')
    crushwheel(['gtceu:crushed_tetrahedrite_ore', Item.of('gtceu:crushed_tetrahedrite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_tetrahedrite')
    crushwheel(['gtceu:impure_tetrahedrite_dust', Item.of('gtceu:impure_tetrahedrite_dust').withChance(0.5), Item.of('gtceu:antimony_dust').withChance(0.1)], 'gtceu:crushed_tetrahedrite_ore')
    wash('gtceu:tetrahedrite_dust', 'gtceu:impure_tetrahedrite_dust')
    crushwheel(['gtceu:crushed_topaz_ore', Item.of('gtceu:crushed_topaz_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_topaz')
    crushwheel(['gtceu:impure_topaz_dust', Item.of('gtceu:impure_topaz_dust').withChance(0.5), Item.of('gtceu:blue_topaz_dust').withChance(0.1)], 'gtceu:crushed_topaz_ore')
    wash('gtceu:topaz_dust', 'gtceu:impure_topaz_dust')
    crushwheel(['gtceu:crushed_tungstate_ore', Item.of('gtceu:crushed_tungstate_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_tungstate')
    crushwheel(['gtceu:impure_tungstate_dust', Item.of('gtceu:impure_tungstate_dust').withChance(0.5), Item.of('gtceu:manganese_dust').withChance(0.1)], 'gtceu:crushed_tungstate_ore')
    wash('gtceu:tungstate_dust', 'gtceu:impure_tungstate_dust')
    crushwheel(['gtceu:crushed_uraninite_ore', Item.of('gtceu:crushed_uraninite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_uraninite')
    crushwheel(['gtceu:impure_uraninite_dust', Item.of('gtceu:impure_uraninite_dust').withChance(0.5), Item.of('gtceu:uraninite_dust').withChance(0.1)], 'gtceu:crushed_uraninite_ore')
    wash('gtceu:uraninite_dust', 'gtceu:impure_uraninite_dust')
    crushwheel(['gtceu:crushed_uvarovite_ore', Item.of('gtceu:crushed_uvarovite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_uvarovite')
    crushwheel(['gtceu:impure_uvarovite_dust', Item.of('gtceu:impure_uvarovite_dust').withChance(0.5), Item.of('gtceu:uvarovite_dust').withChance(0.1)], 'gtceu:crushed_uvarovite_ore')
    wash('gtceu:uvarovite_dust', 'gtceu:impure_uvarovite_dust')
    crushwheel(['gtceu:crushed_wulfenite_ore', Item.of('gtceu:crushed_wulfenite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_wulfenite')
    crushwheel(['gtceu:impure_wulfenite_dust', Item.of('gtceu:impure_wulfenite_dust').withChance(0.5), Item.of('gtceu:iron_dust').withChance(0.1)], 'gtceu:crushed_wulfenite_ore')
    wash('gtceu:wulfenite_dust', 'gtceu:impure_wulfenite_dust')
    crushwheel(['gtceu:crushed_yellow_limonite_ore', Item.of('gtceu:crushed_yellow_limonite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_yellow_limonite')
    crushwheel(['gtceu:impure_yellow_limonite_dust', Item.of('gtceu:impure_yellow_limonite_dust').withChance(0.5), Item.of('gtceu:nickel_dust').withChance(0.1)], 'gtceu:crushed_yellow_limonite_ore')
    wash('gtceu:yellow_limonite_dust', 'gtceu:impure_yellow_limonite_dust')
    crushwheel(['gtceu:crushed_nether_quartz_ore', Item.of('gtceu:crushed_nether_quartz_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_nether_quartz')
    crushwheel(['gtceu:impure_nether_quartz_dust', Item.of('gtceu:impure_nether_quartz_dust').withChance(0.5), Item.of('gtceu:quartzite_dust').withChance(0.1)], 'gtceu:crushed_nether_quartz_ore')
    wash('gtceu:nether_quartz_dust', 'gtceu:impure_nether_quartz_dust')
    crushwheel(['gtceu:crushed_certus_quartz_ore', Item.of('gtceu:crushed_certus_quartz_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_certus_quartz')
    crushwheel(['gtceu:impure_certus_quartz_dust', Item.of('gtceu:impure_certus_quartz_dust').withChance(0.5), Item.of('gtceu:nether_quartz_dust').withChance(0.1)], 'gtceu:crushed_certus_quartz_ore')
    wash('gtceu:certus_quartz_dust', 'gtceu:impure_certus_quartz_dust')
    crushwheel(['gtceu:crushed_quartzite_ore', Item.of('gtceu:crushed_quartzite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_quartzite')
    crushwheel(['gtceu:impure_quartzite_dust', Item.of('gtceu:impure_quartzite_dust').withChance(0.5), Item.of('gtceu:certus_quartz_dust').withChance(0.1)], 'gtceu:crushed_quartzite_ore')
    wash('gtceu:quartzite_dust', 'gtceu:impure_quartzite_dust')
    crushwheel(['gtceu:crushed_graphite_ore', Item.of('gtceu:crushed_graphite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_graphite')
    crushwheel(['gtceu:impure_graphite_dust', Item.of('gtceu:impure_graphite_dust').withChance(0.5), Item.of('gtceu:carbon_dust').withChance(0.1)], 'gtceu:crushed_graphite_ore')
    wash('gtceu:graphite_dust', 'gtceu:impure_graphite_dust')
    crushwheel(['gtceu:crushed_bornite_ore', Item.of('gtceu:crushed_bornite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_bornite')
    crushwheel(['gtceu:impure_bornite_dust', Item.of('gtceu:impure_bornite_dust').withChance(0.5), Item.of('gtceu:pyrite_dust').withChance(0.1)], 'gtceu:crushed_bornite_ore')
    wash('gtceu:bornite_dust', 'gtceu:impure_bornite_dust')
    crushwheel(['gtceu:crushed_chalcocite_ore', Item.of('gtceu:crushed_chalcocite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_chalcocite')
    crushwheel(['gtceu:impure_chalcocite_dust', Item.of('gtceu:impure_chalcocite_dust').withChance(0.5), Item.of('gtceu:sulfur_dust').withChance(0.1)], 'gtceu:crushed_chalcocite_ore')
    wash('gtceu:chalcocite_dust', 'gtceu:impure_chalcocite_dust')
    crushwheel(['gtceu:crushed_realgar_ore', Item.of('gtceu:crushed_realgar_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_realgar')
    crushwheel(['gtceu:impure_realgar_dust', Item.of('gtceu:impure_realgar_dust').withChance(0.5), Item.of('gtceu:sulfur_dust').withChance(0.1)], 'gtceu:crushed_realgar_ore')
    wash('gtceu:realgar_dust', 'gtceu:impure_realgar_dust')
    crushwheel(['gtceu:crushed_bastnasite_ore', Item.of('gtceu:crushed_bastnasite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_bastnasite')
    crushwheel(['gtceu:impure_bastnasite_dust', Item.of('gtceu:impure_bastnasite_dust').withChance(0.5), Item.of('gtceu:neodymium_dust').withChance(0.1)], 'gtceu:crushed_bastnasite_ore')
    wash('gtceu:bastnasite_dust', 'gtceu:impure_bastnasite_dust')
    crushwheel(['gtceu:crushed_pentlandite_ore', Item.of('gtceu:crushed_pentlandite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_pentlandite')
    crushwheel(['gtceu:impure_pentlandite_dust', Item.of('gtceu:impure_pentlandite_dust').withChance(0.5), Item.of('gtceu:iron_dust').withChance(0.1)], 'gtceu:crushed_pentlandite_ore')
    wash('gtceu:pentlandite_dust', 'gtceu:impure_pentlandite_dust')
    crushwheel(['gtceu:crushed_spodumene_ore', Item.of('gtceu:crushed_spodumene_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_spodumene')
    crushwheel(['gtceu:impure_spodumene_dust', Item.of('gtceu:impure_spodumene_dust').withChance(0.5), Item.of('gtceu:aluminium_dust').withChance(0.1)], 'gtceu:crushed_spodumene_ore')
    wash('gtceu:spodumene_dust', 'gtceu:impure_spodumene_dust')
    crushwheel(['gtceu:crushed_lepidolite_ore', Item.of('gtceu:crushed_lepidolite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_lepidolite')
    crushwheel(['gtceu:impure_lepidolite_dust', Item.of('gtceu:impure_lepidolite_dust').withChance(0.5), Item.of('gtceu:lithium_dust').withChance(0.1)], 'gtceu:crushed_lepidolite_ore')
    wash('gtceu:lepidolite_dust', 'gtceu:impure_lepidolite_dust')
    crushwheel(['gtceu:crushed_glauconite_sand_ore', Item.of('gtceu:crushed_glauconite_sand_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_glauconite_sand')
    crushwheel(['gtceu:impure_glauconite_sand_dust', Item.of('gtceu:impure_glauconite_sand_dust').withChance(0.5), Item.of('gtceu:sodium_dust').withChance(0.1)], 'gtceu:crushed_glauconite_sand_ore')
    wash('gtceu:glauconite_sand_dust', 'gtceu:impure_glauconite_sand_dust')
    crushwheel(['gtceu:crushed_malachite_ore', Item.of('gtceu:crushed_malachite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_malachite')
    crushwheel(['gtceu:impure_malachite_dust', Item.of('gtceu:impure_malachite_dust').withChance(0.5), Item.of('gtceu:goethite_dust').withChance(0.1)], 'gtceu:crushed_malachite_ore')
    wash('gtceu:malachite_dust', 'gtceu:impure_malachite_dust')
    crushwheel(['gtceu:crushed_mica_ore', Item.of('gtceu:crushed_mica_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_mica')
    crushwheel(['gtceu:impure_mica_dust', Item.of('gtceu:impure_mica_dust').withChance(0.5), Item.of('gtceu:potassium_dust').withChance(0.1)], 'gtceu:crushed_mica_ore')
    wash('gtceu:mica_dust', 'gtceu:impure_mica_dust')
    crushwheel(['gtceu:crushed_barite_ore', Item.of('gtceu:crushed_barite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_barite')
    crushwheel(['gtceu:impure_barite_dust', Item.of('gtceu:impure_barite_dust').withChance(0.5), Item.of('gtceu:barite_dust').withChance(0.1)], 'gtceu:crushed_barite_ore')
    wash('gtceu:barite_dust', 'gtceu:impure_barite_dust')
    crushwheel(['2x gtceu:crushed_alunite_ore', Item.of('2x gtceu:crushed_alunite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_alunite')
    crushwheel(['gtceu:impure_alunite_dust', Item.of('gtceu:impure_alunite_dust').withChance(0.5), Item.of('gtceu:alunite_dust').withChance(0.1)], 'gtceu:crushed_alunite_ore')
    wash('gtceu:alunite_dust', 'gtceu:impure_alunite_dust')
    crushwheel(['gtceu:crushed_talc_ore', Item.of('gtceu:crushed_talc_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_talc')
    crushwheel(['gtceu:impure_talc_dust', Item.of('gtceu:impure_talc_dust').withChance(0.5), Item.of('gtceu:clay_dust').withChance(0.1)], 'gtceu:crushed_talc_ore')
    wash('gtceu:talc_dust', 'gtceu:impure_talc_dust')
    crushwheel(['gtceu:crushed_soapstone_ore', Item.of('gtceu:crushed_soapstone_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_soapstone')
    crushwheel(['gtceu:impure_soapstone_dust', Item.of('gtceu:impure_soapstone_dust').withChance(0.5), Item.of('gtceu:silicon_dioxide_dust').withChance(0.1)], 'gtceu:crushed_soapstone_ore')
    wash('gtceu:soapstone_dust', 'gtceu:impure_soapstone_dust')
    crushwheel(['gtceu:crushed_kyanite_ore', Item.of('gtceu:crushed_kyanite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_kyanite')
    crushwheel(['gtceu:impure_kyanite_dust', Item.of('gtceu:impure_kyanite_dust').withChance(0.5), Item.of('gtceu:talc_dust').withChance(0.1)], 'gtceu:crushed_kyanite_ore')
    wash('gtceu:kyanite_dust', 'gtceu:impure_kyanite_dust')
    crushwheel(['gtceu:crushed_pyrochlore_ore', Item.of('gtceu:crushed_pyrochlore_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_pyrochlore')
    crushwheel(['gtceu:impure_pyrochlore_dust', Item.of('gtceu:impure_pyrochlore_dust').withChance(0.5), Item.of('gtceu:apatite_dust').withChance(0.1)], 'gtceu:crushed_pyrochlore_ore')
    wash('gtceu:pyrochlore_dust', 'gtceu:impure_pyrochlore_dust')
    crushwheel(['gtceu:crushed_oilsands_ore', Item.of('gtceu:crushed_oilsands_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_oilsands')
    crushwheel(['gtceu:impure_oilsands_dust', Item.of('gtceu:impure_oilsands_dust').withChance(0.5), Item.of('gtceu:oilsands_dust').withChance(0.1)], 'gtceu:crushed_oilsands_ore')
    wash('gtceu:oilsands_dust', 'gtceu:impure_oilsands_dust')
    crushwheel(['gtceu:crushed_perlite_ore', Item.of('gtceu:crushed_perlite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_perlite')
    crushwheel(['gtceu:impure_perlite_dust', Item.of('gtceu:impure_perlite_dust').withChance(0.5), Item.of('gtceu:perlite_dust').withChance(0.1)], 'gtceu:crushed_perlite_ore')
    wash('gtceu:perlite_dust', 'gtceu:impure_perlite_dust')
    crushwheel(['gtceu:crushed_olivine_ore', Item.of('gtceu:crushed_olivine_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_olivine')
    crushwheel(['gtceu:impure_olivine_dust', Item.of('gtceu:impure_olivine_dust').withChance(0.5), Item.of('gtceu:pyrope_dust').withChance(0.1)], 'gtceu:crushed_olivine_ore')
    wash('gtceu:olivine_dust', 'gtceu:impure_olivine_dust')
    crushwheel(['gtceu:crushed_opal_ore', Item.of('gtceu:crushed_opal_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_opal')
    crushwheel(['gtceu:impure_opal_dust', Item.of('gtceu:impure_opal_dust').withChance(0.5), Item.of('gtceu:opal_dust').withChance(0.1)], 'gtceu:crushed_opal_ore')
    wash('gtceu:opal_dust', 'gtceu:impure_opal_dust')
    crushwheel(['gtceu:crushed_amethyst_ore', Item.of('gtceu:crushed_amethyst_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_amethyst')
    crushwheel(['gtceu:impure_amethyst_dust', Item.of('gtceu:impure_amethyst_dust').withChance(0.5), Item.of('gtceu:amethyst_dust').withChance(0.1)], 'gtceu:crushed_amethyst_ore')
    wash('gtceu:amethyst_dust', 'gtceu:impure_amethyst_dust')
    crushwheel(['3x gtceu:crushed_lapis_ore', Item.of('3x gtceu:crushed_lapis_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_lapis')
    crushwheel(['gtceu:impure_lapis_dust', Item.of('gtceu:impure_lapis_dust').withChance(0.5), Item.of('4x gtceu:lazurite_dust').withChance(0.1)], 'gtceu:crushed_lapis_ore')
    wash('gtceu:lapis_dust', 'gtceu:impure_lapis_dust')
    crushwheel(['2x gtceu:crushed_apatite_ore', Item.of('2x gtceu:crushed_apatite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_apatite')
    crushwheel(['gtceu:impure_apatite_dust', Item.of('gtceu:impure_apatite_dust').withChance(0.5), Item.of('2x gtceu:tricalcium_phosphate_dust').withChance(0.1)], 'gtceu:crushed_apatite_ore')
    wash('gtceu:apatite_dust', 'gtceu:impure_apatite_dust')
    crushwheel(['2x gtceu:crushed_tricalcium_phosphate_ore', Item.of('2x gtceu:crushed_tricalcium_phosphate_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_tricalcium_phosphate')
    crushwheel(['gtceu:impure_tricalcium_phosphate_dust', Item.of('gtceu:impure_tricalcium_phosphate_dust').withChance(0.5), Item.of('gtceu:apatite_dust').withChance(0.1)], 'gtceu:crushed_tricalcium_phosphate_ore')
    wash('gtceu:tricalcium_phosphate_dust', 'gtceu:impure_tricalcium_phosphate_dust')
    crushwheel(['2x gtceu:crushed_red_garnet_ore', Item.of('2x gtceu:crushed_red_garnet_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_red_garnet')
    crushwheel(['gtceu:impure_red_garnet_dust', Item.of('gtceu:impure_red_garnet_dust').withChance(0.5), Item.of('gtceu:spessartine_dust').withChance(0.1)], 'gtceu:crushed_red_garnet_ore')
    wash('gtceu:red_garnet_dust', 'gtceu:impure_red_garnet_dust')
    crushwheel(['2x gtceu:crushed_yellow_garnet_ore', Item.of('2x gtceu:crushed_yellow_garnet_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_yellow_garnet')
    crushwheel(['gtceu:impure_yellow_garnet_dust', Item.of('gtceu:impure_yellow_garnet_dust').withChance(0.5), Item.of('gtceu:andradite_dust').withChance(0.1)], 'gtceu:crushed_yellow_garnet_ore')
    wash('gtceu:yellow_garnet_dust', 'gtceu:impure_yellow_garnet_dust')
    crushwheel(['gtceu:crushed_vanadium_magnetite_ore', Item.of('gtceu:crushed_vanadium_magnetite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_vanadium_magnetite')
    crushwheel(['gtceu:impure_vanadium_magnetite_dust', Item.of('gtceu:impure_vanadium_magnetite_dust').withChance(0.5), Item.of('gtceu:magnetite_dust').withChance(0.1)], 'gtceu:crushed_vanadium_magnetite_ore')
    wash('gtceu:vanadium_magnetite_dust', 'gtceu:impure_vanadium_magnetite_dust')
    crushwheel(['gtceu:crushed_pollucite_ore', Item.of('gtceu:crushed_pollucite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_pollucite')
    crushwheel(['gtceu:impure_pollucite_dust', Item.of('gtceu:impure_pollucite_dust').withChance(0.5), Item.of('gtceu:caesium_dust').withChance(0.1)], 'gtceu:crushed_pollucite_ore')
    wash('gtceu:pollucite_dust', 'gtceu:impure_pollucite_dust')
    crushwheel(['gtceu:crushed_fullers_earth_ore', Item.of('gtceu:crushed_fullers_earth_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_fullers_earth')
    crushwheel(['gtceu:impure_fullers_earth_dust', Item.of('gtceu:impure_fullers_earth_dust').withChance(0.5), Item.of('gtceu:aluminium_dust').withChance(0.1)], 'gtceu:crushed_fullers_earth_ore')
    wash('gtceu:fullers_earth_dust', 'gtceu:impure_fullers_earth_dust')
    crushwheel(['2x gtceu:crushed_monazite_ore', Item.of('2x gtceu:crushed_monazite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_monazite')
    crushwheel(['gtceu:impure_monazite_dust', Item.of('gtceu:impure_monazite_dust').withChance(0.5), Item.of('gtceu:thorium_dust').withChance(0.1)], 'gtceu:crushed_monazite_ore')
    wash('gtceu:monazite_dust', 'gtceu:impure_monazite_dust')
    crushwheel(['gtceu:crushed_trona_ore', Item.of('gtceu:crushed_trona_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_trona')
    crushwheel(['gtceu:impure_trona_dust', Item.of('gtceu:impure_trona_dust').withChance(0.5), Item.of('gtceu:sodium_dust').withChance(0.1)], 'gtceu:crushed_trona_ore')
    wash('gtceu:trona_dust', 'gtceu:impure_trona_dust')
    crushwheel(['gtceu:crushed_gypsum_ore', Item.of('gtceu:crushed_gypsum_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_gypsum')
    crushwheel(['gtceu:impure_gypsum_dust', Item.of('gtceu:impure_gypsum_dust').withChance(0.5), Item.of('gtceu:sulfur_dust').withChance(0.1)], 'gtceu:crushed_gypsum_ore')
    wash('gtceu:gypsum_dust', 'gtceu:impure_gypsum_dust')
    crushwheel(['2x gtceu:crushed_zeolite_ore', Item.of('2x gtceu:crushed_zeolite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_zeolite')
    crushwheel(['gtceu:impure_zeolite_dust', Item.of('gtceu:impure_zeolite_dust').withChance(0.5), Item.of('gtceu:calcium_dust').withChance(0.1)], 'gtceu:crushed_zeolite_ore')
    wash('gtceu:zeolite_dust', 'gtceu:impure_zeolite_dust')
    crushwheel(['5x gtceu:crushed_redstone_ore', Item.of('5x gtceu:crushed_redstone_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_redstone')
    crushwheel(['gtceu:impure_redstone_dust', Item.of('gtceu:impure_redstone_dust').withChance(0.5), Item.of('gtceu:cinnabar_dust').withChance(0.1)], 'gtceu:crushed_redstone_ore')
    wash('gtceu:redstone_dust', 'gtceu:impure_redstone_dust')
    crushwheel(['5x gtceu:crushed_electrotine_ore', Item.of('5x gtceu:crushed_electrotine_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_electrotine')
    crushwheel(['gtceu:impure_electrotine_dust', Item.of('gtceu:impure_electrotine_dust').withChance(0.5), Item.of('minecraft:redstone').withChance(0.1)], 'gtceu:crushed_electrotine_ore')
    wash('gtceu:electrotine_dust', 'gtceu:impure_electrotine_dust')
    crushwheel(['gtceu:crushed_diatomite_ore', Item.of('gtceu:crushed_diatomite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_diatomite')
    crushwheel(['gtceu:impure_diatomite_dust', Item.of('gtceu:impure_diatomite_dust').withChance(0.5), Item.of('gtceu:hematite_dust').withChance(0.1)], 'gtceu:crushed_diatomite_ore')
    wash('gtceu:diatomite_dust', 'gtceu:impure_diatomite_dust')
    crushwheel(['gtceu:crushed_granitic_mineral_sand_ore', Item.of('gtceu:crushed_granitic_mineral_sand_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_granitic_mineral_sand')
    crushwheel(['gtceu:impure_granitic_mineral_sand_dust', Item.of('gtceu:impure_granitic_mineral_sand_dust').withChance(0.5), Item.of('gtceu:deepslate_dust').withChance(0.1)], 'gtceu:crushed_granitic_mineral_sand_ore')
    wash('gtceu:granitic_mineral_sand_dust', 'gtceu:impure_granitic_mineral_sand_dust')
    crushwheel(['gtceu:crushed_garnet_sand_ore', Item.of('gtceu:crushed_garnet_sand_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_garnet_sand')
    crushwheel(['gtceu:impure_garnet_sand_dust', Item.of('gtceu:impure_garnet_sand_dust').withChance(0.5), Item.of('gtceu:red_garnet_dust').withChance(0.1)], 'gtceu:crushed_garnet_sand_ore')
    wash('gtceu:garnet_sand_dust', 'gtceu:impure_garnet_sand_dust')
    crushwheel(['gtceu:crushed_basaltic_mineral_sand_ore', Item.of('gtceu:crushed_basaltic_mineral_sand_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_basaltic_mineral_sand')
    crushwheel(['gtceu:impure_basaltic_mineral_sand_dust', Item.of('gtceu:impure_basaltic_mineral_sand_dust').withChance(0.5), Item.of('gtceu:basalt_dust').withChance(0.1)], 'gtceu:crushed_basaltic_mineral_sand_ore')
    wash('gtceu:basaltic_mineral_sand_dust', 'gtceu:impure_basaltic_mineral_sand_dust')
    crushwheel(['gtceu:crushed_space_neutronium_ore', Item.of('gtceu:crushed_space_neutronium_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_space_neutronium')
    crushwheel(['gtceu:impure_space_neutronium_dust', Item.of('gtceu:impure_space_neutronium_dust').withChance(0.5), Item.of('gtceu:space_neutronium_dust').withChance(0.1)], 'gtceu:crushed_space_neutronium_ore')
    wash('gtceu:space_neutronium_dust', 'gtceu:impure_space_neutronium_dust')
    crushwheel(['gtceu:crushed_infinity_ore', Item.of('gtceu:crushed_infinity_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_infinity')
    crushwheel(['gtceu:impure_infinity_dust', Item.of('gtceu:impure_infinity_dust').withChance(0.5), Item.of('gtceu:infinity_dust').withChance(0.1)], 'gtceu:crushed_infinity_ore')
    wash('gtceu:infinity_dust', 'gtceu:impure_infinity_dust')
    crushwheel(['gtceu:crushed_infinity_catalyst_ore', Item.of('gtceu:crushed_infinity_catalyst_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_infinity_catalyst')
    crushwheel(['gtceu:impure_infinity_catalyst_dust', Item.of('gtceu:impure_infinity_catalyst_dust').withChance(0.5), Item.of('gtceu:infinity_catalyst_dust').withChance(0.1)], 'gtceu:crushed_infinity_catalyst_ore')
    wash('gtceu:infinity_catalyst_dust', 'gtceu:impure_infinity_catalyst_dust')
    crushwheel(['gtceu:crushed_arcane_crystal_ore', Item.of('gtceu:crushed_arcane_crystal_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_arcane_crystal')
    crushwheel(['gtceu:impure_arcane_crystal_dust', Item.of('gtceu:impure_arcane_crystal_dust').withChance(0.5), Item.of('gtceu:arcane_crystal_dust').withChance(0.1)], 'gtceu:crushed_arcane_crystal_ore')
    wash('gtceu:arcane_crystal_dust', 'gtceu:impure_arcane_crystal_dust')
    crushwheel(['gtceu:crushed_wollastonite_ore', Item.of('gtceu:crushed_wollastonite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_wollastonite')
    crushwheel(['gtceu:impure_wollastonite_dust', Item.of('gtceu:impure_wollastonite_dust').withChance(0.5), Item.of('gtceu:wollastonite_dust').withChance(0.1)], 'gtceu:crushed_wollastonite_ore')
    wash('gtceu:wollastonite_dust', 'gtceu:impure_wollastonite_dust')
    crushwheel(['gtceu:crushed_kaolinite_ore', Item.of('gtceu:crushed_kaolinite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_kaolinite')
    crushwheel(['gtceu:impure_kaolinite_dust', Item.of('gtceu:impure_kaolinite_dust').withChance(0.5), Item.of('gtceu:kaolinite_dust').withChance(0.1)], 'gtceu:crushed_kaolinite_ore')
    wash('gtceu:kaolinite_dust', 'gtceu:impure_kaolinite_dust')
    crushwheel(['gtceu:crushed_dolomite_ore', Item.of('gtceu:crushed_dolomite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_dolomite')
    crushwheel(['gtceu:impure_dolomite_dust', Item.of('gtceu:impure_dolomite_dust').withChance(0.5), Item.of('gtceu:dolomite_dust').withChance(0.1)], 'gtceu:crushed_dolomite_ore')
    wash('gtceu:dolomite_dust', 'gtceu:impure_dolomite_dust')
    /*crushwheel(['gtceu:crushed_desh_ore', Item.of('gtceu:crushed_desh_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_desh')
    crushwheel(['gtceu:impure_desh_dust', Item.of('gtceu:impure_desh_dust').withChance(0.5), Item.of('gtceu:desh_dust').withChance(0.1)], 'gtceu:crushed_desh_ore')
    wash('gtceu:desh_dust', 'gtceu:impure_desh_dust')
    crushwheel(['gtceu:crushed_ostrum_ore', Item.of('gtceu:crushed_ostrum_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_ostrum')
    crushwheel(['gtceu:impure_ostrum_dust', Item.of('gtceu:impure_ostrum_dust').withChance(0.5), Item.of('gtceu:ostrum_dust').withChance(0.1)], 'gtceu:crushed_ostrum_ore')
    wash('gtceu:ostrum_dust', 'gtceu:impure_ostrum_dust')
    crushwheel(['gtceu:crushed_calorite_ore', Item.of('gtceu:crushed_calorite_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_calorite')
    crushwheel(['gtceu:impure_calorite_dust', Item.of('gtceu:impure_calorite_dust').withChance(0.5), Item.of('gtceu:calorite_dust').withChance(0.1)], 'gtceu:crushed_calorite_ore')
    wash('gtceu:calorite_dust', 'gtceu:impure_calorite_dust')*/
    crushwheel(['gtceu:crushed_zinc_ore', Item.of('gtceu:crushed_zinc_ore').withChance(0.5), Item.of('create:experience_nugget').withChance(0.75)], 'gtceu:raw_zinc')
    crushwheel(['gtceu:impure_zinc_dust', Item.of('gtceu:impure_zinc_dust').withChance(0.5), Item.of('gtceu:zinc_dust').withChance(0.1)], 'gtceu:crushed_zinc_ore')
    wash('gtceu:zinc_dust', 'gtceu:impure_zinc_dust')
})