ServerEvents.recipes(event => {
//Gunpowder line
    event.recipes.gtceu.chemical_reactor('nitrocellulose')
        .circuit(16)
        .itemInputs('5x minecraft:paper')
        .inputFluids('gtceu:nitric_acid 3000', 'gtceu:sulfuric_acid 8000')
        .itemOutputs('5x gtceu:nitrocellulose_ingot')
        .outputFluids('minecraft:water 3000')
        .duration(200)
        .EUt(24)
    event.recipes.gtceu.chemical_reactor('barium_nitride')
        .circuit(16)
        .itemInputs('3x gtceu:barium_dust')
        .inputFluids('gtceu:nitrogen 2000')
        .itemOutputs('5x gtceu:barium_nitride_dust')
        .duration(200)
        .EUt(24)
    event.recipes.gtceu.chemical_reactor('lead_styphnate')
        .circuit(16)
        .itemInputs('gtceu:lead_dust', '6x gtceu:carbon_dust')
        .inputFluids('gtceu:hydrogen 1000', 'gtceu:nitrogen 3000', 'gtceu:oxygen 8000')
        .itemOutputs('19x gtceu:lead_styphnate_dust')
        .duration(200)
        .EUt(24)

    event.shapeless(Item.of('pointblank:guninternals'), ['2x gtceu:small_steel_gear', '4x gtceu:small_steel_spring', '2x gtceu:steel_bolt', 'gtceu:steel_plate'])
})