GTCEuStartupEvents.registry('gtceu:material', event => {
    const INFINITY = GTMaterialIconSet.getByName('infinity');
    const STELLAR_MATTER = GTMaterialIconSet.getByName('stellar_matter');
    const SUB_ATOMIC = GTMaterialIconSet.getByName('sub_atomic');
    const EXPERIENCE = GTMaterialIconSet.getByName('experience')

//Element Materials
    event.create('desh')
        .ingot()
        .fluid()
        .ore()
        .color(0xF2A057).secondaryColor(0x2E2F04)
        .element('desh')
        .iconSet(METALLIC)
        .flags(plates, dense_plate, foil)
        .blastTemp(1000, null, AMv, 1000)

    event.create('ostrum')
        .ingot()
        .fluid()
        .ore()
        .color(0xE5939B).secondaryColor(0x2F0425)
        .element('ostrum')
        .iconSet(METALLIC)
        .flags(plates, dense_plate, foil)
        .blastTemp(2500, 'low', AHv, 2000)

    event.create('calorite')
        .ingot()
        .fluid()
        .ore()
        .color(0xE65757).secondaryColor(0x2F0506)
        .element('calorite')
        .iconSet(METALLIC)
        .flags(plates, dense_plate, foil)
        .blastTemp(3500, 'mid', AEv, 3000)

    event.create('mithril')
        .ingot()
        .fluid()
        .ore(1, 1)
        .element('mithril')
        .color(0x95F9F1)
        //.secondaryColor(0x13414E)
        .iconSet(METALLIC)
        .flags(plates)
        .blastTemp(7200, 'highest', 61440, 600)
        .cableProperties(GTValues.V[GTValues.UV], 4, 4, false)
    
    event.create('protonium')
        .ingot()
        .fluid()
        .element('protonium')
        .color(0xFF7F7F).secondaryColor(0x232020)
        .iconSet(RADIOACTIVE)
        .radioactiveHazard(10)

    event.create('adamantite')
        .ingot()
        .fluid()
        .element('adamantite')
        .color(0xAD0F0D)
        .iconSet(SHINY)
        .flags(plates)
        .blastTemp(10800, 'highest', AUHv, 1200)
    
    event.create('draconium')
        .ingot()
        .fluid()
        .ore(1, 1)
        .color(0x7A42AE)
        .element('draconium')
        .iconSet(METALLIC)
        .flags(plates, rod, bolt_and_screw)
        .blastTemp(7200, 'highest', ALUv, 2000)
        .cableProperties(GTValues.V[GTValues.UEV], 8, 4, false)
    
    event.create('awakened_draconium')
        .ingot()
        .fluid()
        .color(0xFF6A00)
        .element('awakened_draconium')
        .iconSet(METALLIC)
        .flags(plates, rod, bolt_and_screw)
        .blastTemp(10800, 'highest', AUHv, 25000)
        .cableProperties(GTValues.V[GTValues.MAX], 8192, 0, true)

    event.create('radiance')
        .gas()
        .color(0x000000)
        .element('radiance')

    /*event.create('refined_radiance')
        .ingot()
        .fluid()
        .plasma()
        .color(0xF5FAE1)
        .element('radiance')
        .blastTemp(9750, 'higher', AUHv, 2400)
        .iconSet(DULL)

    event.create('shadow_steel')
        .ingot()
        .fluid()
        .color(0x575366)
        .element('shadow_steel')
        .blastTemp(9500, 'higher', AUHv, 2400)
        .iconSet(DULL)*/

    event.create('void')
        ['fluid(com.gregtechceu.gtceu.api.fluids.store.FluidStorageKey,com.gregtechceu.gtceu.api.fluids.FluidBuilder)']
        (GTFluidStorageKeys.PLASMA, new GTFluidBuilder().state(GTFluidState.PLASMA).customStill())
        .color(0x1E1333)
        .element('void')

    event.create('stellar_matter')
        .ingot()
        ['fluid(com.gregtechceu.gtceu.api.fluids.store.FluidStorageKey,com.gregtechceu.gtceu.api.fluids.FluidBuilder)']
        (GTFluidStorageKeys.LIQUID, new GTFluidBuilder().state(GTFluidState.LIQUID).customStill())
        ['fluid(com.gregtechceu.gtceu.api.fluids.store.FluidStorageKey,com.gregtechceu.gtceu.api.fluids.FluidBuilder)']
        (GTFluidStorageKeys.PLASMA, new GTFluidBuilder().state(GTFluidState.PLASMA).customStill())
        //.color(0xFFA963)
        .element('stellar_matter')
        .iconSet(STELLAR_MATTER)
        .flags(plates, rod, bolt_and_screw)
        .blastTemp(11530, null, AZPm/2, 14000)
        .cableProperties(GTValues.V[GTValues.UIV], 16, 0, true)

    /*event.create('infinity')
        .ingot()
        .fluid()
        //.color(0xFFFFFF)
        .element('infinity')
        .iconSet(INFINITY)
        .flags(plates, rod, bolt_and_screw)
        .cableProperties(GTValues.V[GTValues.MAX], 1000000, 0, true)*/

    event.create('ardite')
        .ingot()
        .fluid()
        .ore(1, 1)
        .color(0xE88317)
        .element('ardite')
        .iconSet(METALLIC)
        .flags(plates)
        .blastTemp(3500, 'mid', AHv, 2400)

    event.create('experience')
        .ingot()
        .fluid()
        .color(0x3ED900)
        .element('experience')
        .iconSet(EXPERIENCE)

    event.create('cognitive_amalgam')
        .ingot()
        .fluid()
        .color(0x3B466A)
        .element('cognitium')
        .iconSet(EXPERIENCE)
})