GTCEuStartupEvents.registry('gtceu:material', event => {
//Ores
    event.create('rose_quartz')
        .ore(2, 1)
        .gem()
        .fluid()
        .components('8x redstone', '1x flint')
        .color(0xeb4b4b)
        .iconSet(GEM_HORIZONTAL)
        .flags(plates, rod, lens, mortar_grind)

    event.create('charged_certus')
        .ore(2, 1)
        .gem()
        .components('certus_quartz')
        .color(0x99bbff)
        .secondaryColor(0x6dacc5)
        .iconSet(CERTUS)
        .flags(lens, no_plate_compressor_craft)

    event.create('zircon')
        .ore()
            .addOreByproducts(/*'zircon',*/ 'hafnium')
            .oreSmeltInto('zirconium_ingot')
            .washedIn('sodium_persulfate')
        .components('zirconium', 'silicon', '4x oxygen')
        .color(0xfff0e2)
        .iconSet(DULL)
        .flags()

    event.create('lignite')
        .ore(2, 1)
        .gem()
        .burnTime(1200)
        .components('carbon')
        .color(0x513939)
        .iconSet(LIGNITE)
        .flags(lens)

    event.create('wustite')
        .ore(1, 1)
        .components('iron', 'oxygen')
        .color(0x382C26)

    event.create('lunite')
        .gem()
        .ore(2, 1)
        .iconSet(OPAL)
        .components('9x silicon_dioxide', '2x aluminium', '2x wustite')
        .color(0x5695E2)
        .flags(plates, lens)

    event.create('ostrite')
        .ore(1, 1)
        .color(0xC47F71).secondaryColor(0x4F0663)
        .components('3x ostrum', '2x tantalite', '3x wustite', '4x magnesia')
        .iconSet(METALLIC)

    event.create('uranium_oxide')
        .ore(1, 1)
        .color(0x1d891d).secondaryColor(0x313A27)
        .components('uranium', '2x oxygen')
        .iconSet(RADIOACTIVE)
        .radioactiveHazard(1)

    event.create('zirconium_oxide')
        .ore(1, 1)
        .color(0xfff0e2).secondaryColor(0x271813)
        .components('zirconium', '2x oxygen')
        .iconSet(METALLIC)

    event.create('hafnium_oxide')
        .ore(1, 1)
        .color(0x99999A).secondaryColor(0x2b4a3a)
        .components('hafnium', '2x oxygen')
        .iconSet(SHINY)

    event.create('cerium_oxide')
        .ore(1, 1)
        .color(0x7B544E)
        .components('cerium', '2x oxygen')
        .iconSet(RADIOACTIVE)

    event.create('carobbiite')
        .ore(2, 1)
        .gem()
        .color(0xC6C791)
        .iconSet(CERTUS)
        .components('potassium', 'fluorine')
        .flags(lens)

    event.create('villiaumite')
        .ore(2, 1)
        .gem()
        .color(0xD13351)
        .iconSet(LAPIS)
        .components('sodium', 'fluorine')
        .flags(lens)
        
    event.create('fluorite')
        .ore(2, 1)
        .gem()
        .color(0x90AE99)
        .iconSet(QUARTZ)
        .components('calcium', '2x fluorine')
        .flags(lens)

    event.create('rhodochrosite')
        .ore(2, 1)
        .gem()
        .color(0xDD4243)
        .iconSet(EMERALD)
        .components('manganese', 'carbon', '3x oxygen')
        .flags(lens)

    event.create('titanite')
        .ore(2, 1)
        .gem()
        .color(0x3B9E1A)
        .iconSet(GEM_HORIZONTAL)
        .components('calcium', 'titanium', 'silicon', '5x oxygen')
        .washedIn(GTMaterials.SodiumPersulfate)
        .flags(lens)

    event.create('nepheline')
        .ore(2, 1)
        .gem()
        .color(0x524C54)
        .iconSet(QUARTZ)
        .components('3x sodium', 'potassium', '4x aluminium', '4x silicon', '16x oxygen')
        .washedIn(GTMaterials.SodiumPersulfate)
        .flags(lens)

    event.create('ulexite')
        .ore(1, 1)
        .ingot()
        .fluid()
        .color(0xF5FFF4)
        .iconSet(SHINY)
        .components('sodium', 'calcium', '5x boron', '12x oxygen', '6x hydrogen', '5x water')
        .flags(fine_wire)

    event.create('jade')
        .ore(2, 1)
        .gem()
        .color(0x256B32)
        .iconSet(GEM_VERTICAL)
        .components('sodium', 'aluminium', '2x silicon', '6x oxygen')
        .flags(lens)
    
    event.create('kunzite')
        .ore(2, 1)
        .gem()
        .color(0xFF10FF)
        .iconSet(QUARTZ)
        .components('lithium', 'aluminium', '2x silicon', '6x oxygen', 'manganese')
        .flags(lens)

    event.create('porphyry_copper')
        .ore(1, 3)
        .color(0x77dd77)
        .iconSet(DULL)
        .components('12x copper', '3x silver', 'tellurium')
})